### ISSUE TITLE
Web Service not clear

### ISSUE THREAD

**Issue by sunojvijayan** [multiOTP/multiotp#1]
Hi Can you please explain how web service works? The document is not clear on that. Please help?

**Comment by multiOTP** [comment]
Hello,

The current web service is for "private" communication between two multiOTP instances and is not designed to be used by "public" parties.

A public (SOAP based) web service will be available and documented in the next release available in the next weeks.

Best regards,

Andre

**Comment by sunojvijayan** [comment]
Thanks for the update.

**Comment by sunojvijayan** [comment]
I have one more question. When i create a user i specified the token time interval as 

$multiotp = new Multiotp('DefaultCliEncryptionKey', FALSE);
$multiotp->SetUser($user);
$multiotp->SetUserTokenTimeInterval(60);

But its taking the default value  30. how can i change it?

**Comment by multiOTP** [comment]
Hello,

Are you doing the $multiotp->WriteUserData(); after the changes ?

For performance and optimization issues (the backend can be database or flat files, and the library is also used on nano computers like Raspberry Pi), the WriteUserData is not down after each changes and must be done manually, .

$multiotp = new Multiotp('DefaultCliEncryptionKey', FALSE);
$multiotp->SetUser($user);
$multiotp->SetUserTokenTimeInterval(60);
$multiotp->WriteUserData();

If you are using flat files backend, you should see the new value in the "$user".db file (which is a readable text file).

Regards,

**Comment by multiOTP** [comment]
As this is not related to the title topic (Web Service not clear), you should open a new issue if it's a "real" issue. Regards
