### ISSUE TITLE
Error when upgraded to PHP 7.0

### ISSUE THREAD

**Issue by cymapgt** [multiOTP/multiotp#10]
When you upgrade to PHP7, you get a **PHP Fatal error:  'break' not in the 'loop' or 'switch' context** error due to a rogue break statement on line 1461

![screenshot from 2016-09-21 13 47 26](https://cloud.githubusercontent.com/assets/12482626/18708196/599a89a4-8002-11e6-9678-10828196c3dd.png)

**Comment by multiOTP** [comment]
Thanks, this has been corrected in the 5.0.2.5 release which will be posted soon.
