### ISSUE TITLE
Feature request : Use "Display Name" instead of "User Description" in Print Template 

### ISSUE THREAD

**Issue by Jonathan-Garber** [multiOTP/multiotp#100]
I may have overlooked it but is there a template tag to use for "Display Name" from AD as opposed to "User Description"

```
MultiotpUserDescription
```
Results in displaying the user description text from Active Directory on the printed page for that users account.

I want to use the users "Display Name" from Active Directory instead so maybe a tag like
```
MultiotpUserDisplayName
```
Could return that Display Name.

**Comment by multiOTP** [comment]
Hello,
thanks for suggestion, we will see if this is possible for a future release.
Best regards

**Comment by multiOTP** [comment]
{MultiotpUserDisplayName} is now a valid tag since version 5.9.0.3.

**Comment by multiOTP** [comment]
Hello,
The {MultiotpUserDisplayName} must be changed in the templates (template.html, scratchtemplate.html).
Replace {MultiotpUserDescription} by {MultiotpUserDisplayName}
Regards,

**Comment by mactruitasse** [comment]
Hello,
I am using the version 5.9.7.1 of Multiotp, when I am doing the {MultiotpUserDisplayName} nothing is showing. 

We found a workaround in changing the value in the description column in the database post synchronisation with the active directory.

Regards.

**Comment by multiOTP** [comment]
Hello,
this will be corrected in the next release.
Best regards.

**Comment by multiOTP** [comment]
This is now fixed in version 5.9.9.1 and above.
