### ISSUE TITLE
Credential Provider for RDP using Microsoft Account

### ISSUE THREAD

**Issue by mattburris** [multiOTP/multiotp#101]
There is an section of the help for the Credential Provider setup that indicates that a Microsoft Account can be used:

(from https://github.com/multiOTP/multiOTPCredentialProvider#prerequisites ):
configured multiOTP user (multiOTP username = [domain user name] or [windows local account name] or [microsoft account name])

I cannot for the life of me figure out how to get the credential provider working with a Microsoft account.

When I type my MS account into the MultiOTP Credential Provider setup - "MultiOTP configuration test" window, and hit the test button, it gives me the following error: 
"Windows login failed: the parameter is incorrect"

Any help would be appreciated.
![Annotation 2021-02-06 161535](https://user-images.githubusercontent.com/3037795/107128631-0e479780-6874-11eb-8962-ea075d11d004.png)

**Comment by multiOTP** [comment]
Hello,

This is a Credential Provider issue, not a multiOTP issue.

It seems the OTP checker before activating the Credential Provider is not working well with Microsoft Account. 

**But you can try to activate manually the Credential Provider with the register.reg file provided, just be careful not to loose access to your computer (in any case, you can still login in recovery mode and launch the Unregister.reg to remove the Credential Provider).**

A brand new version 6 of the credential provider should be available in the next monthes (currently in promising internal alpha tests).

Regards,

**Comment by multiOTP** [comment]
Hello,
Please note that this issue will be close because it's not in the correct repository.
If you still have an issue with the Credential Provider, please open a new issue in the [multiOTP Credential Provider](https://github.com/multiOTP/multiOTPCredentialProvider) repository.
Regards,
