### ISSUE TITLE
 [multiotp 5.8.1.0] docker build failed  E: Unable to locate package apt-offline

### ISSUE THREAD

**Issue by WilliamFromTW** [multiOTP/multiotp#102]
docker build stop :
 **E: Unable to locate package apt-offline**

docker  build success after add 
RUN echo "deb http://ftp.de.debian.org/debian buster-backports main" |  tee /etc/apt/sources.list.d/docker.list
 
![Screen Shot 2021-03-08 at 6 46 51 PM](https://user-images.githubusercontent.com/5213198/110311876-59092a80-803f-11eb-989c-b59dfcbef433.png)

**Comment by multiOTP** [comment]
Hello William,
Thanks for the fix. The apt-offline package is no needed anymore.
It will be removed in the next version.
Regards,
