### ISSUE TITLE
OTP codes are not triggered after daylight saving time multiOTP 5.8.1.0 2021-02-12

### ISSUE THREAD

**Issue by cyxopykov** [multiOTP/multiotp#103]
OTP codes are not triggered after daylight saving time (15.03.2021)
Time on server and clients is the same and synchronized, but only spare codes are triggered

failed (99 ERROR: Authentication failed (and other possible unknown errors))
For newly created users, the same problem

**Comment by multiOTP** [comment]
Hello,
Try release 5.8.1.1. Please be also sure that you didn'tchange the "real" time of your server, but only the DST setup.
Regards,
Andre

**Comment by cyxopykov** [comment]
on https://download.multiotp.net/ available only 5.8.1.0

My time zone does not switch to daylight saving time in Windows Server 2012 settings
The displayed time on the server and on the phone whith google authenticator is the same

**Comment by cyxopykov** [comment]
> Hello,
> Try release 5.8.1.1. Please be also sure that you didn'tchange the "real" time of your server, but only the DST setup.
> Regards,
> Andre
on https://download.multiotp.net/ available only 5.8.1.0

My time zone does not switch to daylight saving time in Windows Server 2012 settings
The displayed time on the server and on the phone whith google authenticator is the same

**Comment by multiOTP** [comment]
Did you try release 5.8.1.1 ?
Check also your timezone in your PHP configuration.

**Comment by cyxopykov** [comment]
> Did you try release 5.8.1.1 ?
> Check also your timezone in your PHP configuration.

on https://download.multiotp.net/  is only available 5.8.1.0
I changed In C:\multiotp\windows\php and C:\multiotp\windows\config
timezone=Europe/Minsk 

one and the same as in Windows

**Comment by cyxopykov** [comment]
> Did you try release 5.8.1.1 ?
> Check also your timezone in your PHP configuration.
I  try release 5.8.1.1 And it helped I can add new users

Can I update the version while keeping old users?

**Comment by multiOTP** [comment]
Cool, thx for the feedback.
