### ISSUE TITLE
Docker setup two errors

### ISSUE THREAD

**Issue by rakeone** [multiOTP/multiotp#104]
Hi,
I am trying to make the docker setup work so I can try this software.
First problem I encountered is that it tries to build the docker with the Dockerfile and it misses a package (apt-offline). 
So I decided to try an older version (that runs debian 9 instead of debian 10), which works.

And then I have the error

Zeroing disk space...
dd: error writing '/zeroes': No space left on device

It fills 32 GB of zero.

Maybe I am missing something, is there more documentation than the docker build and docker run commands ?

Thank you.

Carl

**Comment by multiOTP** [comment]
Hi,
The apt-offline package can be safely removed.
The dd is done in the "regular" script in order to be able to shrink to the best possible compression a virtual appliance.
We will have a look to see why this is running when started with Docker.
Regards

**Comment by multiOTP** [comment]
Hello,
Dockerfile has been update to version 5.8.1.9, which will fix these issues due to bad Docker detection in the script.
The docker repository has also been updated.
Regards,
