### ISSUE TITLE
Vulnerability (cookie attributes in commercial releases)

### ISSUE THREAD

**Issue by karkaaa** [multiOTP/multiotp#107]
Not fixed on 5.8.1.1 and same vulnerability @multiOTP

https://github.com/multiOTP/multiotp/issues/75

and "Weak Cipher Suites"

**Comment by multiOTP** [comment]
Hello,
The 'vulnerable' detected cookie by OpenVAS was a language option cookie.
Anyway, we have fixed this issue for previous virtual appliance also, as well as 'TCP timestamps' and 'weak SSL encryption' warnings.
5.8.1.9 update is running test units on various virtual appliance (starting on version 002) and will be available in the next hours.
Regards,

**Comment by multiOTP** [comment]
The version 5.8.1.9 is now available and has been tested using OpenVAS on virtual appliance foundations from 002 to 010.
