### ISSUE TITLE
During RDP connection, the saved login and password are not transferred.

### ISSUE THREAD

**Issue by IGRYNS** [multiOTP/multiotp#108]
When connecting via RDP to the server, the login and password are not transmitted.

You must select Other user and enter data. Can I transfer a pre-saved account?

**Comment by multiOTP** [comment]
Hello,
Please note that this issue has to be opened in the https://github.com/multiOTP/multiOTPCredentialProvider repository.
We are in the beta phase of a new version of the multiOTP Credential Provider which transmit the login and the password. The new release will be available in the next weeks.
Regards,
Andre

**Comment by IGRYNS** [comment]
Good day.
Can't hear when there will be an update? We are waiting for him =))

------------------------
Пасечник Александр
На 07.05.2021 10:19:31, multiOTP ***@***.***> написал(а):
Hello,
Please note that this issue has to be opened in the https://github.com/multiOTP/multiOTPCredentialProvider [https://github.com/multiOTP/multiOTPCredentialProvider] repository.
We are in the beta phase of a new version of the multiOTP Credential Provider which transmit the login and the password. The new release will be available in the next weeks.
Regards,
Andre
