### ISSUE TITLE
Host is Vulnerable to Extended Master Secret TLS Extension (TLS triple handshake)

### ISSUE THREAD

**Issue by skgospodinov** [multiOTP/multiotp#112]
Hello, I am writing you in order with the vulnerability detected in MultiOTP web server: Host is Vulnerable to Extended Master Secret TLS Extension (TLS triple handshake). From what I understand the problem is in nginx software: https://forum.nginx.org/read.php?2,272703,272704#msg-272704 
I want to ask you if I can desable it somwhere in configuration files.

MultiOTP version: 5.8.1.9

Best Regards
Stoyan

**Comment by multiOTP** [comment]
Hello,
How did you deploy your multiOTP 5.8.1.9 exactly ?
Are you running on Windows, Linux, Docker ?
Regards,

**Comment by skgospodinov** [comment]
Hello, 

We have implemented multiOTP 5.8.1.9 server running on Windows 2019, synchronizing the users from an Active Directory.  multiOTP Credential Provider is installed on another three Windows 2019 servers. We are using TOTP as second factor.

Please contact me if something else is neeeded as information.

Best Regards

**Comment by multiOTP** [comment]
The nginx provided in the Windows open source package is relatively old (2017).
Stop the web service on the Windows server, download the last version here : http://nginx.org/download/nginx-1.21.4.zip, unzip the package, take only the nginx.exe and replace the old nginx.exe on the server with the new one.
Regards

**Comment by skgospodinov** [comment]
Hello, 

Thank you very much for your support. After replacing nginx.exe the mentioned vulnerability above is fixed.

Best Regards
Stoyan

**Comment by multiOTP** [comment]
You're welcome
