### ISSUE TITLE
About the issue shows the radius 

### ISSUE THREAD

**Issue by Wilson0502** [multiOTP/multiotp#113]
Hi, I got an error message showing the Access-Reject packet from home server 127.0.0.1 port 41812 with invalid Response Authenticator! when I was running the checkmultiotp.
Does anyone know how to solve this issue? thanks
![received Access-Reject](https://user-images.githubusercontent.com/48788816/140321958-a08a3c72-5761-4dc1-bea6-a0cccb9b3b3d.png)

**Comment by multiOTP** [comment]
Hello,
The shared secret seems to be incorrect. What is the shared secret defined in the RADIUS server ?
Where is installed the RADIUS server ?
Are you running everyrhing under Windows or Linux ?
Regards,

**Comment by multiOTP** [comment]
No news since almost two monthes.
