### ISSUE TITLE
How to exclude Administrator account from OTP

### ISSUE THREAD

**Issue by umardraz** [multiOTP/multiotp#116]
Hi

Is there any option that I can exclude Administrator account for OTP, I don't want that OTP required for Administrator account

**Comment by multiOTP** [comment]
Hello,
yes this feature is available in the latest version of the credential provider. You need to set the following registry key.

HKEY_CLASSES_ROOT\CLSID{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\excluded_account

Please use the following format domain\username or computername\username

Best regards

**Comment by multiOTP** [comment]
Hello,
you have the latest version. You can always found the latest version at the bottom of this page : https://download.multiotp.net/credential-provider/

For example you create a REG_SZ key under HKEY_CLASSES_ROOT\CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978} called excluded_account and you set the value to myDomain\Administrator  (please replace MyDomain by your actual domain or your computer name; and Administrator by the username you wish to exclude from the OTP process)
The CLSID value is always the same. It's a product id.
Best regards

**Comment by umardraz** [comment]
Hi Thanks for your reply, I am still confused about this CLSID{xxx}. In my AWS VM there are hundred of thousand garbage entries under CLSID and not sure that which one is that I need to modify. 

You have mentioned that (HKEY_CLASSES_ROOT\CLSID{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}) is a product id. but if I see my windows product id, then that is something 00377-00001-02222-AA753

Regards,

Umar

**Comment by multiOTP** [comment]
Hello,
first you need to install multiOTP credential provider and configure it. Once installed, the registry key {FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978} will be automatically created during installation. {FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978} is multiOTP credential unique CLSID. All computers with multiOTP credential provider installed have that specific key. That's where all the configuration is stored.
Best regards

**Comment by multiOTP** [comment]
Once the authentication process is done, multiOTP is no longer involved in the rdp process.
I would check the computer sleep timeout or the session idle timeout.

Best regards
