### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by burghy86** [multiOTP/multiotp#117]
hi. how to setup secret on a docker? i setup multiotp on synology server.

there a manual for a docker? a guide? a video, a comment to help me?

i find this bug.
port 80 not permit logon on a web interface

if use a command -v to map a volume the cert and all configuration will not generated
-v /volume1/docker/multiotp:/etc/multiopt  command not work

how to see a secret key not encrypt to config my client?

your forum does not allow registration without an invitation 

can i have a community support?

please insert a variable in a dockerimage to set a parameters

**Comment by sibberio** [comment]
Hi there!
I played a litte bit with the docker container with @burghy86 
What we discovered it's that, first of all, the docker image it's a little bit old so would be great to have a new one.

Then, as said by @burghy86 port 80 is not working.
Also, the first start/install didn't place the certificates under /etc/multiotp folder mapped on the docker host. So also the SSL contection was not working.

After some trouble, in a docker on Synology NAS, I was able to sync the users in AD. The I tried to install the credential provider on a Windows 10 PC and test it. User unknown.

I tried the to install the container on a QNAP and give it an IP of the LAN. So all ports are the default one. This thing it's not possible on Synology. There I basically used the same configuration for the AD Sync but I receive ad authentication error.

A littlme more documentation and logs would be great to understand where is the problem.

Again, maybe an updated docker version could fix all these bugs.

Thanks!

**Comment by burghy86** [comment]
ok. with a sibber we have resolve with a workaround.
little guide for synology:
create a docker with name multiotp
set  volume folder
volume1/docker/multiotp    /temp
power on docker

connect to ssh
sudo -i
password
docker exec -it multiotp /bin/sh
sudo -i
cp -r /etc/multiotp /temp

poweroff docker

edit  volume folder in
volume1/docker/multiotp    /etc/multiotp

power on docker
now image work and is possible to backup and edit setting

for config multiotp
ssh
sudo -i
password
docker exec -it multiotp /bin/sh
sudo -i

and use a manual to config.

**Comment by multiOTP** [comment]
Hello,
Thanks for the feedback. A new docker file will be provided, after several tests under :
* Windows 10 on a "out-of-the-box" distribution
* Synology docker
Regards,

**Comment by burghy86** [comment]
top. grazie mille

**Comment by burghy86** [comment]
can't wait to try the new docker 5.8.7.0 image with synology enhancements

**Comment by multiOTP** [comment]
Hello,
The last 5.8.8.4 version is now working smoothly with Synology and docker.
Please define unused ports to map ports 80 and 443 (for example 44480 and 44443), and prefer using port 44443 (ssl) for multiTOTP configuration.
VOLUME mapping is described in the readme file.
Regards,
