### ISSUE TITLE
disable shoutdown command in otp request

### ISSUE THREAD

**Issue by burghy86** [multiOTP/multiotp#118]
in windows 10 and 11 have a bug
in login screen when request a otp code there are a possibility to shoutdown/reboot/sleep a remote pc.

how to disable a this bug?
https://i.imgur.com/biDXxQ6.jpg

**Comment by multiOTP** [comment]
Hello,
could it be linked to that : https://www.protosoft.com/tricksheet/remove-shutdown-restart-from-rdp-users-options/
Best regards

**Comment by multiOTP** [comment]
No further solution for this issue, but if the "attacker" already have your admin username and your password, and access to your network, he will probably be able to launch a remote shutdown !

We close the case in this forum, as the question is related to multiOTP Credential Provider, and not to multiOTP (the server).

Regards,
