### ISSUE TITLE
email recovery

### ISSUE THREAD

**Issue by burghy86** [multiOTP/multiotp#119]
i. i see a wishlist with
Email account recovery

i see a smtp parameter on ini file and when create new user i can insert a email
goal is coming?
Will this feacture also be available on the windows client? 

great job and thank you

**Comment by multiOTP** [comment]
Hello,

Yes, if you send "email" as the password AND the option is activated (email_code_allowed=1 in the config.ini), you should receive an email.

Please note that the multiOTP open source edition use the regular mail() function of PHP. Therefore, the mail stack of PHP must be configured.

For the Windows client (aka multiOTP Credential Provider), the buttton "Send SMS" is already implemented, but we will add the button "Send Email" in a next release.

Regards,


_(we close this issue as the send email is already implemented in multiOTP)_

**Comment by multiOTP** [comment]
Send email has been implemented in the Credential provider also.
