### ISSUE TITLE
Change time zone.

### ISSUE THREAD

**Issue by mansoorkpa** [multiOTP/multiotp#12]
My current time zone is set to timezone=Europe/Zurich. How can i set to malaysian time zone? Where can i find the list of time zone strings?

**Comment by multiOTP** [comment]
Hello, on which distribution and which plateform are you working ?

**Comment by multiOTP** [comment]
Are you talking about the Virtual Appliance (OVA image), or the Raspberry image ?

**Comment by mansoorkpa** [comment]
In **linux** distribution, build : **4.3.2.6.**

in file **linux\config\multiotp.ini**, property name **timezone=Europe/Zurich**

**Comment by multiOTP** [comment]
You have to use the value of Linux, which is **Asia/Kuala_Lumpur**
If you want to set the timezone of your Linux distribution, please follow one of the tutorial available on the web, like this one: http://unix.stackexchange.com/questions/110522/timezone-setting-in-linux

**Comment by multiOTP** [comment]
(or **Asia/Kuching**, sorry)
