### ISSUE TITLE
windows logo

### ISSUE THREAD

**Issue by burghy86** [multiOTP/multiotp#120]
i have install a multiOTPCredentialProvider-5.8.5.1 and all works. in a program files i have edited a loginLogo.bmp
i have reboot a pc but a logo no change.

how to config correct logo?

**Comment by multiOTP** [comment]
Hello,
you need to set the following registry key :
HKEY_CLASSES_ROOT\CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\v1_bitmap_path 

The complete path and filename of a bitmap image. This is a customized login image. The image must be a version 3 Windows BMP file with a resolution of 128x128 pixels.

**Comment by burghy86** [comment]
great!! thank you

che correct string are: HKEY_CLASSES_ROOT\CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\v1_bitmap_path

**Comment by iwalke** [comment]
> great!! thank you
> 
> che correct string are: HKEY_CLASSES_ROOT\CLSID{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\v1_bitmap_path

Hi, what version of Windows are you using? The registry path you mentioned does not exist in my version of Windows.
![image](https://github.com/user-attachments/assets/e4643f72-3e3a-4dff-8b5f-a1534eff1b17)
