### ISSUE TITLE
MultiOTP with MS Sql

### ISSUE THREAD

**Issue by Ajalsi** [multiOTP/multiotp#122]
Dear 

I want to use MS sql as backend storage. Can you please help me where I can start to do it.

BR.

**Comment by multiOTP** [comment]
Hello,

Additional database support must be adapted in the following methods of the multiOTP in multiotp.class.php (search 'mysql' in the source code) :
* WriteData
* ReadCacheData
* ReadConfigData
* ReadStatData
* WriteLog
* ShowLog
* ClearLog
* InitializeBackend
* Create a new method MSSQLAddRowIfNeeded

Regards,
