### ISSUE TITLE
PHP version support

### ISSUE THREAD

**Issue by AussieMakerGeek** [multiOTP/multiotp#123]
Hi, I see that MultiOTP is currently using PHP 7.3 which has been announced as unsupported.

This also goes for the Credential provider which is packaged with php.exe and is being flagged by windows defender as having multiple vulnerabilites.

Are there any plans to bring it up to 7.4 or 8(.1)? Will it work with newer versions?

**Comment by isfufula** [comment]
+1

**Comment by multiOTP** [comment]
Hello,
The last version of source code works on PHP version 7.4. You can replace the php.exe with the version 7.4

The next package will be released with PHP 7.4 directly.

Best regards

**Comment by multiOTP** [comment]
Hello,
Full PHP 7.4 support with version 5.8.7.0 has been released (and should work with PHP 8(.1) too).
multiOTP Credential Provider 5.8.7.0 is also updated with PHP 7.4 stuff. The MSI installer can be downloaded here : https://download.multiotp.net/credential-provider
Regards,

**Comment by multiOTP** [comment]
Hello,

Version 5.8.7.1 of the multiOTP Credential Provider includes the last PHP 8.1 version (8.1.5).

Binary download: https://download.multiotp.net/credential-provider/

Regards,
