### ISSUE TITLE
issue on server 2022

### ISSUE THREAD

**Issue by killmasta93** [multiOTP/multiotp#124]
Hi currently using version 5.8.2.9 trying to install using these commands running server 2022, also tried on server 202r2 same issue 
`
multiotp -config default-request-prefix-pin=0
`
but im getting VCRUNTIME140.DLL not found

Thank you

**Comment by killmasta93** [comment]
i added the DLL inside and started to working but now when i try to put in the user it keeps showing user does not exist

![image](https://user-images.githubusercontent.com/13953629/167282549-a384c14c-2423-4efe-8c32-7e67c181387c.png)

![image](https://user-images.githubusercontent.com/13953629/167282556-4eda3b6c-c559-4d46-a81b-3fec59640f17.png)

**Comment by multiOTP** [comment]
Hello,
This seems to be a multiOTP Credential Provider error.
Please upgrade to the last version of multiOTP Credential Provider (currently https://github.com/multiOTP/multiOTPCredentialProvider/releases/tag/5.8.8.0)
Regards,
If there is still an issue, please open an issue in the [multiOTPCredentialProvider ](https://github.com/multiOTP/multiOTPCredentialProvider/issues) repository

**Comment by killmasta93** [comment]
Thank you so much that did the trick, quick question, it works when authenticating when the computer has network but when i disconnect from network it does not work the 2fa , when i installed the client i check marked enable cache support 
or is there a way when the user does not have internet they can use a temporal password that only let them use once?
Thank you

**Comment by multiOTP** [comment]
Hello,
Whats is written in the log file in C:\Program Files\multiOTP\log\multiotp.log when you try to log in when you are online and offline ?

Best regards

**Comment by multiOTP** [comment]
Hello,
Last version (5.9.0.3) supports offline authentication.
Regards,
