### ISSUE TITLE
2FA offline?

### ISSUE THREAD

**Issue by farzadha2** [multiOTP/multiotp#126]
Hi @multiOTP 
Wanted to say thank you for the amazing software, currently was wondering if i configured correctly because it seems that the 2fa offline does not work or maybe i missed some step?

on the server i have this config

![image](https://user-images.githubusercontent.com/62571297/167675524-440161f6-4838-4843-90da-d8cdd12cb021.png)

and on the windows client when i installed using 5.8.8.0 
using authentication mode mandatory and enable cache support 

![Screenshot at 12-20-37](https://user-images.githubusercontent.com/62571297/167676532-a5590440-ad3d-469e-b456-e5d950cdc48c.png)

but could not find the 10 emergency one time password usage setting?

which i was reading was released in the version 4.0

Thank you

**Comment by killmasta93** [comment]
hi there so i was able to configure the scratch code 

`multiotp.exe -scratchlist testuser`

but only seems to work if the user has internet not sure why offline not working

**Comment by multiOTP** [comment]
Hello,
This is a multiOTP Credential Provider issue (https://github.com/multiOTP/multiOTPCredentialProvider). Did you install the last version of multiOTP Credential Provider (**5.8.8.0** or greater) ?
_2022-05-06 5.8.8.0 FIX: Second factor authentication failed if no domain controller is reachable_

**Comment by multiOTP** [comment]
Whats is written in the log file in C:\Program Files\multiOTP\log\multiotp.log when you try to log in when you are offline ?

**Comment by farzadha2** [comment]
thank you so much for the reply, 
currently using the 5.8.8.0 and the log section 
![image](https://user-images.githubusercontent.com/62571297/167997908-ec10e9bb-e5ff-420f-9161-db0073d1014e.png)

my question is would i run this command on the server or on the users computer?

`multiotp.exe -scratchlist casa`

Thank you again
the first line of the log the computer has internet
then the rest of lines the computer does not have internet and was trying to use the scratchlist running the command on the server and the last line the computer has internet again to put the 2fa of the google app 
```

2022-05-12 07:16:12	notice	casa	User	Info: User casa successfully logged in (using Credential Provider) using an external server	0	WINDOWS10-PC
2022-05-12 07:17:36	debug		Client-Server	Warning: Host 192.168.3.86 on port 8112 not reached before a timeout of 5 seconds.	0	WINDOWS10-PC
2022-05-12 07:17:36	warning		System	Error: database file C:\Program Files (x86)\multiOTP\.\users\ser.db for user ser does not exist	0	WINDOWS10-PC
2022-05-12 07:17:36	debug		Client-Server	Info: temporary skipping http://192.168.3.86:8112 due to previous timeout or inconsistent response.	0	WINDOWS10-PC
2022-05-12 07:17:42	debug		Client-Server	Warning: Host 192.168.3.86 on port 8112 not reached before a timeout of 5 seconds.	0	WINDOWS10-PC
2022-05-12 07:17:42	warning		System	Error: database file C:\Program Files (x86)\multiOTP\.\users\ser.db for user ser does not exist	0	WINDOWS10-PC
2022-05-12 07:17:42	debug		Client-Server	Info: temporary skipping http://192.168.3.86:8112 due to previous timeout or inconsistent response.	0	WINDOWS10-PC
2022-05-12 07:17:59	notice	casa	User	Info: User casa successfully logged in (using Credential Provider) using an external server	0	WINDOWS10-PC
```

**Comment by farzadha2** [comment]
Thanks again for the reply,  correct im using the multiOTP Credential Provider with a multiOTP server with LDAP i recently created a test environment 
![image](https://user-images.githubusercontent.com/62571297/168130602-e3311b77-f307-47d7-8b1c-33c1d32caac4.png)

when i login windows it shows

![image](https://user-images.githubusercontent.com/62571297/168130737-988cdfa0-1205-4963-8c58-0c61bfdd2f1c.png)

after few hours of trying, it seems that i needed to run the multiotp.exe on the client for it to sync the offline codes 
now it working wonderful thank you so much 

also wanted to ask quick question, logging in as administrator local it seems not to be an option? without the 2fa?

thank you again

**Comment by multiOTP** [comment]
Hello, you can use the following registry key to choose a single user that can log on without 2FA.

HKEY_CLASSES_ROOT\CLSID{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\excluded_account

Specify an account that should be excluded from 2FA. The format is required to be domain\username or computername\username.

Best regards

**Comment by farzadha2** [comment]
hi @multiOTP thank you so much for the reply,
i was looking at the client of the computer though the regedit but does not show CLSID
![image](https://user-images.githubusercontent.com/62571297/168453305-de4ab0ed-1c70-4502-8973-8e47af5f2055.png)
