### ISSUE TITLE
Error when restarting docker container

### ISSUE THREAD

**Issue by MBPotier** [multiOTP/multiotp#127]
When restarting the docker container, I get the following error and multiOTP does not start.

```
mkdir: cannot create directory '/run/php': File exists
```

I replaced the following block in /multiotp/raspberry/boot-part/newvm.sh

```
  if [ -e /etc/init.d/${PHPFPM} ] ; then
    /etc/init.d/${PHPFPM} start
  else
    service ${PHPFPM} start
  fi
```

with

```
  if [ -e /etc/init.d/${PHPFPM} ] ; then
    if [ -e /run/php ] ; then
      /etc/init.d/${PHPFPM} restart
    else
      /etc/init.d/${PHPFPM} start
    fi
  else
    if [ -e /run/php ] ; then
      service ${PHPFPM} restart
    else
      service ${PHPFPM} start
    fi
  fi
```

After this change I built the container, and it can now be started and restarted. However, I get the feeling that this is just a workaround and something is not shutting down cleanly when the container is restarted.

**Comment by multiOTP** [comment]
Thanks for the feedback.
We will investigate further and providing at least the patch you propose, or a better fix, for the next public release.
Regards

**Comment by multiOTP** [comment]
Version 5.9.0.3 includes the patch.
