### ISSUE TITLE
MULTIOTP_PATH working in kubernetes?

### ISSUE THREAD

**Issue by heket87** [multiOTP/multiotp#128]
Hi! I setup multiotp in kubernetes. I want to change default URL PATH. I set          
env:
        - name: MULTIOTP_PATH
          value: "https://x.x.x.x/multiotp"
I can reach https://x.x.x.x/multiotp, but buttons not working. If i use NodePort with port number 30162 instead of Ingress-controller,  with url https://x.x.x.x:30162/multiotp result is the same. But if i go on x.x.x.x:30162/ it's working! Can you help me, please?

**Comment by multiOTP** [comment]
Hello,
MULTIOTP_PATH is an environment variable that can be use to define the full path of the root folder of multiOTP in a directory structure. It has nothing to do with an URL !
Regards,
