### ISSUE TITLE
How to send sms when logging in?

### ISSUE THREAD

**Issue by mikhailfedotov** [multiOTP/multiotp#13]
Authentification by Google Authentificator is work.
I made changes in config for aspsms. 
I can send sms by this script: multiotp @username@ sms. I receive it.

But what should I do to get code by sms when I'm logging in?

**Comment by multiOTP** [comment]
When you want to receive an SMS when you log in, type first "sms" as the password. It will refuse the login, but it will send an sms.
Regards,

**Comment by mikhailfedotov** [comment]
Is there a way to make it not so complicated for user?
I mean user will need to enter login\password for login by  RDP client
then he will need to enter login\password and "sms". After that he will need again to enter login\password for login by  RDP client and then he will need to enter login\password\received_code

Thats a pretty complicated for user.
Maybe you have another way to do it?

**Comment by multiOTP** [comment]
The credential provider could propose an extra button to send an sms, but it's currently not implemented.

**Comment by mikhailfedotov** [comment]
When do you plan to implement this button?
Maybe you have another way to do it? Another credentian provider, or RDP-client option to say server that we use sms? or maybe change config or code to use only sms?

**Comment by mikhailfedotov** [comment]
Maybe if we parse Windows eventlog and see that user was connected we can send an sms using script?

**Comment by multiOTP** [comment]
Eventlog will be trigged when the user try to log, which is too late.
An idea could be to add a "Send SMS button" next to the user name folder of the Credential Provider.

**Comment by multiOTP** [comment]
Adding "Send SMS button" next to the user name folder of the Credential Provider has been added in the roadmap of the Credential Provider.
