### ISSUE TITLE
How to support IPV6

### ISSUE THREAD

**Issue by xue-DC182** [multiOTP/multiotp#131]
when I use IPV6 send to freeradius-server I got my success result
![QQ截图1](https://user-images.githubusercontent.com/27612558/175450515-21cc843f-79df-45b3-b6ab-cde6fb513cc1.jpg)
but I send to multiOTP I got this error

![QQ截图2](https://user-images.githubusercontent.com/27612558/175451295-68141819-c375-40f5-af68-ecbe67b6820d.jpg)
![QQ截图3](https://user-images.githubusercontent.com/27612558/175451304-caa57eec-0a95-454f-bc5c-fa4be72e7145.jpg)

**Comment by xue-DC182** [comment]
I added this text to the freeradius/config/3.0/users and annotated the information about multiOTP in the freeradius/config/3.0/sites-enabled/default,finally I reached my goal, but I don't know if there are hidden dangers
![image](https://user-images.githubusercontent.com/27612558/176141580-452d276c-2183-4afb-af1f-be8f02f1226b.png)

**Comment by multiOTP** [comment]
Hello,
regarding security, we think there is no issues with the proposed settings.

Best regards

**Comment by xue-DC182** [comment]
That would be great, but it would be better to add about IPv6 instructions to README
