### ISSUE TITLE
multiotp how to sync user from opendj

### ISSUE THREAD

**Issue by junhou-he** [multiOTP/multiotp#132]
Hi,
I need to synchronize users from opendj to multiotp, but opendj is not a standard ldap, there is no objectclass, how can I set it?

thanks，
Junhou

**Comment by multiOTP** [comment]
Hello,

OpenDJ do have object class, see here :

![image](https://user-images.githubusercontent.com/9338189/178268077-3b956584-eee4-4ef8-815d-74d0a6178e18.png)

We don't understand your issue. Set the LDAP server type as "standard LDAP" (2) and it should be ok.

Regards,

**Comment by multiOTP** [comment]
Hello @junhou-he, any feedback ?
Regards,

**Comment by junhou-he** [comment]
I modified the corresponding properties in the configuration file, thank you
