### ISSUE TITLE
RDGW with 2fa multiotp

### ISSUE THREAD

**Issue by mastaslam** [multiOTP/multiotp#134]
Hi.
I have a gateway to a windows server 2019. Is it possible to set a 2fa request using multiotp.  Thanks

**Comment by multiOTP** [comment]
Hello,
I would say yes for RDGW , when you install Credential Provider on the final Windows Server 2019.
This is different from using RD Web Access, which will request some configuration like explained here : https://roman.gallauner.at/?p=886
Regards, and keep us in touch !
