### ISSUE TITLE
users request/update

### ISSUE THREAD

**Issue by emper0r** [multiOTP/multiotp#135]
Hi, we installed the docker version of multiotp and works like a charm. but exist the possibility to users read/manage/recreate their own QR in case of lost/delete it OTP code?... because the admin can't must see the QR code of the users by security reasons.

**Comment by multiOTP** [comment]
Hello,
with the open source version this feature is not available.

In the commercial version the provisionning QRCode can be sent automatically by e-mail to any user.

Best regards.
