### ISSUE TITLE
without2fa user will not be cached on client

### ISSUE THREAD

**Issue by yankaiqian** [multiOTP/multiotp#136]
Hi, 
If I create a user using the without2fa option on the server, this user will not be cached on client, when client disconnect the network, the user will still need 2fa.
I am not sure if I configured it correctly, the expected behavior should be user can login without 2fa even if the PC is offline.

server version: multiOTP 5.9.0.3 2022-05-26 (hyper-v vm version)
client version: multiOTPCredentialProvider-5.9.2.1 (Windows 10 21H2)

How to reproduce:
1, On the server, run command to create a user
 `multiotp -create user01 without2FA`
  
2, On the client, when it is connected to network, login with the account user01, no 2FA needed, this is expected behavior. 
Check the folder multiotp\users, found no user01.db file.

3, On the client, disconnect the network, login with the account user01, 2FA is needed now.

**Comment by multiOTP** [comment]
Hello,
thanks for the feedback, we are working on this issue and we are planning to release a new version soon.
Best regards

**Comment by multiOTP** [comment]
Hello,
Version 5.9.3.1 and further allow now caching of without2fa user.
Regards,

**Comment by yankaiqian** [comment]
Off topic.
Thank you for the great job!
I tried to donate using the button, but failed, it says "Donations to this recipient aren't supported in this country", I am from China.

Btw, I also tried to send mail about the donation issue to info@multiotp.net, got the "Undelivered Mail Returned to Sender" reply.

>  <[report-multiotp@sysco.ch](mailto:report-multiotp@sysco.ch)>: host [mx30.zline.ch](http://mx30.zline.ch/)[[212.74.141.25](tel:2127414125)] said: [554 5.7.1](tel:554571)
>    Spam content detected, milter-regex: [194982](tel:194982) 

Just let you know, thank you for your work again.

**Comment by multiOTP** [comment]
> I tried to donate using the button, but failed, it says "Donations to this recipient aren't supported in this country", I am from China.

Hello,
We are sorry for that, it seems to be a PayPal donation limitation. But if you want, you can make a PayPal direct transfert to the account "paypal -at- sysco.ch".
Best regards, and thanks for your support.
