### ISSUE TITLE
Multiotp Freeradius Apache on Windows

### ISSUE THREAD

**Issue by greddy7** [multiOTP/multiotp#138]
Hello, i like this multiotp ... very nice work!

but i am on windows server, the multiotp is fine running under apache ...  the problem is:

is exist no module for windows apache 2.4.x and freeradius and i have no idea how to protect
my webdav-drive with  multiotp and totp (this is my wish),  an ldap i want not use.

any ideas ?

greets, Peter

**Comment by multiOTP** [comment]
Hello,
Perphaps the best option is to setup an HyperV Linux appliance with an Apache reverse proxy installed, and you can mount your webdav-drive through the Apache reverse proxy.
Regards,

**Comment by multiOTP** [comment]
Other idea : try to use https://github.com/phokz/mod-auth-external to launch php (and use multiOTP) to check the authentication
