### ISSUE TITLE
Enterprise version

### ISSUE THREAD

**Issue by c-le** [multiOTP/multiotp#139]
Hello,

I just bought an Enterprise version, and get the key, and what next now ?
I can't found an howto or where to put the key.

Thanks.

**Comment by multiOTP** [comment]
Hello,
Appliances can be donwloaded here (one free licence is already included) : 
Hyper-V appliance : http://firmware.multiotp.com/enterprise/hyper-v/
OVA appliance : http://firmware.multiotp.com/enterprise/vmware/
A quick start guide is available here : https://download.multiotp.com/multiOTP_Pro_and_Enterprise_Quick_Start.pdf
For further support about commercial edition, please contact us directly at support@multiotp.com
Regards,

**Comment by c-le** [comment]
I can't upgrade my open source version ?

**Comment by multiOTP** [comment]
Hello,
The commercial edition is slightly different with a lot of additional capabilities.
Using the open source interface, you can backup the configuration (using a password), and you can apply the configuration file to your commercial edition.
For further support about commercial edition, please contact us directly at support@multiotp.com
Regards,
