### ISSUE TITLE
Linux SSH client

### ISSUE THREAD

**Issue by bohemtucsok** [multiOTP/multiotp#140]
Hello

The program works perfectly from Windows, but I would like to use it to identify ssh access from Linux, is there a solution for this?

**Comment by multiOTP** [comment]
Hello,
here you find some information to setup multiOTP for SSH access :
https://research.kudelskisecurity.com/2014/01/20/openssh-hardening-for-cloud-machine-two-factor-authentication-part-2/

Best regards
