### ISSUE TITLE
Bug : when set the password & otp in one step, a display bug exists

### ISSUE THREAD

**Issue by ljhmily** [multiOTP/multiotp#142]
when set the password & otp in one step，the bugs exists，like this
the four hits always exists，and the reg modify is invalid，otherwise its need to change to otp in two step，then it will be disappear
![image](https://user-images.githubusercontent.com/20486958/195230790-f55e958c-a101-4920-8213-3b6c14cd53de.png)

another question，how to disable multiotp change my default logo

**Comment by multiOTP** [comment]
Hello,
thanks for your feedback.
We will have a look at that in the next few weeks.
Best regards

**Comment by multiOTP** [comment]
Furthermore, please note that as the multiOTP Credential Provider is another Credential Provider, the default logo of Microsoft Credential Provider is not handled.
Regards,

**Comment by multiOTP** [comment]
The "one step display bug" has been corrected internally and will be published later this month.
Regards,

**Comment by multiOTP** [comment]
This multiOTP Credential Provider issue has been corrected in the release 5.9.4.0 : https://github.com/multiOTP/multiOTPCredentialProvider/releases/tag/5.9.4.0
Regards,

**Comment by ljhmily** [comment]
> This multiOTP Credential Provider issue has been corrected in the release 5.9.4.0 : https://github.com/multiOTP/multiOTPCredentialProvider/releases/tag/5.9.4.0 Regards,

got，try it next week.
