### ISSUE TITLE
Bug: Non authenticated users can download files because MultiOTP Ngnix webroot isn't blocking files

### ISSUE THREAD

**Issue by lollett** [multiOTP/multiotp#145]
Non authenticated users can download any file from the MultiOTP Ngnix webroot.
Tested and confirmed on Windows version 5.9.4.0

Example:
http://[multiotp IP:PORT]/config/multiotp.ini
http://[multiotp IP:PORT]/log/multiotp.log
http://[multiotp IP:PORT]/users/[username].db
http://[multiotp IP:PORT]/tokens/[token].db

Suggested workaround - add blocked folders to Ngnix configuration:
C:\multiotp\windows\webservice\conf\sites-enabled\multiotp.conf

	location ~ /(config|log|users|tokens|devices|groups|radius|webservice) {
		deny all;
		return 404;
	}

**Comment by multiOTP** [comment]
Hello Lollett,
Thanks for your feedback about the Windows nginx configuration.
Subfolder access has been modified in [release 5.9.5.1 and further](https://github.com/multiOTP/multiotp/releases/latest).
Regards,
