### ISSUE TITLE
Feature request - Without2FA and AD sync

### ISSUE THREAD

**Issue by jortiexx** [multiOTP/multiotp#147]
Hi!

I setup multiotp with AD sync to protect a RDS server. Used these steps: http://woshub.com/enable-2fa-in-windows-with-multiotp/
multiotp -config ldap-in-group=”MFA”
Accounts that are member of the MFA group are getting synced and they work perfectly with a OTP. However for some account I want them to use only a username and password. These users are not part of the MFA group.

The issue now is that those users also get presented with a enter OTP code textfield during login. MultiOTP cant find these users as they are excluded from sync. 

I configured the credential provider with multiOTPWithout2FA  = 1

Any thoughts?

**Comment by multiOTP** [comment]
Hello,
users without 2FA must exist in multiOTP with a token Without2FA. You can either add them in the MFA group and change their token type or create them by hand in multiOTP and assign them a without2FA token.

Best regards

**Comment by jortiexx** [comment]
Thanks for your input!

Is there a way to configure multiOTP to sync all users in AD, but assign only the without2fa token to users not in the MFA group?

Op 8 nov. 2022 om 09:05 heeft multiOTP ***@***.***> het volgende geschreven:

﻿

Hello,
users without 2FA must exist in multiOTP with a token Without2FA. You can either add them in the MFA group and change their token type or create them by hand in multiOTP and assign them a without2FA token.

Best regards

**Comment by multiOTP** [comment]
Hello,
`multiotp -config ldap-without2fa-in-group=”without2fa”`
is now implemented in [release 5.9.5.0 and further](https://github.com/multiOTP/multiotp/releases/latest).
Please check and thanks in advance for the feedback
Regards,
