### ISSUE TITLE
Cannot Run webservice_install.cmd from C:\Program Files (x86)\multiOTP 

### ISSUE THREAD

**Issue by mattburris** [multiOTP/multiotp#150]
On Windows when you have extracted MultiOTP to "C:\Program Files (x86)\multiOTP\" and attempt to run webservice_install.cmd (as admin) you get the following error:
\multiOTP\ was unexpected at this time.

On Windows the credential Provider installs into C:\Program Files (x86)\multiOTP\ so it makes it impossible to configure multiOTP from the web interface because the webservice cannot be installed from that folder.

The credential provider used to allow you to choose the installation folder, but it does not give that option any longer.  

I think the webservice_install.cmd needs to be modified so that it can run correctly from the default installation location of the credential provider ("C:\Program Files (x86)\multiOTP\")

**Comment by multiOTP** [comment]
Hello Matt,

multiOTP open source should be run on a separate virtual appliance or on a docker.  The Windows version is more like a "demonstrator", and it use an outdated version of FreeRADIUS for Windows.

- Install multiOTP open source as a virtual machine (under VMware or Hyper-V)
- Install multiOTP Credential Provider on your computers

If you want to use multiOTP Credential Provider on one computer only (without an extra server), you only need to install it alone on your computer, and you can create the user with command line commands.

Regards,
