### ISSUE TITLE
admin password didn't change

### ISSUE THREAD

**Issue by emper0r** [multiOTP/multiotp#152]
Hi i'm getting error to change the admin password, never changed after first time from 1234, if i want to change again don't works

i'm using 5.9.0.3 and then updated to 5.9.3.1 from latest dockerhub version but still same error..

in other case. if I want to generate the hash not using the web how can i do to objtained the same format hash ??

thanks

**Comment by emper0r** [comment]
nevermind.. some reason now works fine. in fact was weird maybe was permissions file sorry about it

**Comment by multiOTP** [comment]
No problem, regards
