### ISSUE TITLE
PHP 8.x Support

### ISSUE THREAD

**Issue by joeyberkovitz** [multiOTP/multiotp#153]
Per #123, PHP 8.1 should be supported, although using PHP 8.1.13 triggers at least one deprecation warning:
`Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/multiotp.server.php on line 22135`

PHP 8.2 triggers many more warnings

**Comment by multiOTP** [comment]
Hello joeyberkovitz,
PHP 8.1 is supported (and currently it works with warnings, you are right). We have planned to adapt/remove the PHP 8.1 deprecated implementation for the next release in a few weeks.
Regards,

**Comment by joeyberkovitz** [comment]
thanks for the info

**Comment by multiOTP** [comment]
Hello,
The last release [5.9.5.5](https://github.com/multiOTP/multiotp/releases/tag/5.9.5.5) is now fully compatbile with PHP 8.x
Regards,
