### ISSUE TITLE
When I delete a user on the web, it cannot be synced back from LDAP

### ISSUE THREAD

**Issue by xiaominzhang1987** [multiOTP/multiotp#154]
When I delete a user on the Web GUI, it cannot be synced back from LDAP

**Comment by multiOTP** [comment]
Hello,
can you please tell us which product version you are using ?
Best regards.

**Comment by xiaominzhang1987** [comment]
multiOTP 5.6.1.5 2019-10-23

**Comment by multiOTP** [comment]
can you please update to the latest build and check if the problem is still there.

**Comment by multiOTP** [comment]
Any feedback about this issue:
Be aware that there is no automatic scheduler to launch the -syncldap option (you will have to schedule it by yourself)
Regards,

**Comment by multiOTP** [comment]
Not reproductible using the current version, and no feedback since 3 weeks.
