### ISSUE TITLE
Active Directory Sync and NTP  issues

### ISSUE THREAD

**Issue by saraiva82** [multiOTP/multiotp#16]
I am running MultiOTP on Windows Server 2008 R2 and I believe I can communicate with my AD fine my problem is that when I run >multiotp -debug -display-log -ldap-users-sync
I get a never ending array that I pasted below. I ran this for 3 days and i was still getting new entries. Also I noticed that on the web UI the time is and I habe my NTP  correct as well as time sone America/New_York on the config .INI I am wondering if this is the issue. 

LOG 2017-03-02 17:12:15 debug LDAP Debug: *AD/LDAP synchronization started at 17
:11:15, LDAP account #629665 at 17:12:15 / Memory used: 7.3MB / Peak: 20.4MB
Array
(
    [count] => 1
    [distinguishedname] => Array
        (
            [0] =>
            [count] => 1
        )

)

LOG 2017-03-02 17:13:15 debug LDAP Debug: *AD/LDAP synchronization started at 17
:11:15, LDAP account #1262324 at 17:13:15 / Memory used: 7.3MB / Peak: 20.4MB
Array
(
    [count] => 1
    [distinguishedname] => Array
        (
            [0] =>
            [count] => 1
        )

)

LOG 2017-03-02 17:14:15 debug LDAP Debug: *AD/LDAP synchronization started at 17
:11:15, LDAP account #1900317 at 17:14:15 / Memory used: 7.3MB / Peak: 20.4MB
Array
(
    [count] => 1
    [distinguishedname] => Array
        (

**Comment by multiOTP** [comment]
Hello, 5.0.4.6 is available here currently : http://download.multiotp.net/
Have a look and keep us in touch
Regards,
Andre

**Comment by multiOTP** [comment]
Any feedback ?
