### ISSUE TITLE
Cannot sign into Website

### ISSUE THREAD

**Issue by elmidwill** [multiOTP/multiotp#160]
Hello Everyone,

I have tried both Nginx and Apache, php8.1 FPM installed as well. The website loads but whenever I go to enter the default credentials nothing happens. The password fields goes blank yet I cannot login.

**Comment by multiOTP** [comment]
Hello,
Please enable the PHP log file (error_log=...) and set the error level to all (error_reporting=ALL)
What is written into the PHP log file ?
Regards,

**Comment by elmidwill** [comment]
I have enabled PHP logging but nothing appears there. Is as it its not even getting that far. Once I enter the default user name and password, the password goes away and nothing proceeds beyond that. 

This is what I see on my login screen

multiOTP web administration console
the open source strong authentication library
multiOTP 5.9.5.5 2023-01-19
Web service is ready 2023-03-10 02:09:53, Apache/2.4.52 (Ubuntu), PHP/8.1.2-1ubuntu2.11

I have installed php, php8.1-bcmath, php8.1-mbstring, php8.1-gd and php8.1-fpm.

The install folder looks like:

-rw-r--r-- 1 www-data www-data  113283 Mar  7 20:37 README.md
-rw-r--r-- 1 www-data www-data    5057 Mar  7 20:37 Dockerfile
-rw-r--r-- 1 www-data www-data    7639 Mar  7 20:37 COPYING.LESSER
-rw-r--r-- 1 www-data www-data   35147 Mar  7 20:37 COPYING
-rw-r--r-- 1 www-data www-data      29 Mar  7 20:37 _config.yml
-rw-r--r-- 1 www-data www-data    3214 Mar  7 20:37 CODE_OF_CONDUCT.md
-rw-r--r-- 1 www-data www-data   36641 Mar  7 20:37 checkmultiotp.cmd
-rw-r--r-- 1 www-data www-data   70454 Mar  7 20:37 check.multiotp.class.php
-rw-r--r-- 1 www-data www-data    6086 Mar  7 20:37 md5.js
drwxr-xr-x 2 www-data www-data    4096 Mar  7 20:37 launcher
drwxr-xr-x 2 www-data www-data    4096 Mar  7 20:37 docs
drwxr-xr-x 2 www-data www-data    4096 Mar  7 20:37 contrib
-rw-r--r-- 1 www-data www-data    6779 Mar  7 20:37 multiotp.cli.proxy.php
-rw-r--r-- 1 www-data www-data  138640 Mar  7 20:37 multiotp.cli.header.php
-rw-r--r-- 1 www-data www-data  998428 Mar  7 20:37 multiotp.class.php
-rw-r--r-- 1 www-data www-data    2989 Mar  7 20:37 radius_uninstall.cmd
-rw-r--r-- 1 www-data www-data    8709 Mar  7 20:37 radius_install.cmd
-rw-r--r-- 1 www-data www-data    6017 Mar  7 20:37 radius_debug.cmd
drwxr-xr-x 2 www-data www-data    4096 Mar  7 20:37 oath
-rw-r--r-- 1 www-data www-data    5877 Mar  7 20:37 multiotp.wsdl
-rw-r--r-- 1 www-data www-data   79241 Mar  7 20:37 multiotp.server.php
-rwxr-xr-x 1 www-data www-data 3045859 Mar  7 20:37 multiotp.php
-rw-r--r-- 1 www-data www-data    3118 Mar  7 20:37 webservice_uninstall.cmd
-rw-r--r-- 1 www-data www-data    9570 Mar  7 20:37 webservice_install.cmd
-rw-r--r-- 1 www-data www-data     225 Mar  7 20:37 test-tokens.csv
drwxr-xr-x 2 www-data www-data    4096 Mar  7 20:37 templates
drwxr-xr-x 2 www-data www-data    4096 Mar  7 20:37 scripts
drwxr-xr-x 3 www-data www-data    4096 Mar  7 20:37 raspberry

**Comment by multiOTP** [comment]
Hello,
Did you check the error log of Apache ?
Regards,

**Comment by multiOTP** [comment]
Used PHP extensions:
extension=php_gd.dll
extension=php_gmp.dll
extension=php_ldap.dll
extension=php_mbstring.dll
extension=php_mysqli.dll
extension=php_openssl.dll
extension=php_pgsql.dll
extension=php_sockets.dll

**Comment by elmidwill** [comment]
I am using Linux. All those extensions except pgsql is installed and I installed the pgsql. 

Nothing shows up in the php_error logs.

Besides attaching it to a web server, do I need to setup ms sql or anything other than Apache?

**Comment by multiOTP** [comment]
Hello,
The first time, the system need to create some subfolders, and also a file for each user and each token.
Be sure that www-data can create folders in your root www folder.
Regards,

**Comment by elmidwill** [comment]
Any suggestions on what might be causing this error:

`[Wed Mar 15 00:42:44.330608 2023] [php:error] [pid 8391] [client 192.168.2.111:13521] PHP Fatal error:  Uncaught Error: Call to undefined function mb_strpos() in /var/www/html/linux/multiotp.server.php:74039\nStack trace:\n#0 {main}\n  thrown in /var/www/html/linux/multiotp.server.php on line 74039`

**Comment by multiOTP** [comment]
Hello,
Sure, mbstring extension is missing in PHP.
Regards,
