### ISSUE TITLE
How to build multiotp.exe?

### ISSUE THREAD

**Issue by stevenChuCP** [multiOTP/multiotp#161]
Hi,

I'd like to build my own `multiotp.exe`.
It is said to be in the `launcher` directory, and I found a `launcher.cpp` file indeed.
However, I couldn't find the solution file to build the program.

How can I build `multiotp.exe`?

Thanks!

**Comment by multiOTP** [comment]
Hello Steven,
It's just a simple C++ stub that launch PHP with the passed parameters. 
Create an empty C++ console project in VIsualStudio and you should be able to compliel it easily.
Regards,
