### ISSUE TITLE
Queries regarding HOTP (hardware tokens based) and PKI smart card login ?

### ISSUE THREAD

**Issue by ashishsabu** [multiOTP/multiotp#167]
According to the information provided in the README https://github.com/multiOTP/multiotp/wiki   
HOTP (hardware tokens based) integration is possible with multiOTP and following hardware tokens are supported ->  OTP c200, Gemalto Ezio Token, Seamoon KingKey, YubiKeys from Yubico.

I have some queries regarding HOTP on windows system, could you please help me with this ?
      1. How to integrate supported HOTP hardware tokens with multiOTP/multiOTP Credential Provider ? is there any document available for this ?
      2. Is it possible to implement “PKI smart card-based login” with multiOTP ?
      3. Is it possible to use both HOTP(HW token based) and TOTP solutions at the same on one system ? and to choose the authentication mechanism during the windows login process, with authentication happening based on selected options ?
      4. Is it possible to integrate a HOTP solution with an active directory ?

**Comment by multiOTP** [comment]
Hello,
could you please tell us what scenario you are working on ? I mean do you have a dedicated multiOTP server or did you install the credential provider by itself on a computer ?

1. If you are not using a dedicated server (standalone CredentialProvider withtou multiOTP server), you need to
  a. Import the HOTP token in multiOTP
  b. Create a user
  c. link a token with a user

  If you are using a dedicated server, you need to create the user and the token on this server.
  If you are using multiOTP PRO/Enterprise appliance as dedicated server you can create the user and the token using the web interface
   Here are some useful command lines
```
multiotp -fastcreatenopin user (create a user without a prefix PIN)
multiotp -import tokens_definition_file [key|pass|key_file] (import the tokens from a csv file for example)
multiotp -assign-token user token-id (assign a token to a user. The token id is the file name of the token without the extension. The token files are stored in the folder tokens)
```
2. No it's not possible to use “PKI smart card-based login” with multiOTP. If you want to user “PKI smart card-based login” simply use the default Windows credential provider.

3. No it's not possible to have multiple tokens per user. Do you have a use case where it could be necessary ?

4. If you have a multiOTP dedicated server then you can sync it with Active Directory. During the sync process it creates all the users. You can choose which AD group you want to sync.

I hope you find the answers to your questions. Do not hesitate to contact us if you need additional information.

Best regards

**Comment by ashishsabu** [comment]
Hello Team,

Thank you team. I appreciate the new information.

I have some questions regarding point 1.
" a. Import the HOTP token in multiOTP
  b. Create a user
  c. link a token with a user"

1. I have questions abouts using one HOTP token for multiple user accounts
on a single system. Is it possible to link a single token with multiple
accounts on a single system ?
eg - I have 3 user-accounts on single systems,  is it possible to use a
single HOTP token to authenticate all of these accounts ?

2. Can I authenticate different user accounts on different systems using
the same HOTP token ?
eg.- I have 5 systems with 3 user accounts on each system. Is it possible
to use a single HOTP token for all users on different systems ?

Thank you.

Regards,
Ashish Sabu

**Comment by multiOTP** [comment]
Hello,
1. yes you can link a token to multiple users.
2. In general it's not possible to have the same HOTP token on different system because HOTP is a per event based token.
It works if you use TOTP token which are time based token

Best regards

**Comment by ashishsabu** [comment]
Thank you team for the details. 
Closing the issue for now.
