### ISSUE TITLE
Multitotp behind a reverse proxy 

### ISSUE THREAD

**Issue by cbaptista** [multiOTP/multiotp#168]
Hi all,

I have an instance of multitotp running on my internal network without problems.
I need to put the multitotp behind a reverse proxy for external access.
In addition to the 80/443 web ports, are any more needed?
For reverse proxy I use pound, but I can't get the windows credential provider to work.
I can access the web interface without problems.

windows client logs:

php multiotp.windows.php -debug -display-log USERXX TOKENXXX -server-timeout=10 -server-cache-level=0 -server-url=https://xxxxxxx.xxxxxxx.xx -server-secret=SECRETXXX
PHP Warning:  fgets(): SSL: Uma ligação existente foi forçada a fechar pelo anfitrião remoto in C:\Program Files (x86)\multiOTP\php\multiotp.windows.php on line 21440

LOG 2023-06-05 22:40:11 debug Client-Server Info: temporary adding https://xxxxxxx.xxxxxxx.xx to the list of banned servers, content not recognized (...)

LOG 2023-06-05 22:40:11 debug Client-Server Error: *Host sent an incorrect answer:

LOG 2023-06-05 22:40:11 debug Client-Server Info: temporary skipping https://xxxxxxx.xxxxxxx.xx due to previous timeout or inconsistent response.

LOG 2023-06-05 22:40:11 debug Client-Server Error: *Host sent an incorrect answer:

LOG 2023-06-05 22:40:11 warning System Error: database file C:\Program Files (x86)\multiOTP\php\users\USERXX.db for user USERXX does not exist

LOG 2023-06-05 22:40:11 debug Client-Server Info: temporary skipping https://xxxxxxx.xxxxxxx.xx due to previous timeout or inconsistent response.

LOG 2023-06-05 22:40:11 error Client-Server Error: *Host sent an incorrect answer:
21 *ERROR: User doesn't exist

LOG 2023-06-05 22:40:11 debug Debug Debug: *Attributes sent to the RADIUS server: Reply-Message := "ERROR: User doesn't exist"
Reply-Message := "ERROR: User doesn't exist"

With the web browser i get the login page and the wed administration works:

https://xxxxxxx.xxxxxxx.xx 

multiOTP web administration console
the open source strong authentication library
multiOTP 5.9.6.1 2023-05-10
Web service is ready 2023-06-05 22:27:20, nginx/1.18.0, PHP/7.4.33
This package is the result of a *bunch* of work. If you find this package useful, [Donation] are always welcome to support this project.
Please check https://www.multiotp.net/ and you will find the magic button ;-)
Visit http://forum.multiotp.net/ for additional support. Are you interested in additional features like automatic syncronization of AD/LDAP users, provisioning PDF automatic email distribution, API automation, HA in master-slave mode and many others, everything through an easy and fast web interface ?
Check out our commercial editions here: https://www.multiOTP.com/
Login
Username:
Password:

Can you help?

Thanks

Carlos Baptista

ps: i try the forum.multiotp.net, but I think that is only with invitation.

**Comment by cbaptista** [comment]
Hi,

I'm pretty sure that the problem is related to this error:

php multiotp.windows.php -debug -display-log USERXX TOKENXXX -server-timeout=10 -server-cache-level=0 -server-url=https://xxxxxxx.xxxxxxx.xx -server-secret=SECRETXXX
PHP Warning: fgets(): SSL: An existing connection was forced closed by the remote host in C:\Program Files (x86)\multiOTP\php\multiotp.windows.php on line 21440

Any help?

Thanks
Carlos Baptista

**Comment by multiOTP** [comment]
Hello,
Be sure that your reverse proxy is not adding/changing any headers.
The next step will be to sniff the traffic on the proxy to know what is going inside and outside.
Regards,

**Comment by cbaptista** [comment]
Hi,
I will capture a tcpdump, but do you know if someone has an installation or even try it, behind a reverse proxy with ssl offload?

Thanks

**Comment by multiOTP** [comment]
Hello Carlos,
Do you have further information in order to fix this potential issue ?
Regards,

**Comment by multiOTP** [comment]
No more answer from @cbaptista for more than one month, case closed.
