### ISSUE TITLE
Wrong One-Time Passcode (OTP) Issue During Login

### ISSUE THREAD

**Issue by synetalsolutions** [multiOTP/multiotp#172]
Description:
I am encountering an issue with MultiOTP where I am receiving an "Invalid OTP" error during login attempts. I have followed the configuration steps as outlined in the documentation, but I'm unable to log in successfully due to the wrong OTP being generated.

However when I test the otp via  webserver it working by applying passwords and OTP from google authenticator but on server when I  try to login via RDP it not working.

Says invalid Passcode 

![image](https://github.com/multiOTP/multiotp/assets/32237609/26d29433-1d7a-4f99-bfcf-888dfbb6c8c5)

**Comment by syscoch** [comment]
Hello,
what kind of multiOTP server are you using ? (openSource, multiOTP pro, multiOTP enterprise)

Best regards

**Comment by multiOTP** [comment]
Hello,
do you still need our help ?
Best regards

**Comment by synetalsolutions** [comment]
Its working now only issue facing is audio not working on server even
services start after installing multiOTP credentials app.

**Comment by multiOTP** [comment]
Hello,
Thx for your feedback.
I clause the issueas the login is now working for you.
If you need to fix another issue, please open a new one. We don't have any reproductible information in order to check an audio issue.
Regards,
