### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [multiOTP/multiotp#173]
Dear @multiOTP team,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- https://github.com/IBM
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by multiOTP** [comment]
Hello,

What is the goal ?

Warning: Before converting a user into an organization, keep these points in mind.

You will no longer be able to sign into the converted personal account.
You will no longer be able to create or modify gists owned by the converted personal account.
An organization cannot be converted back to a user.
The SSH keys, OAuth tokens, job profile, reactions, and associated user information, will not be transferred to the organization. This is only true for the personal account that's being converted, not any of the personal account's collaborators.
Any GitHub Apps installed on the converted personal account will be uninstalled.
Any commits made with the converted personal account will no longer be linked to that account. The commits themselves will remain intact.
Any existing comments made by the converted personal account will no longer be linked to that account. The comments themselves will remain intact, but will be associated with the ghost user.
Any forks of private repositories made with the converted personal account will be deleted.

Regards,

**Comment by Neustradamus** [comment]
@multiOTP: Thanks for your reply!

Currently the multiOTP project uses a personal account, it is not a person.

There are two choices:

1/ Converting this current account and it is perfect directly.

2/ Renaming this personal account, the creation of an organization and transfer of the current repository into the organization. There are no lost, redirection will be here...

Some examples:
- https://github.com/libreswan has been converted
- https://github.com/exiftool has been converted
- https://github.com/redorescue has been converted
- https://github.com/asciimoo/searx -> https://github.com/searx/searx
- https://github.com/boothj5/profanity -> https://github.com/profanity-im/profanity
- https://github.com/nerzhul/ocsms -> https://github.com/nextcloud/ocsms
- https://github.com/tigaseinc/tigase-server -> https://github.com/tigase/tigase-server

**Comment by multiOTP** [comment]
@Neustradamus Thanks for your reply,
We will stay like this for now.
Regards,

**Comment by Neustradamus** [comment]
@multiOTP: Can you reopen this ticket, it is not done.
It is important to do not close unsolved ticket.
And it is important to do it.

**Comment by multiOTP** [comment]
Hello @Neustradamus,
Currently, we will keep the account like this.

**Comment by Neustradamus** [comment]
Dear @multiOTP team,

I do a comeback about my request, it is possible to do it?

Thanks in advance.

**Comment by Neustradamus** [comment]
@multiOTP: You have not understand all.

You have different steps, like I have specified in the past, please read all.

But if you do not want to convert this personal account (and select the good organization personal account owner):
- You can rename this personal account to another username (it takes few seconds here: https://github.com/settings/admin)
- Create the good organization following the first step (it takes few seconds here with the good username: https://github.com/organizations/plan)
- Transfer all multiotp repositories from the personal account into the organization (it takes few seconds)

ALL redirections will be here, no lost.

Several users and projects have done it without any problem.

Some examples:
- https://github.com/libreswan has been converted
- https://github.com/exiftool has been converted
- https://github.com/redorescue has been converted
- https://github.com/asciimoo/searx -> https://github.com/searx/searx
- https://github.com/boothj5/profanity -> https://github.com/profanity-im/profanity
- https://github.com/nerzhul/ocsms -> https://github.com/nextcloud/ocsms
- https://github.com/tigaseinc/tigase-server -> https://github.com/tigase/tigase-server

**Comment by Neustradamus** [comment]
Dear Andre Liechti from @multiOTP team,

Have you progressed on this historical request, ticket (2023-08-15)?

Do you need help?
I am available for you, to solve this problem.

Thanks in advance.
