### ISSUE TITLE
RDP (mstsc.exe) keeps crashing with Windows Server 2012 R2

### ISSUE THREAD

**Issue by walllam** [multiOTP/multiotp#178]
Issue Description:
When users log in to other servers through Windows Server 2012 R2 mstsc (Remote Desktop Connection), an error occurs with the following details:
```
  Problem Event Name: APPCRASH
  Application Name: mstsc.exe
  Application Version: 6.3.9600.18980
  Application Timestamp: 5ab67164
  Fault Module Name: authui.dll
  Fault Module Version: 6.3.9600.20772
  Fault Module Timestamp: 639ab096
  Exception Code: c0000005
  Exception Offset: 00000000000a7ea3
  OS Version: 6.3.9600.2.0.0.144.8
  Locale ID: 2052
  Additional Information 1: dced
  Additional Information 2: dced54a4f740010c972b500b47967650
  Additional Information 3: 1782
  Additional Information 4: 1782beeddd3daa7fd007f869c3fc3d4d
```
Steps to Reproduce:

>Open Windows Server 2012 R2 mstsc (Remote Desktop Connection).
Enter the necessary server information (IP address, username, password, etc.).
Click on the "Connect" button to initiate the remote desktop session.
After successful authentication, the APPCRASH error occurs.

Expected Result:
Users should be able to log in to other servers through Windows Server 2012 R2 mstsc without encountering an APPCRASH error.

Actual Result:
An APPCRASH error occurs when users attempt to log in to other servers through Windows Server 2012 R2 mstsc.

Additional Information:

This issue started occurring after enabling multiotp 2FA authentication in Windows Server 2012 R2.
The error message does not provide specific details about the cause of the crash.
The issue is reproducible on multiple client machines and with different remote servers.

**Comment by multiOTP** [comment]
Hello,
thanks for using our product. Windows Server 2012 is not supported anymore by Microsoft therefore we will not support Credential Provider on this Operating System anymore.

Can you update your server and try again.

Best regards
