### ISSUE TITLE
RDweb + multiOTP problem Windows 2022

### ISSUE THREAD

**Issue by sabych** [multiOTP/multiotp#180]
Hi!

I've tried to setup Multiotp on RDweb server. I have successfully installed multiotp credential provider, and connect to multiotp server. Authentication (login) is working with no problems, when I try to connect on rdweb sever locally or vi remote desktop program. But if I use rdweb portal I receive :
![image](https://github.com/multiOTP/multiotp/assets/149696986/c90fe264-2f58-4521-99f8-bd364df6e6ba)

For configuring MultiOTP on RDweb server used this [tutorial](http://roman.gallauner.at/?p=886)

Any help would be appreciated.

Thanks!

**Comment by multiOTP** [comment]
Hello,

You have inserted bad syntax in the files.
Here are an example of the modified files
- **C:\Windows\Web\RDWeb\Web.config**
[Web.config.txt](https://github.com/multiOTP/multiotp/files/13453075/Web.config.txt)
Compare with original: [Web-org.config.txt](https://github.com/multiOTP/multiotp/files/13453082/Web-org.config.txt)
- **C:\Windows\Web\RDWeb\Pages\en-US\login.asp**
[login.aspx.txt](https://github.com/multiOTP/multiotp/files/13453077/login.aspx.txt)
Compare with original: [login-org.aspx.txt](https://github.com/multiOTP/multiotp/files/13453086/login-org.aspx.txt)

Best regards,

**Comment by sabych** [comment]
Thanks colleagues, I figured it out. My pool account did not have rights. everything works now.

**Comment by 146junior** [comment]
Hi,

I would like to point out that I have read and reread all the various posts, also checking the files posted, but the integration doesn't work for me.

I tried integrating MultiOTP Credential Provider with RDWeb.
I followed Roman's tutorial and the files posted here, but I always get "Invalid username or password"
I enabled logs in multiotp.ini but there is no connection trace.
By carrying out the tests from the multiotp credential provider, I can connect to the multiotp server without problems and validate the otp.

My environment is Windows Server 2022
Domain users are in the format domain\t.test

Can you help me please
Thank you

**Comment by 146junior** [comment]
thanks for reply Sabych,
I have added the IUSR and IIS_IUSRS with full access to multiOTP folder but nothing has changed.
It still doesn't consider the changes and there is no trace in the logs.

**Comment by sabych** [comment]
> thanks for reply Sabych, I have added the IUSR and IIS_IUSRS with full access to multiOTP folder but nothing has changed. It still doesn't consider the changes and there is no trace in the logs.

no, you also need to add these accounts to local administrators on the server with Multiotp and on the RD WEB server, one of these connections is definitely added. try adding both, and leave the one that is added. I just don't remember which one.

**Comment by 146junior** [comment]
I found out what the problem is.
The accepted username is domain\name while we use domain\n.surname
How can I change the syntax?

**Comment by 146junior** [comment]
thank you so much for your support
