### ISSUE TITLE
Feature request : Hide default Username / Password after changed #146 isn't working

### ISSUE THREAD

**Issue by lollett** [multiOTP/multiotp#185]
The show default credentials until changed functionality doesn't seem to be working.

i.e. Its not showing admin and 1234 on a clean windows install of 5.9.7.1

**Comment by multiOTP** [comment]
Please check in the #146
With a fresh install, the multiotp.ini configuration file is not created before calling the page for the first time.
If you do a "SHIFT+RELOAD", the default credentials are displayed.
We will try to fix that starting with version 5.9.7.2
