### ISSUE TITLE
Problem Syntax Username from RDWeb - MultiOTP

### ISSUE THREAD

**Issue by 146junior** [multiOTP/multiotp#186]
Hi,
I have a problem with the MultiOtp - RdWeb integration.
It works well if I use the domain\name syntax in the domain
Since in our domain we use the syntax domain\n.surname (initial of the name . surname) authentication does not occur by giving the wrong username or password message.
How can I solve the problem?
Thanks for your precious help

**Comment by multiOTP** [comment]
Hello,
your multiOTP users must have the same name as used on the Windows login form. (n.surname in your case).

Regards

**Comment by 146junior** [comment]
Thanks for reply
my multiotp server is configured with DC's ldap. Users are synchronized. If I run the test from the prompt the users work perfectly with the DC syntax. Should I disconnect it and just create them locally?

**Comment by multiOTP** [comment]
Hello,
you could try to create a user manually and check if it works.

For the LDAP sync you can set what AD field to use using this command :

multiotp -config ldap-cn-identifier="sAMAccountName"
(by default sAMAccountName but you could use userPrincipalName)

The login you use MUST be valid for multiOTP AND for Windows. If n.surname is not in sAMAccountName nor in userPrincipalName you probably won't be able to use it to login.

Best regards.

**Comment by 146junior** [comment]
I made the suggested changes, it changed the syntax by importing from ldap in the format name.surname@domain.xxxxx The same works only from a prompt.
I understand that the problem is linked to the dot between name and surname. As soon as I create the credentials with any name and surname it works both from the prompt and from RDWeb, as soon as I add a point via RDWeb it no longer works.

**Comment by 146junior** [comment]
Is there any way I can use the syntax I have?
Thanks

**Comment by multiOTP** [comment]
Hello,
in the config file *C:\Windows\Web\Web.Config*, there is a regexp expression named *OTPUsernameRegex*.
Please add a dot (.) in after the capital Z :

`<add key="OTPUsernameRegex" value="^[0-9a-zA-Z.]*$" />`

Best regards
