### ISSUE TITLE
Wrong one-time Password

### ISSUE THREAD

**Issue by pogosyan-it** [multiOTP/multiotp#189]
Hello.
A have the same problem as described in issue:
https://github.com/multiOTP/multiotp/issues/41
The solution was to upgrade the version.  I'm using a much newer version than the one was mentioned in this solution, so I have to reopen the issue. 
Let me brifly describe the problem:
I'm using AD authentification. On my TOTP web interface I can see all users in group which was set in container.
![image](https://github.com/multiOTP/multiotp/assets/46302610/3703a180-4b81-49b8-ad08-64602a63d4b6)
When I'm trying to authentificate on my windows server 2019 I revice an error: "**TOTP password is wrong**".
From cmd of windows server I'm receiving:
![Uploading image.png…]()
But test from container:
root@f9d7ff3a4d91:/# multiotp -display-log yrpogosyan 569647
LOG 2024-04-14 19:47:50 notice (user yrpogosyan) User OK: User yrpogosyan successfully logged in with TOTP token
and test from web interface (check a user)
Test result: | succeeded
 are both successful. 
When I'm checking the directory users in Program files\multiotp it appears to be empty. The firewall on the windows server is turned off, the server is in domain. The linux server where conteiner is deployed and windows server are in the same subnet. 
Below are all the settings that I have made in the container:

multiotp -config default-request-prefix-pin=0
multiotp -config default-request-ldap-pwd=0
multiotp -config ldap-ssl=0
multiotp -config ldap-port=389
multiotp -config ldap-domain-controllers=domaincontroller.myorg.com
multiotp -config ldap-in-group="2FAGROUP"
multiotp -config ldap-cn-identifier="sAMAccountName"
multiotp -config ldap-group-cn-identifier="sAMAccountName"
multiotp -config ldap-group-attribute="memberOf"
multiotp -config ldap-bind-dn="user"
multiotp -config ldap-server-password="pass"
multiotp -config ldap-bind-dn="CN=user,OU=TechUsers,OU=myorg,OU=Systems,DC=myorg,DC=local"
multiotp -config ldap-base-dn="DC=myorg,DC=local"
multiotp -config server-secret=secretOTP
multiotp -config debug=1
multiotp -config ldap-network-timeout=10
multiotp -config ldap-time-limit=90
multiotp -config ldap-activated=1
multiotp -config disp-displaylay-log=1-display
I'll expect you to help me with this problem. Thank you in advance.

**Comment by pogosyan-it** [comment]
For some reason the second picture didn't upload. 
![image](https://github.com/multiOTP/multiotp/assets/46302610/9af9d987-2f0f-4986-a33f-06e2c0eb141b)

**Comment by multiOTP** [comment]
Hello,
Can you check if you Windows server can access your docker multiOTP on the address 11.217.238.152

Best regards

**Comment by pogosyan-it** [comment]
Thanks you for  response.
Of course I have access from my windows host to the server with  multiotp container:
This is tcpdump on 11.217.238.152
![image](https://github.com/multiOTP/multiotp/assets/46302610/23dd6ddb-1b78-4a64-8f85-887c3d9963e5)
I receiving it when on the windows server  the command was running:
![image](https://github.com/multiOTP/multiotp/assets/46302610/5764857d-c214-4a68-af3b-9ee5bad015fc)

Also I'm receiving reply on ping and telnet works on 80 and 443/tcp ports. 
![image](https://github.com/multiOTP/multiotp/assets/46302610/0f6cb253-c6e9-4c33-90d6-d556ebd5faaf)

**Comment by pogosyan-it** [comment]
It's a pitty I'didn't receive any answer.  I wonder which protolol is used for transfer files username.db from container to the windows host in folder c:\program files\Multiotp\Users?  After instalation of CredentialProvider on the windows host there is no folder Users, it creates after first attempt to login using multiotp. When I put files username.db myself in this folder everything works fine,

**Comment by multiOTP** [comment]
When you install the Credential Provider on Windows, you have to give the URL of your multiOTP server (in your case the URL of your Docker multiOTP server web interface), and also the shared secret (by default: **ClientServerSecret**).
When someone try to connect on the server using the CredentialProvider, the CredentialProvider will sent a (https) request to the multiOTP server, and if the username, password and OTP is correct, it will answer back to the CredentialProvider with the content of the username file (in order to make cache on the CredentialProvider side).
Regards,

**Comment by pogosyan-it** [comment]
Great! Your comment was very helpful. When I set during instalation of the Credential Provider, URL of my Docker multiOTP in such a way **https://My_server_IP**, everythink worked correctly.  
Thank you
Best regards.

**Comment by radiotehnick** [comment]
Good afternoon,

I have 10 servers, one of which is an OTP server running on port 8113. I installed the client on the other servers and specified https://<ip>:8113 or https://<namesrv>:8113. I also set a secret password. However, in the folder C:\Program Files\multiOTP\users, the users who are approve access to the server do not appear. On the server (otp-Server) where the OTP server is hosted, login with a one-time password works correctly.

If I copy the user database from Server (otp-server) and paste it into C:\Program Files\multiOTP\users on another server, it allows me to log in.

Can you help me?
*all servers- windows 2019
* we create users manually, not via ldap

**Comment by pogosyan-it** [comment]
Everything is ok. I specified on windows client https://IP. Port by default
must be 443. Thank you for helping.

вт, 6 мая 2025 г., 18:32 radiotehnick ***@***.***>:

**Comment by multiOTP** [comment]
> Good afternoon,
> 
> I have 10 servers, one of which is an OTP server running on port 8113. I installed the client on the other servers and specified https://:8113 or https://:8113. I also set a secret password. However, in the folder C:\Program Files\multiOTP\users, the users who are approve access to the server do not appear. On the server (otp-Server) where the OTP server is hosted, login with a one-time password works correctly.
> 
> If I copy the user database from Server (otp-server) and paste it into C:\Program Files\multiOTP\users on another server, it allows me to log in.
> 
> Can you help me? *all servers- windows 2019
> 
> * we create users manually, not via ldap

Hello,
It's not a good idea to ask for another issue in a closed issue :-(

> Everything is ok. I specified on windows client https://IP. Port by default
> must be 443. Thank you for helping.
> 
> вт, 6 мая 2025 г., 18:32 radiotehnick ***@***.***>:
> […](#)

It seems that @radiotehnick and @pogosyan-it are the same users, correct ?

Regards

**Comment by radiotehnick** [comment]
No, we are different users, it's just that this is my first time writing here and I don't know how to do it correctly, but I found this forum through a browser search.


> > Good afternoon,
> > I have 10 servers, one of which is an OTP server running on port 8113. I installed the client on the other servers and specified https://:8113 or https://:8113. I also set a secret password. However, in the folder C:\Program Files\multiOTP\users, the users who are approve access to the server do not appear. On the server (otp-Server) where the OTP server is hosted, login with a one-time password works correctly.
> > If I copy the user database from Server (otp-server) and paste it into C:\Program Files\multiOTP\users on another server, it allows me to log in.
> > Can you help me? *all servers- windows 2019
> > 
> > * we create users manually, not via ldap
> 
> Hello, It's not a good idea to ask for another issue in a closed issue :-(
> 
> > Everything is ok. I specified on windows client https://IP. Port by default
> > must be 443. Thank you for helping.
> > вт, 6 мая 2025 г., 18:32 radiotehnick _**@**_.***>:
> > […](#)
> 
> It seems that [@radiotehnick](https://github.com/radiotehnick) and [@pogosyan-it](https://github.com/pogosyan-it) are the same users, correct ?
> 
> Regards
