### ISSUE TITLE
AD bind failed. Check the login credentials (Invalid credentials)

### ISSUE THREAD

**Issue by goonux** [multiOTP/multiotp#19]
### **Hi MultiOTP Team, 

I have problem bellow**

[root@otpserver public_html]# ./multiotp.php  -debug -display-log -ldap-users-sync

LOG 2017-06-15 09:48:24 debug Debug Debug: *parameter(s) received: -debug -display-log -ldap-users-sync

LOG 2017-06-15 09:48:24 debug LDAP Debug: *AD/LDAP synchronization started at 09:48:24 / Memory used: 21.6MB / Peak: 22.2MB

LOG 2017-06-15 09:48:24 info LDAP Info: AD/LDAP synchronization started

LOG 2017-06-15 09:48:24 debug System Debug: *LDAP cache folder value: /tmp/.ldap_cache/

LOG 2017-06-15 09:48:24 warning LDAP Error: FATAL: AD bind failed. Check the login credentials (Invalid credentials).
99 *ERROR: Authentication failed (and other possible unknown errors)

LOG 2017-06-15 09:48:24 debug Debug Debug: *Attributes sent to the RADIUS server: Reply-Message := "ERROR: Authentication failed (and other possible unknown errors)"
Reply-Message := "ERROR: Authentication failed (and other possible unknown errors)"

**### Here my multiotp.ini**

`[root@otpserver public_html]# cat /etc/multiotp/config/multiotp.ini 
multiotp-database-format-v3
; If backend is set to something different than files,
; and backend_type_validated is set to 1,
; only the specific information needed for the backend
; is used from this config file.

encryption_hash=99CCFC0D033729754B6BB4832FE786A1
server_secret:=dGx9cn5qeFV7fFJ5RGR/cGd4
actual_version=5.0.4.6
admin_password_hash:=RmM+aS4EPREmfFEyIiQQeSF7MGoWPSBOXCZmP3w1G3w=
anonymous_stat=1
anonymous_stat_last_update=1497258907
anonymous_stat_random_id=c7b9e7050a8526230091ae8fb1d37c59569137e2
attributes_to_encrypt=
auto_resync=1
backend_encoding=UTF-8
backend_type=files
backend_type_validated=0
cache_data=0
cache_ldap_hash=1
case_sensitive_users=0
clear_otp_attribute=
console_authentication=0
debug=0
default_algorithm=totp
default_dialin_ip_mask=
default_user_group=
default_request_ldap_pwd=0
default_request_prefix_pin=0
demo_mode=0
display_log=0
domain_name=
email_admin_address=
encode_file_id=0
encryption_key_full_path=
failure_delayed_time=300
group_attribute=Filter-Id
hash_salt_full_path=
issuer=multiOTP
language=en
last_update=1497512728
ldap_account_suffix=
ldap_activated=1
ldap_base_dn=DC=FIS,DC=LOCAL
ldap_bind_dn=CN=Administrator,CN=Users,DC=FIS,DC=LOCAL
ldap_cache_folder=tempdir
ldap_cache_on=1
ldap_cn_identifier=sAMAccountName
ldap_default_algorithm=totp
ldap_domain_controllers=AD-Novaland.FIS.LOCAL,ldap://AD-Novaland.FIS.LOCAL:389
last_failed_white_delay=60
ldap_group_attribute=memberOf
ldap_group_cn_identifier=sAMAccountName
ldap_groups_dn=
ldap_hash_cache_time=604800
ldap_in_group=MonUsers,Administrators
ldap_language_attribute=preferredLanguage
ldap_network_timeout=10
ldap_port=389
ldap_recursive_cache_only=0
ldap_recursive_groups=1
ldap_server_password:=bmhHIxouJg==
ldap_server_type=1
ldap_ssl=0
ldap_synced_user_attribute=
ldap_time_limit=30
log=0
max_block_failures=6
max_delayed_failures=3
max_event_resync_window=10000
max_event_window=100
max_time_resync_window=90000
max_time_window=600
multiple_groups=0
ntp_server=pool.ntp.org
overwrite_request_ldap_pwd=1
radius_error_reply_message=1
radius_reply_attributor= += 
radius_reply_separator_hex=2c
scratch_passwords_digits=6
scratch_passwords_amount=10
self_registration=1
server_cache_level=1
server_cache_lifetime=15552000
server_timeout=5
server_type=xml
server_url=
sms_api_id:=
sms_message_prefix=%s is your SMS-Code
sms_originator=multiOTP
sms_password:=
sms_provider=
sms_userkey:=
sms_digits=6
sms_timeout=180
smtp_auth=0
smtp_password:=
smtp_port=25
smtp_sender=
smtp_sender_name=
smtp_server=
smtp_ssl=0
smtp_username=
sql_server=
sql_username=
sql_password:=
sql_database=
sql_schema=
sql_config_table=multiotp_config
sql_cache_table=multiotp_cache
sql_devices_table=multiotp_devices
sql_groups_table=multiotp_groups
sql_log_table=multiotp_log
sql_tokens_table=multiotp_tokens
sql_users_table=multiotp_users
syslog_facility=7
syslog_level=5
syslog_port=514
syslog_server=
tel_default_country_code=
timezone=Europe/Zurich
token_serial_number_length=12
token_otp_list_of_length=6
verbose_log_prefix=
`

I used Centos 6.9 64bit minimal 
Can you check it for me. Thank you.

**Comment by multiOTP** [comment]
Hello,
The bind failure is returned by the ldap_bind() function of PHP.
On your server, could you try to do a LDAP binding with the PHP ldap_bind() function using your username and your password ?
We don't see any problem in the configuration file.
Regards.

**Comment by goonux** [comment]
**i try to test LDAP binding by script** 

`<?php

// using ldap bind
$ldaprdn  = 'uname';     // ldap rdn or dn
$ldappass = 'password';  // associated password

// connect to ldap server
$ldapconn = ldap_connect("ldap.example.com")
    or die("Could not connect to LDAP server.");

if ($ldapconn) {

    // binding to ldap server
    $ldapbind = ldap_bind($ldapconn, $ldaprdn, $ldappass);

    // verify binding
    if ($ldapbind) {
        echo "LDAP bind successful...";
    } else {
        echo "LDAP bind failed...";
    }

}

?>`

**And Resulted**

[root@otpserver public_html]# php test_connect_lapd.php 
LDAP bind successful...

**I used  version php 5.3.3**

**Comment by multiOTP** [comment]
Ok, did you put CN=Administrator,CN=Users,DC=FIS,DC=LOCAL as the $ldaprdn ?

**Comment by goonux** [comment]
Hi 
I set  : $ldaprdn  = 'Administrator';     // ldap rdn or dn

**Comment by goonux** [comment]
**i tryed to set** 

<?php

// using ldap bind
$ldaprdn  = 'CN=Administrator,CN=Users,DC=FIS,DC=LOCAL';     // ldap rdn or dn
$ldappass = '*********';  // associated password

// connect to ldap server
$ldapconn = ldap_connect("AD-Novaland.FIS.LOCAL")
    or die("Could not connect to LDAP server.");

if ($ldapconn) {

    // binding to ldap server
    $ldapbind = ldap_bind($ldapconn, $ldaprdn, $ldappass);

    // verify binding
    if ($ldapbind) {
        echo "LDAP bind successful...";
    } else {
        echo "LDAP bind failed...";
    }

}

?>

**It's work fine**

[root@otpserver public_html]# php test_connect_lapd.php 
LDAP bind successful...

**Comment by multiOTP** [comment]
OK, put the same in the config file and try again.

**Comment by multiOTP** [comment]
And what about the server, also AD-Novaland.FIS.LOCAL ?
Your DNS is resolving correctly AD-Novaland.FIS.LOCAL on the Linux machine used for multiOTP ?

**Comment by goonux** [comment]
**Hi, 
I edited file bellow** 

```
[root@otpserver public_html]# cat test_connect_lapd.php 
<?php

// using ldap bind
$ldaprdn  = 'CN=Administrator,CN=Users,DC=FIS,DC=LOCAL';     // ldap rdn or dn
$ldappass = 'Fi$Ent@2017';  // associated password

// connect to ldap server
$ldapconn = ldap_connect("AD-Novaland.FIS.LOCAL")
    or die("Could not connect to LDAP server.");

if ($ldapconn) {

    // binding to ldap server
    $ldapbind = ldap_bind($ldapconn, $ldaprdn, $ldappass);

    // verify binding
    if ($ldapbind) {
        echo "LDAP bind successful...";
    } else {
        echo "LDAP bind failed...";
    }

}

?>
```
**And it works fine**

```
[root@otpserver public_html]# php test_connect_lapd.php 
LDAP bind successful...[root@otpserver public_html]#
```
My DNS Server work ok. Here my ping trace

```
[root@otpserver public_html]# ping AD-Novaland.FIS.LOCAL
PING AD-Novaland.FIS.LOCAL (192.168.1.1) 56(84) bytes of data.
64 bytes from AD-Novaland.FIS.LOCAL (192.168.1.1): icmp_seq=1 ttl=128 time=0.377 ms
64 bytes from AD-Novaland.FIS.LOCAL (192.168.1.1): icmp_seq=2 ttl=128 time=0.264 ms
^C
--- AD-Novaland.FIS.LOCAL ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1895ms
rtt min/avg/max/mdev = 0.264/0.320/0.377/0.059 ms
[root@otpserver public_html]#
```

**Comment by multiOTP** [comment]
Hello,
We set this password for a test account and it works alos.

The LDAP connection do this exactly. Please check this:

```
<?php

// using ldap bind
$ldaprdn  = 'CN=Administrator,CN=Users,DC=FIS,DC=LOCAL';     // ldap rdn or dn
$ldappass = 'Fi$Ent@2017';  // associated password

// connect to ldap server
$ldapconn = ldap_connect("ldap://AD-Novaland.FIS.LOCAL:389")
    or die("Could not connect to LDAP server.");

ldap_set_option($ldapconn, LDAP_OPT_PROTOCOL_VERSION, 3);
ldap_set_option($ldapconn, LDAP_OPT_REFERRALS, 0);

if ($ldapconn) {

    // binding to ldap server
    $ldapbind = ldap_bind($ldapconn, $ldaprdn, $ldappass);

    // verify binding
    if ($ldapbind) {
        echo "LDAP bind successful...";
    } else {
        echo "LDAP bind failed...";
    }

}

?>
```

You could also upgrade to version 5.0.4.8 from here to be sure to have the last version : http://download.multiotp.net/

Regards,

**Comment by goonux** [comment]
Thank you for you assist, let me recheck it.

**Comment by multiOTP** [comment]
Any feedback ?

**Comment by yeughe** [comment]
hello, I encountered the same problem, multiotp version 5.6.1.5, php7.3 ,openldap 2.4.44
when  i try to test LDAP binding by script，LDAP bind successful 
The log  is as follows:
multiotp 5.6.1.5
Your script is running from /usr/local/bin/
2020-05-11 19:26:00     debug           LDAP    Debug: *AD/LDAP synchronization started at 19:26:00 / Memory used: 10.5MB / Peak: 25.3MB
2020-05-11 19:26:00     info            LDAP    Info: AD/LDAP synchronization started
2020-05-11 19:26:00     debug           System  Debug: *LDAP cache folder value: /tmp/.ldap_cache/
2020-05-11 19:26:00     warning         LDAP    Error: FATAL: AD bind failed. Check the login credentials (49: Invalid credentials).
2020-05-11 19:26:00     debug           Debug   Debug: *99 ERROR: Authentication failed (and other possible unknown errors)
2020-05-11 19:26:00     debug           Debug   Debug: *Attributes sent to the RADIUS server: Reply-Message := "ERROR: Authentication failed (and other possible unknown errors)"

multiotp.ini
last_sync_update=0
last_sync_update_host=
last_update=1589179407
last_update_host=radius-2fa-prod
ldap_expired_password_valid=1
ldap_account_suffix=
ldap_activated=1
ldap_base_dn=dc=xxxxx,dc=me
ldap_bind_dn=cn=read,dc=xxxxx,dc=me
ldap_cache_folder=tempdir
ldap_cache_on=1
ldap_cn_identifier=uid
ldap_default_algorithm=totp
ldap_domain_controllers=ldap://192.168.8.8
last_failed_white_delay=60
ldap_group_attribute=memberOf
ldap_group_cn_identifier=cn
ldap_users_dn=ou=users,dc=xxxxx,dc=me
ldap_hash_cache_time=604800
ldap_in_group=
ldap_language_attribute=preferredLanguage
ldap_network_timeout=10
ldap_port=389
ldap_recursive_cache_only=0
ldap_recursive_groups=1
ldap_server_password:='xxxxxxxxxxxx'
ldap_server_type=2
ldap_ssl=0
ldap_synced_user_attribute=
ldap_time_limit=30
ldaptls_reqcert=auto
ldaptls_cipher_suite=auto
log=1

I am sure it is not a password issue，can you give me your hand , thanks very much !
