### ISSUE TITLE
Reset user OTP-code

### ISSUE THREAD

**Issue by MRagulin** [multiOTP/multiotp#198]
I made my own web-server for users for possibility ldap authorization and print QR-code from multiOTP-server from local network. 

I use request like http://server/?method=PrintQrCode&options=user to multiOTP-server  get their QR-code from multiOTP but QR-code always tha same.
I need  generate new QR-code each time when I make request to multiOTP.

How do can I make request to web-server for new QR-code or possobility reset user OTP code with HTTP request to server?

**Comment by multiOTP** [comment]
Hello,
The QRcode contains the seed of the user token. It's always the same for the same user.
If you want a New QRcode, The easiest way to go is to delete the user (http://server/?method=DeleteUser&options=user ) and recreate it again, and then print the QRcode.
Regards,
