### ISSUE TITLE
Timeout, memory exhausted with big ActiveDirectory

### ISSUE THREAD

**Issue by mmuszkow** [multiOTP/multiotp#2]
Hi,
Our ActiveDirectory has ~50k users, ~50k groups and thousands of other records. When syncing:
1. timeout occurs as in multiotp.php it is set to 15 secs (fixed value). I increased that value to 120 secs and ...
2. Search of users, groups and computers is made on base DN, which is quite slow because it's looking through the whole AD tree. I manually specified the more specific search paths for users & groups in multiotp.class.php, but ...
3. After changing the paths, this happens:
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /opt/multiotp/multiotp.proxy.php on line 55
4. I increased the memory_limit to 1GB, but this doesn't help. The "ldap-in-group" contains only 2 users.

Can you consider improving the performance of the AD queries?

**Comment by multiOTP** [comment]
Hello,

The last beta version improved the performance. Could you have a look and give us a comment ?

Last beta version: [http://download.multiotp.net/beta/](http://download.multiotp.net/beta/)

A released version will be available soon.

Best regards,

Andr

**Comment by multiOTP** [comment]
Users should not be a problem anymore, but the groups handling should be improved a little bit in the next weeks. Regards, and thanks in advance for your feedback.

**Comment by mmuszkow** [comment]
Thank you for quick answer. The timeout doesn't occur in the beta version (4.3.3.1), but the problem with memory exhaustion remains:
```
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 32 bytes) in /opt/multiotp/multiotp.php on line 56
```

**Comment by multiOTP** [comment]
We will prepare a similar test AD, with ~50k users, ~50k groups and thousands of other records. Could you give us the average number of groups in which one user is ?

**Comment by mmuszkow** [comment]
It varies a lot. The accounts (users) that represent real people usually belong to ~100-300 groups (there are ~25k such accounts), however there are many service accounts (users) that belongs to few thousands groups.
It would be definitely a good idea if we could specify the root DN for users and for groups in the multiotp configuration.

**Comment by multiOTP** [comment]
Algorithm should be improved in the next weeks concerning AD with huge groups

**Comment by multiOTP** [comment]
Thanks do download and to try the last 5.0.3.3-beta-1 version available here : [http://download.multiotp.net/beta/](http://download.multiotp.net/beta/)
A lot of works has been done since February, including for large AD/LDAP.
Any feedback welcome.
A new release will be published soon in GitHub, but it could be nice to have your feedback before.
Best regards

**Comment by mmuszkow** [comment]
I no longer work for that company, so I have no possibility to check it anymore. Thanks for the improvements anyway.
