### ISSUE TITLE
[Help Needed] How to change the logo displayed on the Windows login screen?

### ISSUE THREAD

**Issue by iwalke** [multiOTP/multiotp#203]
Hello,I replaced the loginLogo.bmp file, but it doesn't seem to work. The Windows login screen still displays the default multiOTP logo.

Is there any way to customize or update the logo? 

Thank you!

![image](https://github.com/user-attachments/assets/dbc422df-5e0c-4b0c-ad2d-2aa62b1d62af)

https://github.com/multiOTP/multiotp/issues/120#issuecomment-2552589490

**Comment by multiOTP** [comment]
Hello,
yes you can.
Did you configure the logo path in the registry under HKEY_CLASSES_ROOT\CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\v1_bitmap_path ?

You must set the complete path and filename of a bitmap image. The image **must** be a version 3 Windows BMP file with a resolution of 128x128 pixels.

Best regards

**Comment by kty00** [comment]
Hi @iwalke , I was wondering if you’ve managed to resolve this issue? I’m encountering a similar problem. Specifically, I can locate the corresponding icon settings path in the registry, but after making the changes, it doesn’t seem to take effect.

![image](https://github.com/user-attachments/assets/d575063c-25bf-49c4-833e-64b478567687)

[multiotp-logo.zip](https://github.com/user-attachments/files/18309534/multiotp-logo.zip)

**Comment by kty00** [comment]
> Hi @iwalke , I was wondering if you’ve managed to resolve this issue? I’m encountering a similar problem. Specifically, I can locate the corresponding icon settings path in the registry, but after making the changes, it doesn’t seem to take effect.
> 
> ![image](https://private-user-images.githubusercontent.com/185750878/400185470-d575063c-25bf-49c4-833e-64b478567687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNjMxMDMsIm5iZiI6MTczNjA2MjgwMywicGF0aCI6Ii8xODU3NTA4NzgvNDAwMTg1NDcwLWQ1NzUwNjNjLTI1YmYtNDljNC04MzNlLTY0YjQ3ODU2NzY4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNVQwNzQwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTViMTMwN2E0NTg5NWU0YTYxMDNmNzhlNmQ4MjNlYjM5OGQ0MmIyODJmN2U2YWMwNGZiNmM4NjZhMDY1NGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VKkT9yizzO1nzplm4B0lagiKCDtGH0LWMnm8YlNkpDA)
> 
> [multiotp-logo.zip](https://github.com/user-attachments/files/18309534/multiotp-logo.zip)

I restarted Windows, but it still didn't take effect.
