### ISSUE TITLE
Unclear how sms field of user should be populated in case of LDAP sync with Active Directory

### ISSUE THREAD

**Issue by octo-teacat** [multiOTP/multiotp#204]
MultiOTP version : 5.9.7.1
OS : Windows
Hi
Users are syncing correctly from Active Directory, but sms field in users/myuser.db is not populated
I've looked up LDAP conversation between **multiOTP** and domain controller - ldap query returns user attribute "**telephoneNumber**" - but it is unused by multiOTP. 
In **MultiotpAdLdap.php** there is some code that refer those attributes:
```php
if ($attributes["telephone"]){ $mod["telephoneNumber"][0]=$attributes["telephone"]; }
if ($attributes["mobile"]){ $mod["telephoneNumber"][0]=$attributes["mobile"]; }
```
but it does not seems to be used e.g.:
```php
//create a user
    function user_create($attributes){
        //check for compulsory fields
        if (!array_key_exists("username",$attributes)){ return ("Missing compulsory field [username]"); }
        if (!array_key_exists("firstname",$attributes)){ return ("Missing compulsory field [firstname]"); }
        if (!array_key_exists("surname",$attributes)){ return ("Missing compulsory field [surname]"); }
        if (!array_key_exists("email",$attributes)){ return ("Missing compulsory field [email]"); }
        if (!array_key_exists("container",$attributes)){ return ("Missing compulsory field [container]"); }
        if (!is_array($attributes["container"])){ return ("Container attribute must be an array."); }
```
Question : Is it by design? How we can make it sync users including **telephoneNumber** or any other custom attribute?
Thank You

**Comment by multiOTP** [comment]
Hello,
Yes, it's by design, because the phone number we are talking about is the mobile phone number, as we want to send SMS to it.
You will have to fill the "Mobile Phone" attribute in Active Directory, and it will sync correctly.
Regards,

**Comment by octo-teacat** [comment]
Thank you for your reply. The solution **works** when I set the "**Mobile Phone**" (mobile) attribute.

However, we have privacy requirements that restrict storing users mobile numbers in publicly readable attributes, which "**Mobile Phone**" unfortunately is.

Am I correct in understanding that if we use a custom attribute, such as **myOrgMobilePhone**, with the confidentiality bit set (not publicly readable), and we want **multiOTP** to sync with this specific attribute, we would need to modify the PHP code throughout the project wherever references to mobile or "**Mobile Phone**" exist?

Additionally, would we also need to update the **RADIUS** configurations in the radius folder to accommodate this change?

Thank you.

**Comment by multiOTP** [comment]
Hello,
You don't need to change anything in the RADIUS configuration.
In the PHP code, you will have to rename any `"mobile"` and `'mobile'` occurences to `"myOrgMobilePhone"` and `'myOrgMobilePhone'`.
Keep us in touch
Regards,
