### ISSUE TITLE
Configuring multiOTP to send sms when logging in

### ISSUE THREAD

**Issue by TarlanAbdullayev** [multiOTP/multiotp#22]
Hello. Can you help me? I set multiotp, it works through google authenticator. But I want to configure it via SMS authenticator, using our SMS server. Where and how this can be configured? And can SMS authenticator and google authenticator to work at the same time? Or should only run one?

**Comment by multiOTP** [comment]
Hello,
Which SMS server do you have ?

**Comment by TarlanAbdullayev** [comment]
Thank you for your answer.
SMS web service, send SMS via the operator. 
Current setup is VM multiOTP open source. I want to use two-factor authentication in the domain.

**Comment by multiOTP** [comment]
Did you already install the multiOTP Credential Provider on the machines of the domain ?
To use your own SMS web service, modify the following in the config file of multiOTP (/etc/multiotp/config/multiotp.ini):
 * sms-provider = exec
 * sms-api-id = /path/to/your/exec param1 param2 param3 (in the parameters, %from is replaced by the sender value, %to is replaced by the destination SMS number and %msg is replaced by the text message).

If you want to receive an SMS; give your username and type sms as the password. The login will be refuses, but you will receive an SMS with a valid code for the next try.

The next version of multiOTP Credential Provider will have the possibility to require an SMS without sending "sms" as a password.

Regards

**Comment by TarlanAbdullayev** [comment]
Yes, I install version 5.0.4.8.
The first two steps I did. But where to change and set the username and type sms as the password? 
And when next version of multiOTP Credential Provider will appear?
Thank in advance.

**Comment by multiOTP** [comment]
Hello,
sms and TOTP ( like google authenticator) can be use as the same time.

With the current version of multiOTP Credential Provider:
First step:
Username : [windows username]
Password: [windows password]
OTP: [s][m][s] (you have to type the three small letters [s] [m] [s] to request the system to send an SMS

Second Step:
Username : [windows username]
Password: [windows password]
OTP: [sms code receveived]

In the next multiOTP Credential Provider available later this month:
Username : [windows username]
Password : [windows password]
Click on the "Send an SMS code" link
Type in the OTP field the received SMS

Regards,

**Comment by TarlanAbdullayev** [comment]
Hello,

One more question.

I have this problem: at a time when the password of the account is expired,
i can not change it because I can't log in to the account with expired
password.

How can this be solved?

2017-12-01 17:32 GMT+04:00 multiOTP <notifications@github.com>:

**Comment by multiOTP** [comment]
Since version 5.0.6.2 which is now available, multiOTP Credential Provider has a "Send an SMS code" link.

**Comment by multiOTP** [comment]
Hello @TarlanAbdullayev, please write an other issue for the "password change option".

Please note that in the next version of multiOTP open source available later this month, a new option can allow "expired password" to be accepted by the server. This will allow multiOTP to accept connection for expired password.
Of course, this is only half the way, as multiOTP Credential Provider must also be enhanced in order to support password change on the logon interface.

Regards,
