### ISSUE TITLE
case_sensitive_users BUG

### ISSUE THREAD

**Issue by vak255** [multiOTP/multiotp#23]
Hello!

An error has been detected.
When the option case_sensitive_user=0 - it is impossible to work the users whose names are in unicode UTF-8 (multibyte).
This is because in multiotp.server.php is used function "strtolower()" instead of "mb_strtolower()".
In this case, all strings are processed as ASCII, and we get the following errors:

multiotp.log:
System	Error: database file C: \ multiOTP \ users \ .db for user  does not exist

webservice\logs\error.log:
[error] 18320 11564: *162 FastCGI sent in stderr: "PHP Notice:  XML Parsing Error at 5:37 (byte index: 265). Error 9: Invalid character check sample which starts at position 225: html encoded:   < UserId > �������������< / UserId >

Please fix in next release....

PS: now problem with unicode usernames fix by setting option case_sensitive_user=1 in multiotp.ini config on server and in multiotp.ini on multiOTPCredentialProvider setup path! 

Thanks!

**Comment by multiOTP** [comment]
mb_xxx functions are now used when needed.
Thanks for the feedback.
Regards,
