### ISSUE TITLE
Password change option (for the multiOTP Credential Provider)

### ISSUE THREAD

**Issue by TarlanAbdullayev** [multiOTP/multiotp#25]
Hello, 

I have this problem: at a time when the password of the account is expired, i can not change it because I can't log in to the account with expired password. 
Is multiOTP Credential Provider support password change?

How can this be solved?

**Comment by multiOTP** [comment]
Hello,
currently multiOTP credential provider doesn't support password change.
It's on the todo list.
Best regards

**Comment by TarlanAbdullayev** [comment]
Hello,

Thanks for your answer.
And approximately when multiOTP credential provider with password change feature will be ready?

**Comment by multiOTP** [comment]
It's expected for end of March 2018

**Comment by multiOTP** [comment]
This issue has been moved to multiOTPCredentialProvider : https://github.com/multiOTP/multiOTPCredentialProvider/issues/6
