### ISSUE TITLE
Virus Alert

### ISSUE THREAD

**Issue by Jonathan-Garber** [multiOTP/multiotp#26]
W32.Trojan.Gen -- Detected by Webroot when logging in using MultiOTP
evbf3f6.tmp in Windows Temp Folder

It seems MulitOTP constantly makes .tmp files and each one gets hit by Webroot as a virus.
What in the program is causing this and how can it be resolved?

Yet if I scan the file separately Webroot says it is clean. So it only see's it as it is being made and pops it.

**Comment by multiOTP** [comment]
Hello, the multiotp.exe is a virtual appliance enclosed in on exe file using the Enigma Virtual Box (http://enigmaprotector.com/en/downloads.html), which is creating this .tmp file.
Regards

**Comment by Jonathan-Garber** [comment]
Yea, I saw that in the documentation/Wiki how the MultiOTP.exe CLI was created. I always suspected this alert is a false positive but I wanted to dig for more details here.

As the provided exec is supposedly made from the raw code here visible on GitHub there is nothing to stop the person who rolled that virtual appliance from hiding something nefarious inside it. As end users all we see is the MulitOTP.exe pre-compiled and are blindly trusting that it contains ONLY the code here on Github and is safe to use. So when anti-virus began to pop it, I began to get a bit nervous.

I recommend a section of the Wiki that explains how to add the proper files/applications to Enigma Virtual Box and create the MultiOTP.exe. This way end users can roll their own copy and know exactly what files are inside it (The ones from the public github).


When I do a test run of MultiOTP.exe without interference from any anti-virus software, it creates like 15 of these temp files. Most of them end up being 0kb but a few end up around 1.8kb. They are very small and in raw form you can see references to ntdll and some commands such as "ZwOpenFile". Then when scanned with anti-virus software (several of them) a handful pop the temp files as viruses.

So I was wondering what the content of these temp files is supposed to be.

Also note that I did send the files/github link to Webroot for analysis and they agree it is a false positive on their end. So that is further evidence that the MultiOTP.exe is clean and not dangerous.

**Comment by multiOTP** [comment]
Hello,
Enigma made a new build to avoid virus false positive, it will be used for the next build.
Regards

**Comment by Jonathan-Garber** [comment]
Good to hear it. Thanks for the update.

**Comment by multiOTP** [comment]
Please note also that the precompiled multiOTP.exe is digitally signed by our company, SysCo systemes de communication sa.
