### ISSUE TITLE
Windows 10/Defender Antimalware blocks the client/credentialprovider

### ISSUE THREAD

**Issue by mintyfield** [multiOTP/multiotp#28]
The latest versions of multiotp.exe that come from the installer of the MultiOTP Credential Provider, doesn't work after Windows 10 is updated. Excluding the executable in defender doesn't work. 
This only happens after defender is updated; before the update, right after a clean windows 10 pro installation, the program works OK

Starting multiOTP.exe rom the commandline CMD results in a warning from windows defender anti-malware and a CLI Error; _The System Cannot execute the specified program_

See also: https://www.reasoncoresecurity.com/multiotp.exe-35504ef697ab3179061bfb6f49fdd110bb287965.aspx

**Comment by mintyfield** [comment]
Actually: it is not the executable that is listed as malware.
Windows defender lists several files in the temp folder as malwae: users local temp folder %localappdata%\temp

It lists Trojan:Win32/Fuerboos.A!cl as the bad stuff

**Comment by 7845258** [comment]
similar problem here:
https://github.com/multiOTP/multiOTPCredentialProvider/issues/3

**Comment by multiOTP** [comment]
To avoid virus false positive alert, multiOTP.exe is NO more packaged in one single file using Enigma, a php folder is now included in the multiOTP folder.
A new installation file is available for multiOTPCredentialProvider.
