### ISSUE TITLE
YubicoOTP, private ID not checked?

### ISSUE THREAD

**Issue by mmuszkow** [multiOTP/multiotp#3]
Hi,
It seems that Yubikey private ID is not [imported](https://github.com/multiOTP/multiotp/blob/master/multiotp.class.php#L12123) neither [checked](https://github.com/multiOTP/multiotp/blob/master/contrib/MultiotpYubikey.php#L145). The [documentation](https://www.yubico.com/wp-content/uploads/2015/03/YubiKeyManual_v3.4.pdf) at page 33, paragraph _6.1.1 Private ID_ states that "_The verifying instance should verify this field against the expected value._"

Is there any reason for that?

**Comment by multiOTP** [comment]
Hello,
Our current beta is now implementing the optional ("should", not "must") private ID. The release will be available begin of June 2016.
Regards,
Andre
