### ISSUE TITLE
can not create qrcode 

### ISSUE THREAD

**Issue by karthik-altiscale** [multiOTP/multiotp#31]
```
[root@altiscale tmp]# multiotp -fastcreatenopin my_user
[root@altiscale tmp]# multiotp -qrcode my_user my_qrcode.png
Reply-Message := "ERROR: QRcode not created"
```

```
[root@altiscale tmp]# multiotp -version
multiOTP 5.1.0.3 (2018-02-19) [CLI]
```

**Comment by multiOTP** [comment]
Hello,
It seems that you are using a Linux edition. Which extensions are activated in your PHP installation ?
PHP GD Library **must** be activated. Please typethe following to have more information concerning this problem:
**multiotp -debug -display-log -qrcode my_user my_qrcode.png**
Best regards,

**Comment by karthik-altiscale** [comment]
Yes I am using centos.. I have already installed php-gd package 

```
# multiotp -debug -display-log -qrcode my_user my_qrcode.png

LOG 2018-03-18 06:04:24 debug Debug Debug: *parameter(s) received: -debug -display-log -qrcode my_user my_qrcode.png

LOG 2018-03-18 06:04:25 error System Error: QRcode files or folders are not available
50 *ERROR: QRcode not created

LOG 2018-03-18 06:04:25 debug Debug Debug: *Attributes sent to the RADIUS server: Reply-Message := "ERROR: QRcode not created"
Reply-Message := "ERROR: QRcode not created"
```

**Comment by multiOTP** [comment]
Hello, please be sure that  in the multiotp folder, the **qrcode** directory is present  and that it contains accessible **data** and**images** sub-folders with their content.
Regards,

**Comment by karthik-altiscale** [comment]
Sorry can you tell me where I should make sure the directories are present ??

Somewhere here ? 
```
[root@altiscale multiotp]# tree /etc/multiotp/
/etc/multiotp/
├── config
│   └── multiotp.ini
├── devices
├── groups
├── tokens
└── users
    ├── john.db
    ├── karthik.db
    ├── my_user1.db
    ├── my_user2.db
    └── my_user.db

5 directories, 6 files
```


any pointers or doc should be helpful

**Comment by multiOTP** [comment]
Hello, your multiotp.php file is probably in **/usr/local/bin/multiotp**
the qrcodes subfolder should by in **/usr/local/bin/multiotp/qrcodes**
Regards,

**Comment by multiOTP** [comment]
(the full Linux structure is described in the README.md)

**Comment by karthik-altiscale** [comment]
/usr/local/bin/multiotp is a file 
/usr/local/bin/multiotp/qrcodes  i can not create this because /usr/local/bin/multiotp/ is already a file .. 

I can't find the dir structure, can you please point me to the specific topic/title in README.md ? 

I tried to copy the qrcode directory https://github.com/multiOTP/multiotp/tree/master/qrcode to /etc/multiotp/ but still getting the same error ..  

````
[root@altiscale otp]# multiotp -debug -display-log -qrcode my_user my_qrcode.png

LOG 2018-03-18 09:20:50 debug Debug Debug: *parameter(s) received: -debug -display-log -qrcode my_user my_qrcode.png

LOG 2018-03-18 09:20:50 error System Error: QRcode files or folders are not available
50 *ERROR: QRcode not created

LOG 2018-03-18 09:20:50 debug Debug Debug: *Attributes sent to the RADIUS server: Reply-Message := "ERROR: QRcode not created"
Reply-Message := "ERROR: QRcode not created"
```

```
# ls -ld /etc/multiotp/qrcode/
drwxr-xr-x 4 root root 4096 Mar 18 08:13 /etc/multiotp/qrcode/

# ls -l /etc/multiotp/qrcode/
total 20
drwxr-xr-x 2 root root 12288 Mar 18 08:13 data
drwxr-xr-x 2 root root  4096 Mar 18 08:13 image
-rw-r--r-- 1 root root   780 Mar 18 08:13 qrHOTP.png
```

**Comment by multiOTP** [comment]
Hello, download the full packaged distribution here, it's the easiest way: https://download.multiotp.net/multiotp.zip
Regards,

**Comment by karthik-altiscale** [comment]
awesome I got it working now .. thanks a bunch .. will test with Google authenticator  
I really don't want to put them in bin directory .. may be /etc/multiotp or somehwere in /usr/local/lib .. 
```
├── qrcode
│   ├── data
│   └── image
├── templates
```
can I do that ?

**Comment by multiOTP** [comment]
Hello, you're welcome.
Put the subfolders **qrcode** and **templates** in the same folder as multiotp.php, and that's it !
Regards,
