### ISSUE TITLE
-remove-token username - returns error/token still works

### ISSUE THREAD

**Issue by Jonathan-Garber** [multiOTP/multiotp#33]
When issuing command
`multiotp.exe -remove-token USERNAME`
The command returns an error message

> Reply-Message := "ERROR: Authentication failed (and other possible unknown errors)"

When I use the "Print" option on this user, the hardware token no longer appears on this document but the user can still logon with this hardware token.

So it does not remove the token from the user.

**Comment by Jonathan-Garber** [comment]
I see what it does here...
When assigning a Token to a user, the seed of that token takes over for that user. So even though we removed the hardware token, that user still has the same seed value.

So this hardware token still works.

What needs to happen is when a token is removed from a user, the seed needs to be re-generated so they now have a new seed to associate with their OTP devices (Google Authenticator, whatever)

**Comment by multiOTP** [comment]
Hello Jonathan,
You are right, currently, the adminsitrative information is removed (the administrative link to the hardware token is removed), but a new seed is not automatically generated.
This will be done in the next release.
Thanks for your feedback, and best regards,
Andre

**Comment by Jonathan-Garber** [comment]
Also note that removing the token from the user doesn't unattribute the token either. The token.db file will still show the user attributed to the token etc.

Any status on this fix?

**Comment by multiOTP** [comment]
Hello Jonathan,
This issue is fixed in version 5.3.0.0 (https://github.com/multiOTP/multiotp/releases/tag/5.3.0.0)
Please check it on your side and close this issue if it is resolved.
Regards,
Andre
