### ISSUE TITLE
send sms from multiotp

### ISSUE THREAD

**Issue by Karls-0N** [multiOTP/multiotp#34]
Where I can find Information about format and value of files or settings device.db (/etc/multiotp/devices)?
I need use SMS Challenge Prefered for my devices.

**Comment by multiOTP** [comment]
Hello Karls,
SMS Challenge is currently implemented like this in the open source edition:
- type the username as the username, and sms as the password
- this first authentication is refused, but an SMS token is sent to the mobile phone
- retype the username and the SMS token (prefixed with a PIN or password if configured like this), and the authentication will be accepted.
Regards,
Andre
