### ISSUE TITLE
HOTP not working

### ISSUE THREAD

**Issue by sunojvijayan** [multiOTP/multiotp#4]
Hi I am trying to check HOTP generated. I am using google authenticator. I am getting this error.

failed (98 ERROR: Authentication failed (wrong token length))

Please help

**Comment by multiOTP** [comment]
Hello,
You probably forgot the prefix PIN/password.
Best regards,
Andre

**Comment by sunojvijayan** [comment]
Thanks a lot bro. It worked.

**Comment by sunojvijayan** [comment]
Good job!
