### ISSUE TITLE
Access Denied running multiotp.exe as administrator on system with SRP

### ISSUE THREAD

**Issue by ardavanhashemzadeh** [multiOTP/multiotp#42]
While running as an administrator on a machine with Software Restriction Policies I get the error "Access Denied" anytime I try to run the multiotp.exe executable. The policies restrict applications from running outside of the windows and program files folders, does multiotp.exe extract files to a temporary location?

**Comment by multiOTP** [comment]
Hello, can you tell us which version of multiotp you are using ? (you can also tell us the exe file and we will find the version from the size)

**Comment by ardavanhashemzadeh** [comment]
Hello and thank you for the quick response. I am using version 5.4.0.1, the .exe is 288KB.

**Comment by multiOTP** [comment]
Hello,
As multiOTP is using PHP, PHP will at least access to the Temp directory of the current user.
When you install the Credential Provider, multiOTP files are actually still required (as the local multiOTP could provide offline authentication).
In the future, the Credential Provider will have a "on-line" mode only which will not require multiOTP to be installed.
Regards,

**Comment by multiOTP** [comment]
No more feedback since more than two monthes. Issue closed.
