### ISSUE TITLE
Error at least one parameter ist missing

### ISSUE THREAD

**Issue by Grantig** [multiOTP/multiotp#43]
`root@debian:/usr/local/bin/multiotp# ./multiotp.php 

multiOTP 5.4.0.1 (2018-09-14), running with PHP 7.0.30-0+deb9u1 (CLI mode)
(c) 2010-2018 SysCo systemes de communication sa
http://www.multiOTP.net   (you can try the [Donate] button ;-)

Not enough parameters, type multiotp -help for information about the options.
Reply-Message := "ERROR: At least one parameter is missing"
root@debian:/usr/local/bin/multiotp`

• Copy the multiotp.php file somewhere on your server (for example in the folder /usr/local/bin/multiotp) and make it executable by chmod’ing it to +x
 • The script needs to have read/write access rights on his folder 
• Try to run it. It should display the help page with version information and syntax usage

Debian 9  in VirtualBox under Win10 Pro

**Comment by multiOTP** [comment]
Hello,
As displayed in the answer (Not enough parameters, type multiotp -help for information about the options) you have now to type multiotp -help for information about the options:
**` ./multiotp.php -help`**
Regards,
Andre
