### ISSUE TITLE
mulitotp running as a webservice crashes 

### ISSUE THREAD

**Issue by umapati** [multiOTP/multiotp#44]
we are using multiotp 5.0.3.7 on php ver 7 on a windows 2012 R2 server with 8GB RAM.

when running as a webservice, the php-cgi seems to consume more than 50% CPU and crashes when the load hits about 12 TPS. 

Any idea how to go about improving the performance of the webservice.

**Comment by multiOTP** [comment]
Hello,
we strongly suggest that you run the HyperV virtual appliance in your Windows 2012 server.

Have a great day.
