### ISSUE TITLE
What is using NSSM.EXE

### ISSUE THREAD

**Issue by Jonathan-Garber** [multiOTP/multiotp#45]
What part of MultiOTP relies on nssm.exe in the webservice folder? I cannot seem to find any scripts or code that uses it. Is this just leftovers?

**Comment by multiOTP** [comment]
**webservice_install.cmd** relies on nssm in order to install Nginx as a service. regards.

**Comment by Jonathan-Garber** [comment]
I see it now, I scanned files for "nssm.exe" and it returned nothing. I see the command now is just "nssm"
Thanks.
