### ISSUE TITLE
Windows 7 Pro - Error msvcp140.dll is missing

### ISSUE THREAD

**Issue by Jonathan-Garber** [multiOTP/multiotp#46]
Freshly installed copy of windows 7 professional and 5.4.0.1 credential provider. Windows throws an error when it attempts to load the provider.

```
This program can't start because msvcp140.dll is missing
```

I have not done any further testing yet - just wanted to post the issue first. After this message pops up twice, it reverts to the default provider and I can logon normally.

**Comment by Jonathan-Garber** [comment]
When I installed VC++ 2015 Redistributables the error was resolved. So the credential provider for 5.4.0.1 doesn't work out of the box on Windows 7 Pro unless it is installed. Just a heads up.

**Comment by multiOTP** [comment]
The official 5.4.1.6 installer executable includes now VC++ 2017 redistributables.
