### ISSUE TITLE
Default password 1234

### ISSUE THREAD

**Issue by M1k13** [multiOTP/multiotp#48]
Hey,

I use Centos 7 and successfully installed multiotp. When i start it up in the web-browser it says Username: admin (default is admin) User NOT authenticated 
Password: (default is 1234).

I type in the password but it does'nt work it just disappears.

Kind regards,

**Comment by multiOTP** [comment]
What do you mean by "it just disappears" ? What disappears ? Do you have something in the log file ?
Regards,
Andre

**Comment by M1k13** [comment]
I enter a password and press ‘login’ and it disappears. Also I can’t  change the user its stuck on admin. When I empty the cache and reload the page I’m logged in…. until I log out. After that it does the same thing( disappearing password).

My nginx error log doesn’t say anything same for my php-fpm. So I guess that is fine...

**Comment by M1k13** [comment]
Ah I found a error… weird since it didn’t give an error at first.

[error] 1179#0: *33 open() "/var/www/totp/md5.js" failed (2: No such file or directory), client: 10.5.112.71, server: fqdn, request: "GET /md5.js HTTP/1.1", host: “fqdn", referrer: "http://fqdn/"

**Comment by multiOTP** [comment]
File has been added in the repository.
