### ISSUE TITLE
Multiotp config errors

### ISSUE THREAD

**Issue by p-oleg99** [multiOTP/multiotp#49]
Hi! 

got this error

PHP Fatal error:  Uncaught Error: Call to undefined function mb_strpos() in /etc/multiotp/multiotp.php:69342
Stack trace:
#0 /etc/multiotp/multiotp.php(69418): get_script_dir()
#1 {main}
  thrown in /etc/multiotp/multiotp.php on line 693

PHP Version
PHP 7.1.24 (cli) (built: Nov  7 2018 18:45:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

=====
solved by update to 7.2.12

**Comment by p-oleg99** [comment]
But we  have one more issue, I'd like to add users group and get fatal error

./multiotp.php -config  ldap-in-group='g_vpn_1'
PHP Fatal error:  Uncaught Error: Call to undefined function bcmod() in /etc/multiotp/multiotp.php:21828
Stack trace:
#0 /etc/multiotp/multiotp.php(18987): bigdec2hex('59552162542884')
#1 /etc/multiotp/multiotp.php(6980): Multiotp->CreateGroup('', 'g_vpn_level_12', 'g_vpn_level_12')
#2 /etc/multiotp/multiotp.php(70666): Multiotp->SetLdapInGroup('g_vpn_level_12')
#3 {main}
  thrown in /etc/multiotp/multiotp.php on line 21828

**Comment by multiOTP** [comment]
Hello,
You have to activate the mbstring extension in PHP in order to have the mb_strpos() function declared.
For the bcmod() function, the BCmath support must be enabled.
What is your environnement ?
Regards,

**Comment by p-oleg99** [comment]
hello


radiusd: FreeRADIUS Version 3.0.13, for host x86_64-redhat-linux-gnu, built on May 16 2018 at 06:33:35
FreeRADIUS Version 3.0.13
Copyright (C) 1999-2017 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGH


multiOTP 5.4.0.1 (2018-09-14) [CLI]
19 *INFO: Requested operation successfully done

PHP 7.2.12 (cli) (built: Nov  6 2018 16:40:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

AD - Win 2016 r2

CentOS Linux release 7.5.1804 (Core?


________________________________

**Comment by p-oleg99** [comment]
php -m | grep mbstring
mbstring

**Comment by multiOTP** [comment]
Hello,

For the BCmath support, try this on your Red Hat installation:
yum install php-bcmath

If it didn't work, try this:
yum install php72-php-bcmath

Regards,

Andre

**Comment by p-oleg99** [comment]
installed

Package php72-php-bcmath-7.2.12-1.el7.remi.x86_64 already installed and latest version
Nothing to do
]# ./multiotp.php -config ldap-in-group='g_vpn_1'
PHP Fatal error:  Uncaught Error: Call to undefined function bcmod() in /etc/multiotp/multiotp.php:21828
Stack trace:
#0 /etc/multiotp/multiotp.php(18987): bigdec2hex('59562142341914')
#1 /etc/multiotp/multiotp.php(6980): Multiotp->CreateGroup('', 'g_vpn_1', 'g_vpn_1')
#2 /etc/multiotp/multiotp.php(70666): Multiotp->SetLdapInGroup('g_vpn_1')
#3 {main}
  thrown in /etc/multiotp/multiotp.php on line 21828

**Comment by multiOTP** [comment]
Please restart your server, and check the result of phpinfo().
Is BCMath support enabled ?

**Comment by multiOTP** [comment]
I cannot diagnose why your installation don't have BCmath installed.
If it still didn't work, as a quick fix, please try to add the following at the beginning of the multiotp.php file (just after the <?php tag) :
```
/***********************************************************************
 * Name: bcmod
 * Short description: description: Patch for long2ip
 *
 * Creation 2018-11-15
 * Update   2018-11-15
 * @version 1.0.0
 * @author  Adapted from http://php.net/manual/en/function.bcmod.php#38474
 *
 * @param   string  $dividend  dividend
 *          string  $divisor   divisor
 * @return  string             modulus as a string
 ***********************************************************************/
if (!function_exists('bcmod')) {
    function bcmod($dividend, $divisor) {
        // how many numbers to take at once? carefull not to exceed (int)
        $take = 5;    
        $mod = '';
        $div = $dividend;
        do {
            $a = (int)$mod.substr( $div, 0, $take );
            $div = substr( $div, $take );
            $mod = $a % $divisor;   
        } while ( strlen($div) );

        return (int)$mod;
    }
}
```

Regards,

Andre

**Comment by p-oleg99** [comment]
we installed php-bcmath and it works now, thanks

**Comment by multiOTP** [comment]
Good to know, thanks for the feedback.
Regards,
