### ISSUE TITLE
user without 2fa login failure

### ISSUE THREAD

**Issue by reinethernal** [multiOTP/multiotp#50]
I'm trying ti login with user without 2FA. It's enabled in OTP server, passes login option, but when i try to login receive ERROR: Authentication failed (wrong token length)

And here's a question. Is there any way to make users choose an option - how to login - by 2fa with token or by a standart user@domain\password?

**Comment by multiOTP** [comment]
Hello, please be sure that the prefix is not enabled for this user.
What is the goal to be able to choose between 2FA or not ? In this case, 2FA will never be used !!!
Regards,

**Comment by multiOTP** [comment]
Please note that during the Credential Provider Setup, you can activate 2FA only for Remote Desktop (RDP).

**Comment by reinethernal** [comment]
Hello again. Prefix is not enabled.
I want domain users that have permissions to log in at that server (server 1 for example) have an ability to log in as usual. With their login\password. without pin, or 2fa.

**Comment by reinethernal** [comment]
Thx, i'll try and report after
