### ISSUE TITLE
How to configure only local user with otp-logon

### ISSUE THREAD

**Issue by fx201314** [multiOTP/multiotp#51]
How to configure only local user with otp-logon，and ldap user without otp-logon？
Thanks！

**Comment by multiOTP** [comment]
Hello,
you need to set the ldap-default-algorithm to without2fa, this way the ldap synced users will have a without2fa token.
Make sure to use at least version 5.3.0.3
Regards

**Comment by fx201314** [comment]
> Hello,
> you need to set the ldap-default-algorithm to without2fa, this way the ldap synced users will have a without2fa token.
> Make sure to use at least version 5.3.0.3
> Regards

Nice!
Thank you very much!
