### ISSUE TITLE
Migrate users

### ISSUE THREAD

**Issue by MHDMAM** [multiOTP/multiotp#52]
First, thanks for this great project, it was a help for me in past year.

Well, I'm using Hotp and Totp only and now planing to move to it to be part of my Nodejs project.

I'm trying to migrate the users from multiotp database to my project database. I understand that the token_seed is encrypted. 
I tried to look into the code, but I don't really understand PHP code.

Could you please help showing the encryption & decryption way.

Thanks.

**Comment by multiOTP** [comment]
Hello,
you can backup your configuration in clear text using this command

`multiotp -backup-config "*CLEAR*" filePathAndName`

Regards
