### ISSUE TITLE
sql table setup incomplete in 5.4.1.7

### ISSUE THREAD

**Issue by matt-gnu** [multiOTP/multiotp#53]
Just checked out multiotp and had issues with setup of the SQL database on Debian stable with `Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1`

Initialization missed creation of 2 columns in the multiotp_users table: `user` and `attributed_tokens`.
the first makes adding users impossible, the latter gives errors after trying to login.
After a simple alter table and selecting `VARCHAR(255)` for both, multiotp seems to work.
When debugging, I found the error:

```
MariaDB [multiotp]> ALTER TABLE multiotp_users ADD INDEX attributed_tokens ( `attributed_tokens` );
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
```

Due to UTF8 encoding in the storage backend, the index needs to be shortened by some bytes.
```
ALTER TABLE multiotp_users ADD INDEX ( `attributed_tokens`(150) );
```
is accepted here. But the syntax `$this->_sql_tables_index['users']    = '*attributed_tokens*desactivated*locked*user*';` does not support adding these limits, so I can't provide a pull-request, but added the indexes myself manually.

Short update: after checking all other tables against the schema, as expected *all* indexed columns were not created automatically.

**Comment by multiOTP** [comment]
Hello,
Thanks for the detailled issue. We will provide a patch.
Regards,
Andre

**Comment by multiOTP** [comment]
Should be working in the latest release.
