### ISSUE TITLE
multiple AD groups

### ISSUE THREAD

**Issue by alexmateescu** [multiOTP/multiotp#56]
hi.

 i have multiOTP setup and working fine, however i have a small issue in regards to the fact that my VPN users are split multiple AD groups. 

What i am trying to achieve is to prevent a user that is assigned group X to connect to the profile assigned to group Y. 

On the Cisco ASA i have secondary authnetication which is set to multiOTP and primary to AD and tied to the specific groups. 

Is there any way to achieve this?

**Comment by multiOTP** [comment]
No feedback after 18 days, closed.
