### ISSUE TITLE
open_basedir & windows

### ISSUE THREAD

**Issue by PeuX** [multiOTP/multiotp#57]
Hi,
thank for your great work.

We found out that if you use multiOTP on a Windows server with the open_basedir directive set in the php.ini, you got the error :

> Warning: file_exists(): open_basedir restriction in effect. File(/dev/shm/) is not within the allowed path(s): (C:\inetpub\wwwroot\PROJECT\;C:\Windows\Temp\;/dev/shm/) in C:\inetpub\wwwroot\PROJECT\...\Multiotp\multiotp.class.php on line 1000

Regards,

**Comment by multiOTP** [comment]
Hello,
Thanks for the feedback. /dev/shm should not be used under Windows. This will be corrected in the next release.
Regards,

**Comment by multiOTP** [comment]
The next release will be available mid-May 2019.
Regards,

**Comment by multiOTP** [comment]
Version 5.6.1.5 has been released and this issue is fixed.
