### ISSUE TITLE
Same Subnet MultiOTP Bypass

### ISSUE THREAD

**Issue by breezytm** [multiOTP/multiotp#58]
HI, 

Request feature to add the ability not to require a token if endpoint is in the same subnet as the server/desktop attempted to RDP to. 

I would like to be prompt only when I am attempting to access the computer where OTP is installed from a remote location but not when I am on the same network as it is.

**Comment by multiOTP** [comment]
This is more a **multiOTP Credential Provider** feature than a multiOTP "server" one.
Depending the configuration of the subnets in an organization, it's also common that the network devices (including multiOTP) are not in the same subnet as the desktop machines, which will not help too much.
And currently, I don't think there is a common way to extract the real IP address of the endpoint. The endpoint IP address is the local address of the endpoint, and this will be a problem. See this:

----------

Endpoint IP : **192.168.1.17** -> RDP with NAT to 5.6.7.8
Local external IP (through gateway): 1.2.3.4

Remote external IP : 5.6.7.8 (NAT port 3389 to 192.168.1.1
Remote local IP of the server : **192.168.1.1** (detect the IP address of the endpoint (192.168.1.17) as in the same subnet which is NOT the case.

----------

Amy suggestion ?

Regards,

Andre

**Comment by multiOTP** [comment]
Issue closed as it is related to multiOTP Credential Provider (and not multiOTP), and no feedback has been given the last two weeks. For any technical suggestions, please re-open an issue in the multiOTP Credential Provider project (https://github.com/multiOTP/multiOTPCredentialProvider).
Thx

**Comment by mcolatosti** [comment]
I believe the individual was looking for the ability to configure the windows-based multiOTP client's RDP exclusion to be augmented to support source IP based exclusions for requiring multiOTP auth.  I could use this feature too but its not a MultiOTP server feature request but a request to modify the special Windows client project.  Who knows if the source IP address of the client making the RDP connection is even potentially exposed to the way the OTP client is interacting with the RDP auth process?

**Comment by multiOTP** [comment]
Hello, From a Credential Provider implementation, it's *NOT* possible do detect the public IP address used to make a specific RDP connection. Only the internal IP address of the client initiaing the connection can be detected.
Best regards,
