### ISSUE TITLE
ldap-users-sync delete users

### ISSUE THREAD

**Issue by mschaap204** [multiOTP/multiotp#59]
Hi,

I have a question about the -ldap-users-sync option.

I've setup a ldap connection with a Microsoft AD service which works fine.

Now I have noticed when I delete a user in Active Directory and run -ldap-users-sync the user is deactivated in multiotp.

Is there a reason why the user is deactivated instead of deleted?

And is it possible in the future to create some sort of option to delete users when they are deleted in the ldap-server instead of disabling them?

Thank you.

Best regards,
Mark

**Comment by multiOTP** [comment]
Hello Mark,

This is a feature and not a bug :-)

The problem is that when you delete a user, if you have to re-create it, the seed of the token will be a new one, and you will to communicate it to the user.

Imagine that you have a big Active Directory with 2 or 3 replicated AD server, and for any stupid reason, some users are missing in one of the AD servers, which is the one used for synchronizsation.

In this case, if the usera are deleted in multiOTP, when the AD server is fixed, you will have to distribute the new created tokens to these users.

The same if you accidentally remove some users from the AD sync group(s), if you have to add them back, you will have to distribute the new created tokens.

Regards,

Andre

**Comment by mschaap204** [comment]
Hi Andre,

Thanks for your reply.

I understand the reasons why this is a feature.

Is there a possibility  to make this configurable in a future release?
Now when I delete a user in AD/LDAP, I have to manually delete the user.

Thank you.

Best regards,
Mark

**Comment by multiOTP** [comment]
Hello Mark,
I would suggest the following option:
- sync-delete-secure-retention-days : Delete unexisting synchronised AD/LDAP users after X days (0 = never)

What do you think ?

Regards,
Andre

**Comment by mschaap204** [comment]
Hi Andre,

Sounds like a perfect option.

Best regards,
Mark

**Comment by arddg** [comment]
After using multiOTP for some time I'm completely agree with @mschaap204. This option would be very helpful! Is it still planned?

**Comment by multiOTP** [comment]
Hello, this will be published next week.
Have a good day.

**Comment by mschaap204** [comment]
Greetings,

Hope you are doing well.

Is this option still to be build in?


Thank you.

Kind regards,
Mark Schaap

**Comment by multiOTP** [comment]
Hello Mark,
This option is implemented in version 5.8.x which is on final testing on several installations since two weeks.
Regards,
Andre

**Comment by mschaap204** [comment]
Hello Andre,

Thanks for your quick reply.

Is there any indication when the new version will be released?

Kind regards,
Mark Schaap

**Comment by multiOTP** [comment]
Hello,
Which "distribution" of the version are you talking about ?
OVA Virtual appliance, Hyper-V virtual appliance, Raspberry Pi image, or simply the source code ?
Source code of version 5.,8.0.3 should be published the 2. October 2020.
Appliances and Raspberry Pi images should be available 8. October 2020.
Regards,

**Comment by multiOTP** [comment]
Please note that the parameter is *-sync-delete-retention-days*

**Comment by mschaap204** [comment]
The source code.

**Comment by mschaap204** [comment]
Greetings Andre,

Hope you are doing well.

Is it correct that the new version (5.8.x) has not been released yet?

Thank you.

Kind regards,
Mark

**Comment by multiOTP** [comment]
Hello,
the full source code update on github will be available on friday 12. February.
Best regards

**Comment by multiOTP** [comment]
Since version 5.8.0.2, this option is now integrated.
