### ISSUE TITLE
Visual difference local users vs ldap users

### ISSUE THREAD

**Issue by mschaap204** [multiOTP/multiotp#60]
Hi,

I have a question about the administration interface.

When I've synced users from a LDAP/AD the are automatically created in MuliOTP.
After that there is still a possibility to manually create users.

If I have done that there is no visual difference between users that are manually created or automatically created by sync.

Is it possible to create a visual difference between those users?
(for example other colour, additional text)

Thank you,

Best regards,
Mark

**Comment by multiOTP** [comment]
Hello Mark,
Actually, this feature is not available in the open source edition, but it is not hard to implement it, I put it on the whishlist for the next open source release.
Regards,
Andre

**Comment by mschaap204** [comment]
Hi Andre,

Thanks for your reply.
I'll await future release then.

Thank you.


Best regards,
Mark

**Comment by multiOTP** [comment]
A better visual difference is now available : (green=AD/LDAP synced, orange = delayed, red=locked)
