### ISSUE TITLE
Multiotp VirtualBox Appliance : WebService Activation

### ISSUE THREAD

**Issue by gurilem** [multiOTP/multiotp#63]
Hi.
I was succesfully installed the MultiOtp Virtual Box Appliance, and working great to enhanced Mikrotik PPTP VPN authentication.
The next step, I try to use it to enhanced Wordpress login using webservice plugins, but I still confuse how to activate the WebService on MultiOTP Virtual Box.

I read about we have to configure the folder of multiotp.server.php, but I still have no clue how to do it.

Best Regards

**Comment by multiOTP** [comment]
Hello Gurilem,
What is the distribution of multiOTP that you have exactly installed please ?
Regards,
Andre

**Comment by multiOTP** [comment]
If the web interface is working, the WebService should work too, as it is served by the same instance.
Regards,

**Comment by gurilem** [comment]
> Hello Gurilem,
> What is the distribution of multiOTP that you have exactly installed please ?
> Regards,
> Andre

Multiotp opensouce virtual appliance

**Comment by gurilem** [comment]
> If the web interface is working, the WebService should work too, as it is served by the same instance.
> Regards,

the web interface is working.  if you say that it served by the same instance, mean the port of webservice is 80, am i right ?.

**Comment by multiOTP** [comment]
Hello,
The open source virtual appliance webservice is available both on port 80 and 443 (SSL). SSL should opf course be preferred.
Regards,
Andre
