### ISSUE TITLE
Time to authenticate

### ISSUE THREAD

**Issue by qzem** [multiOTP/multiotp#66]
We use MultiOTP on domain computers. Our scenartio is Password + OTP. I wonder if it is possible to speed up authentication process? It takes 20-25 seconds for system to let you in after typing OTP. It also takes very long time if you mistype OTP, to receive an error. On the other hand if I mistype domain password it takes less time to acknowledge that.

**Comment by multiOTP** [comment]
Hello, what is your exact configuration ?
(exact version of multiOTP Credential Provider, client/server configuration with local cache, directory structure of the multiOTP folder in C:\Program Files (x86)\multiOTP, ...)
Usually, it takes up to 3 seconds to authenticate, no more. Is there something special written in the log file multiotp.log ?
Regards,
Andre

**Comment by qzem** [comment]
We are using multiOTP 5.4.1.6 client and server. Client is installed in C:\Program Files (x86)\multiOTP\ and server is install on C:\multiotp_5.4.1.6\... I have attachemd my configuration, I have only masked password hash, changed usernames and domain name.

Log doesn't show anything special. Should I enable some specific debugging actions?

[multiotp_conf.txt](https://github.com/multiOTP/multiotp/files/3650897/multiotp_conf.txt)

**Comment by multiOTP** [comment]
According to your configuration file, it looks like you have defined two ldap_domain_controllers. Can you make sure that the first server is available and responding correctly ?

**Comment by qzem** [comment]
That is strange. Both controllers are up and running. But I've tried now for the skae of testing, and removed one from configuration file, and authentication is now much faster.

**Comment by multiOTP** [comment]
Ok, thanks for the feedback.
Regards,
