### ISSUE TITLE
Need to enter password twice 

### ISSUE THREAD

**Issue by jwiwe** [multiOTP/multiotp#67]
Hi.

When we are using the multiOTPCredentialProvider on a remote desktop 2016 server using AD credentials, we need to enter the username and password on the client (NLA), and when connected the password and OTP have to be entered.
I know it is a problem with NLA, but have seen other OTP solutions where the OTP prompt showen i a seperate window after AUTH and before load of user data. is it possible with multiOTP?

**Comment by multiOTP** [comment]
Hello,
You are probably talking about ADFS MFA integration, but that means you will have to install and configure the ADFS service in your domain.
