### ISSUE TITLE
Use of MySQL in enterprise environment 

### ISSUE THREAD

**Issue by sunojvijayan** [multiOTP/multiotp#7]
Hi,

We are anticipating challenges in using MySQL in the enterprise environment because of the lack of professional support and HA/DR capability in the community version. Any idea on how to go about? Does MultiOTP have a support for MS-SQL?

**Comment by multiOTP** [comment]
Hello,

multiOTP Enterprise is a commercial integrated virtual appliance available for VMWare or Hyper-V, with master-slave HA support between two virtual appliances (it's not a virtual IP, it's two appliances, one master, one slave, so you can put them in two different subnets). multiOTP Enterprise includes everything in its virtual appliance, you don't need anything more to be installed. Accounts can be set manually and/or synchronised by AD/LDAP on a defined scheduled interval.

A full functional version of multiOTP Enterprise will be available to download with a free one user licence on 31. August. You will be able to use everything, but only one enabled account will be authorized.

The community version of multiOTP doesn't has support for MS-SQL.

Bests regards,

Andre

**Comment by sunojvijayan** [comment]
Hi,

1. As per your last response, does it mean the enterprise version supports MS-SQL server as its backend DB instead of MySQL?
2. Any other limitation on number of users supported or license fee for the community version?
3. Who do we get in touch with for the licensing of Pro version?

**Comment by multiOTP** [comment]
Hello,

1. MySQL Enterprise is an all inclusive (Linux based) virtual appliance, the backend is not available from outside the virtual appliance (no MS-SQL is inside).
2. multiOTP community edition doesn't have any limitation on number of users, and no fee
3. For your request about Pro and Enterprise Edition, you can send an email to info@multiotp.com

Best regards,

Andre
