### ISSUE TITLE
504 Gateway Time-out nginx/1.12.0

### ISSUE THREAD

**Issue by prfraczek** [multiOTP/multiotp#72]
I am having problem to run server on any windows hyper-v clients (mainly Windows Server 2008-16)
Is there any additional library required to be installed? It shows 504 Gateway Time-out nginx/1.12.0

**Comment by multiOTP** [comment]
Hello,
As nginx is calling php code, and PHP interpreter is compiled using Visual C++, you should install the redistribuable Visual C++ components.
https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads
Regards,
