### ISSUE TITLE
Initial configuration

### ISSUE THREAD

**Issue by swood** [multiOTP/multiotp#74]
Hello.

Firstly, thank you for your job and product. It's amazing!
However, I have several questions about the configuration. I hope I just didn't find it and you could lead me in the right way.

I would like to use Multiotp as a second factor for my exists Radius installation. The backend for Radius is MySQL and the password hashed into MD5. 

I tried to configure Multiotp as a second-factor auth provider, and I faced with the weird problem:
>LOG 2019-12-18 19:02:46 warning (user jon_snow_in_black) User *(authentication typed by the user is 6 chars long instead of 10 chars)

I didn't change the configuration much more from the default, except the backend - it's MySQL.

In the end, I have the last question. During the initialisation I have next error message:
>LOG 2019-12-18 18:11:14 error System Error: SQL query error Unknown column 'encryption_hash' in 'field list' INSERT INTO `multiotp_config` (`encryption_hash`,`actual_version`,`admin_password_hash`,`anonymous_stat`,`anonymous_stat_last_update`,`anonymous_stat_random_id`,`attributes_to_encrypt`,`auto_resync`,`backend_encoding`,`backend_type`,`backend_type_validated`,`cache_data`,`cache_ldap_hash`,`case_sensitive_users`,`clear_otp_attribute`,`console_authentication`,`create_host`,`create_time`,`debug`,`default_algorithm`,`default_dialin_ip_mask`,`default_user_group`,`default_request_ldap_pwd`,`default_request_prefix_pin`,`demo_mode`,`developer_mode`,`display_log`,`domain_name`,`email_admin_address`,`encode_file_id`,`encryption_key_full_path`,`failure_delayed_time`,`group_attribute`,`hash_salt_full_path`,`issuer`,`language`,`last_sync_update`,`last_sync_update_host`,`last_update`,`last_update_host`,`ldap_expired_password_valid`,`ldap_account_suffix`,`ldap_activated`,`ldap_base_dn`,`ldap_bind_dn`,`ldap_cache_folder`,`ldap_cache_on`,`ldap_cn_identifier`,`ldap_default_algorithm`,`ldap_domain_controllers`,`last_failed_white_delay`,`ldap_group_attribute`,`ldap_group_cn_identifier`,`ldap_users_dn`,`ldap_hash_cache_time`,`ldap_in_group`,`ldap_language_attribute`,`ldap_network_timeout`,`ldap_port`,`ldap_recursive_cache_only`,`ldap_recursive_groups`,`ldap_server_password`,`ldap_server_type`,`ldap_ssl`,`ldap_synced_user_attribute`,`ldap_time_limit`,`ldaptls_reqcert`,`ldaptls_cipher_suite`,`log`,`max_block_failures`,`max_delayed_failures`,`max_event_resync_window`,`max_event_window`,`max_time_resync_window`,`max_time_window`,`multiple_groups`,`ntp_server`,`overwrite_request_ldap_pwd`,`radius_error_reply_message`,`radius_reply_attributor`,`radius_reply_separator_hex`,`radius_tag_prefix`,`scratch_passwords_digits`,`scratch_passwords_amount`,`self_registration`,`server_cache_level`,`server_cache_lifetime`,`server_secret`,`server_timeout`,`server_type`,`server_url`,`sms_api_id`,`sms_basic_auth`,`sms_content_encoding`,`sms_content_success`,`sms_digits`,`sms_encoding`,`sms_ip`,`sms_message_prefix`,`sms_method`,`sms_no_double_zero`,`sms_originator`,`sms_password`,`sms_port`,`sms_provider`,`sms_send_template`,`sms_status_success`,`sms_timeout`,`sms_url`,`sms_userkey`,`smtp_auth`,`smtp_password`,`smtp_port`,`smtp_sender`,`smtp_sender_name`,`smtp_server`,`smtp_ssl`,`smtp_username`,`sql_server`,`sql_username`,`sql_password`,`sql_database`,`sql_schema`,`sql_config_table`,`sql_cache_table`,`sql_devices_table`,`sql_groups_table`,`sql_log_table`,`sql_stat_table`,`sql_tokens_table`,`sql_users_table`,`syslog_facility`,`syslog_level`,`syslog_port`,`syslog_server`,`tel_default_country_code`,`timezone`,`token_serial_number_length`,`token_otp_list_of_length`,`verbose_log_prefix`,`challenge_response_enabled`,`sms_challenge_enabled`,`text_sms_challenge`,`text_token_challenge`) VALUES ('99CCFC0D033729754B6BB4832FE786A1','5.6.1.5','','1','0','','','1','UTF-8','mysql','1','0','1','0','','0','radius-2fa-test','1576600077','1','totp','','','1','1','0','0','1','','','0','','300','Filter-Id','','multiOTP','en','0','','1576689074','radius-2fa-test','1','','0','','','tempdir','1','sAMAccountName','totp','','60','memberOf','cn','','604800','','preferredLanguage','10','389','0','1','','1','0','','30','auto','auto','0','6','3','10000','100','90000','600','0','pool.ntp.org','1','1',' += ','2c','','6','10','1','1','15552000','ENC:dGx9cn5qeFV7fFJ5RGR/cGd4:ENC','5','xml','','','0','','','6','','','%s is your SMS-Code','','0','multiOTP','','','','','','180','','','0','','25','','','','0','','127.0.0.1','multiotp','ENC:Q0ZAeEpBQEJaaUdAeHBHGVROUiU=:ENC','multiotp','','multiotp_config','multiotp_cache','multiotp_devices','multiotp_groups','multiotp_log','multiotp_stat','multiotp_tokens','multiotp_users','7','5','514','','','Europe/Zurich','12','6','','0','0','Please enter the code received on your mobile phone','Please enter the code displayed on the token')

The table in MySQL doesn't have mentioned field, version of Multiotp is last: 5.6.1.5.

**Comment by multiOTP** [comment]
Hello Swood,
This is because the user jon_snow_in_black has prefix pin enabled, and your are only typing the OTP without the prefix PIN first.
Please type the Prefix PIN first, or disable Prefix PIN for this user.
Regards,

**Comment by MatthewMunro** [comment]
Hi

I am seeing a similar error as described above.  The required pin is turned off `default_request_prefix_pin=0` as defined within the config file `/etc/multiotp/config/multiotp.ini`.

All my user details are being synchronised with Microsoft Active Directory using `multiotp -debug -display-log -ldap-users-sync`.

An example of an user's details within multiOTP are shown below.

Though when I do not use a database (say `backend_type=files`) all functionality works as expected.

Wondering if you have any other suggestions I could try?

Thank you in advance.

Matthew

```
multiotp -user-info auser
   Information for user: auser
                 Locked: no
              Activated: yes
   AD/LDAP synchronized: yes
      Prefix pin needed: no
            Description: auser
                  Email: auser@adomain.com
           Mobile phone: 
                  Group: OTP
   Language (inherited): en
              Algorithm: hotp
             OTP digits: 6
    Next token position: 0
19 *INFO: Requested operation successfully done
```

**Comment by swood** [comment]
By the way, I wrote my own backend for 2-factor authorisation:
https://github.com/swood/radius-otp

Unfortunately, I can't configure multiotp in my case.

**Comment by multiOTP** [comment]
> 
> 
> Hi
> 
> I am seeing a similar error as described above. The required pin is turned off `default_request_prefix_pin=0` as defined within the config file `/etc/multiotp/config/multiotp.ini`.
> 
> All my user details are being synchronised with Microsoft Active Directory using `multiotp -debug -display-log -ldap-users-sync`.
> 
> An example of an user's details within multiOTP are shown below.
> 
> Though when I do not use a database (say `backend_type=files`) all functionality works as expected.
> 
> Wondering if you have any other suggestions I could try?
> 
> Thank you in advance.
> 
> Matthew
> 
> ```
> multiotp -user-info auser
>    Information for user: auser
>                  Locked: no
>               Activated: yes
>    AD/LDAP synchronized: yes
>       Prefix pin needed: no
>             Description: auser
>                   Email: auser@adomain.com
>            Mobile phone: 
>                   Group: OTP
>    Language (inherited): en
>               Algorithm: hotp
>              OTP digits: 6
>     Next token position: 0
> 19 *INFO: Requested operation successfully done
> ```

Hello Matthew,
When you set the backend to a database, you cannot change option in the multiotp.ini file anymore! You have to change the options using the command line, as the options are noe stored in the database !
Regards,

**Comment by MatthewMunro** [comment]
> By the way, I wrote my own backend for 2-factor authorisation:
> https://github.com/swood/radius-otp
> 
> Unfortunately, I can't configure multiotp in my case.

Hi swood

Thanks for your reply and letting me know of your work.

Sorry to hear you did not manage to get multiOTP to work.. Though good work managing to create your OTP!

Unfortunately I require a solution that is quite feature rich.  For example, synchronising users with a Microsoft Active Directory.

Thanks again.

Matthew

**Comment by MatthewMunro** [comment]
> > Hi
> > I am seeing a similar error as described above. The required pin is turned off `default_request_prefix_pin=0` as defined within the config file `/etc/multiotp/config/multiotp.ini`.
> > All my user details are being synchronised with Microsoft Active Directory using `multiotp -debug -display-log -ldap-users-sync`.
> > An example of an user's details within multiOTP are shown below.
> > Though when I do not use a database (say `backend_type=files`) all functionality works as expected.
> > Wondering if you have any other suggestions I could try?
> > Thank you in advance.
> > Matthew
> > ```
> > multiotp -user-info auser
> >    Information for user: auser
> >                  Locked: no
> >               Activated: yes
> >    AD/LDAP synchronized: yes
> >       Prefix pin needed: no
> >             Description: auser
> >                   Email: auser@adomain.com
> >            Mobile phone: 
> >                   Group: OTP
> >    Language (inherited): en
> >               Algorithm: hotp
> >              OTP digits: 6
> >     Next token position: 0
> > 19 *INFO: Requested operation successfully done
> > ```
> 
> Hello Matthew,
> When you set the backend to a database, you cannot change option in the multiotp.ini file anymore! You have to change the options using the command line, as the options are now stored in the database (check your database content).
> Regards,

Hi

Thanks for your reply.

I can see the config within the DB in `multiotp_config` table.  The `default_request_prefix_pin` has a value of `0`.

Though I think this issue relates to the another issue I raised [#86](https://github.com/multiOTP/multiotp/issues/86). As when I change the `varchar(255)` to say `varchar(150)` and re-initialize the backend the above error is not shown.  Though I notice that there is a column `multiotp_config`.`encryption_hash`.

I have a simple script that uses the CLI to change the config and can be seen in the database whenever a change has been made.

Now I am trying to add and validate a user's OTP.  (To note the `default_request_ldap_pwd` value is set to `0` in the `multiotp_config` table.) I when I try to add two OTPs for an user (with valid OTP numbers):

```
multiotp -resync auser 123456 654321
```

I receive this message from the command line `Reply-Message := "ERROR: Authentication failed (and other possible unknown errors)"`.  When I try using the `Resync` through the Web interface the error is shown within the `multiotp_log` table `Error: authentication failed for user auser`.

I am wondering if you can help?

Thanks

Matthew

**Comment by multiOTP** [comment]
Hello,
I don't really undertand what you are trying to do. The _resync_ command is used to sync a user token. For example if your hotp token was used before by another user, during the resync process, multiOTP will try arround 10'000 codes in order to find the token position.

When using resync, you need to enter two unused consecutive codes.

Are trying to resync or to add a user ?

Best regards

**Comment by multiOTP** [comment]
The related issue #86 has been fixed and closed.
Regards,
