### ISSUE TITLE
Vulnerability (cookie attributes in commercial releases)

### ISSUE THREAD

**Issue by karkaaa** [multiOTP/multiotp#75]
Hello,

OpenVAS scanner find this vulnerability:
1. CRITICAL: OID:1.3.6.1.4.1.25623.1.0.15640 (Gain a shell remotely)
2. MEDIUM: OID:1.3.6.1.4.1.25623.1.0.105925 (Web application abuses)
3. LOW: OID:1.3.6.1.4.1.25623.1.0.80091

When will be fixed?

FW ver.: multiOTP 5.6.1.5
Model name: multiOTP Enterprise 501V

**Comment by multiOTP** [comment]
Hello,
thanks for the info. We will have a look and keep you posted.

Have a nice day.

Yann

**Comment by multiOTP** [comment]
It seems to be false positive, but we will further investigate in order to remove also false positive alertes.
regards,

**Comment by karkaaa** [comment]
What is the status?

**Comment by metasite-research** [comment]
I installed latest openvas scanner and found this:

1. SSL/TLS: Missing `secure` Cookie Attribute

```
The cookies:

Set-Cookie: lang=en; expires=Thu, 15-Apr-2021 14:04:09 GMT; Max-Age=***replaced***; path=/

are missing the "secure" attribute.
```

2.  Missing `httpOnly` Cookie Attribute
```
The cookies:

Set-Cookie: lang=en; expires=Thu, 15-Apr-2021 14:04:09 GMT; Max-Age=replaced; path=/

are missing the "httpOnly" attribute.
```


FW ver.: multiOTP 5.6.1.5
Model name: multiOTP Enterprise 501V

**Comment by karkaaa** [comment]
I installed latest openvas scanner and found this:

1. SSL/TLS: Missing secure Cookie Attribute

```
The cookies:

Set-Cookie: lang=en; expires=Thu, 15-Apr-2021 14:04:09 GMT; Max-Age=***replaced***; path=/

are missing the "secure" attribute.
```

2. Missing httpOnly Cookie Attribute

```
The cookies:

Set-Cookie: lang=en; expires=Thu, 15-Apr-2021 14:04:09 GMT; Max-Age=replaced; path=/

are missing the "httpOnly" attribute.
```

FW ver.: multiOTP 5.6.1.5
Model name: multiOTP Enterprise 501V

**Comment by syscoch** [comment]
Hello,
We will provide a patch in the following days to fix the cookie attribute.

**Comment by multiOTP** [comment]
We will provide a patch in the following days to fix the cookie attribute.
Have a great day

**Comment by K-razy** [comment]
Hello, any update on this request ? It seems to be very useful :) 
Thanks in advance.

**Comment by karkaaa** [comment]
MultiOTP support wrote for me:

Hello,

There will be a new release on the **31.08.2020**
**Please try it and let us know if it’s ok.**
Have a good day.

**Comment by K-razy** [comment]
Hello, 
Did you have some news about that release ? 
i expected it yesterday as you mentionned but still nothing :(.
Thanks in advance for your time.

Best Regards

**Comment by multiOTP** [comment]
Cookie attributes have been adapted in version 5.8.0.0. This issue willl be closed after public availability of the release.

**Comment by multiOTP** [comment]
Hello,
The 5.8.0.3 commercial versions is in final tests on several sites and will be released the 8. October 2020
Regards,

**Comment by karkaaa** [comment]
@multiOTP 
What status?

**Comment by K-razy** [comment]
@multiOTP 
Is the release abandonned ?

Thanks in advance for your time

**Comment by multiOTP** [comment]
The 5.8.0.x release has been post-poned due to a quality issue.
Stay tuned.

**Comment by karkaaa** [comment]
@multiOTP 
What status?

**Comment by multiOTP** [comment]
5.8.0.6 is already published to several customers.
Version 5.8.1.0 is in the pipe and will be in general availability on Friday 12. February.
Best regards,

**Comment by multiOTP** [comment]
Version 5.8.1.0 is available for general availability.

**Comment by karkaaa** [comment]
Not fixed on  5.8.1.1 and same vulnerability @multiOTP

**Comment by multiOTP** [comment]
Hello,
Thx for the update, webserver config is fixed in the new virtual appliances, but not backported in previous virtual appliances (before version 010).
Fix will be published in the 5.8.2.x
Regards,

**Comment by karkaaa** [comment]
When will be published?

**Comment by multiOTP** [comment]
Hello,
The 'vulnerable' detected cookie by OpenVAS was a language option cookie.
Anyway, we have fixed this issue for previous virtual appliance also, as weel as 'TCP timestamps' and 'weak SSL encryption' warnings.
5.8.1.9 update is running test units on various virtual appliance (starting on version 002) and will be available in the next hours.
Regards,

**Comment by multiOTP** [comment]
The version 5.8.1.9 is now available and has been tested using OpenVAS on virtual appliance foundations from 002 to 010.

**Comment by karkaaa** [comment]
@multiOTP how to download?

**Comment by multiOTP** [comment]
Hello,
Open source edition : https://download.multiotp.net/ or https://github.com/multiOTP/multiotp/releases/tag/5.8.1.9
Enterprise edition : https://firmware.multiotp.com/enterprise/update/ (the link should be available from the web interface, on the update page)
Pro edition : https://firmware.multiotp.com/pro/update/ (the link should be available from the web interface, on the update page)
Best regards,

**Comment by karkaaa** [comment]
now i found and i will try

thank you
