### ISSUE TITLE
ldaps issues Windows 2019 AD?

### ISSUE THREAD

**Issue by mschaap204** [multiOTP/multiotp#76]
Hi,

I'm configuring MultiOTP to use the Windows A/D password as Pin prefix (Windows 2019 domain controller)

For security reasons we want to use ldaps instead of ldap.

The synchronisation of users works fine with ldaps.

However when testing/checking a user I get the error below:
99 ERROR: Authentication failed (and other possible unknown errors) 

If I switch back to ldap, then it works. (change ldaps://vb-dc01.vb.local to ldap://vb-dc01.vb.local)
When I switch back to ldaps, the authentication keeps working until the ldap_hash_cache_time has expired.

Below the options I've configured:
default_request_ldap_pwd=1
default_request_prefix_pin=1
ldap_activated=1
ldap_base_dn=DC=vb,DC=local
ldap_bind_dn=CN=Service Account VB-OTP01,OU=Service Accounts,OU=Vanboxtel,DC=vb,DC=local
ldap_domain_controllers=ldaps://vb-dc01.vb.local
ldap_group_attribute=memberOf
ldap_group_cn_identifier=sAMAccountName
ldap_in_group=OTP_Users
ldap_port=
ldap_server_password:=<password here>
ldap_server_type=1
ldap_ssl=0
ldap_time_limit=30
ldaptls_reqcert=auto
ldaptls_cipher_suite=HIGH:!TLSv1:!SSLv3:!SSLv2

Version: 5.4.1.6

Are there any issues using MultiOTP in combination with Windows 2019 A/D?

Or have I configured something wrong and what can I do to debug/solve this problem?

Thank you.
Mark

**Comment by multiOTP** [comment]
Hello,
we have done several tests with other Windows server edition and we have not encountered this issue.

We will setup an lab with server 2019 next week then we will let you know if we have found the problem.

Have a good day

**Comment by mschaap204** [comment]
Greetings,

Hope you're all doing well.

Have you been able to test the ldap integration with Windows 2019?

Thank you.

Kind regards,
Mark Schaap

**Comment by soleroitsolutionsltd** [comment]
Did you ever manage to have ldaps working ?

**Comment by multiOTP** [comment]
When we wanted to make a lab with Windows Server 2019, Microsoft took it out of downloads. We are now planning on trying Windows server 2019  in the next weeks. We will keep you posted.

**Comment by soleroitsolutionsltd** [comment]
They are [back](https://www.microsoft.com/en-US/evalcenter/evaluate-windows-server-2019?filetype=ISO) (for quite some time TBH):

**Comment by multiOTP** [comment]
Please be sure that LDAPS is working on Windows 2019. By default in Windows 2019, the Active Directory Certificate Services is *not* installed, and you have *to install it* and *to configure it*.
After that, you will be able to use LDAPS connection.
Take also a look here : https://social.technet.microsoft.com/Forums/en-US/2b651329-4210-48d8-8e1c-bbff53f5a6c4/event-id1220-ldap-over-secure-sockets-layer-ssl-will-be-unavailable-at-this-time-because-the?forum=winservergen
