### ISSUE TITLE
RDweb + multiOTP problem

### ISSUE THREAD

**Issue by qzem** [multiOTP/multiotp#78]
Hi!

I've tried to setup Multiotp on RDweb server. I have successfully installed multiotp credential provider, and connect to multiotp server. Authentication (login) is working with no problems, when I try to connect on rdweb sever locally or vi remote desktop program. But if I use rdweb portal I receive The user name or password that you entered is not valid. Try typing it again.

![image](https://user-images.githubusercontent.com/1011302/72337136-51135c00-36c2-11ea-9db5-4eff72be865b.png)

For configuring MultiOTP on RDweb server used this [tutorial](http://roman.gallauner.at/?p=886)

Any help would be appreciated.

Thanks!

**Comment by multiOTP** [comment]
Hi,

Could you please set debug=1 and developer_mode=1 in multiotp.ini file, try to login again, and send us the log file to info@multiotp.net ?

Have a nice day

**Comment by qzem** [comment]
I've enabled debugging and developer and I found out that it is a problem in username interpretation. On server there are user data stored in files named something like this name.surname@domain.com.db. But we also use shoter names for login in domain, something like names, and when I try to log in with this short name I've got an error that names.db is missing so I copy original .d file and change the name into names.db. Then the login goes trough. But this is just some odd workaround, that I would like to use it. Btw if I try to login in with long name name.surname@domain.com, also won't go trough. Strange thing with this login is, that there is notihg in debugg log to see. Not a single line of error. To be even more confusing, when I use another user that only has name@domain.com it goes authentication goes trough. I belive that the problem lies here:

`        if ( HttpContext.Current.User.Identity.IsAuthenticated == true )
        {
	    string strPre = "zimoc01\\"
	    string strSuf = "@celje.si"
            string strOTPUsername = HttpContext.Current.User.Identity.Name;
			if (strOTPUsername.Split('\\').Length > 1) strOTPUsername = strOTPUsername.Split('\\')[1];
			if (strOTPUsername.Split('@').Length > 0) strOTPUsername = strOTPUsername.Split('@')[0];
			
			bool bOTPAuthenticated = false;

			if (Session["UserOTP"] != null)
			{
			  string strOTP = (string)Session["UserOTP"];
			  if (!string.IsNullOrEmpty(strOTP) && Regex.Match(strOTP,ConfigurationManager.AppSettings["OTPRegex"]).Success && !string.IsNullOrEmpty(strOTPUsername) && Regex.Match(strOTPUsername,ConfigurationManager.AppSettings["OTPUsernameRegex"]).Success)
			  {
				ProcessStartInfo oOTPStartInfo = new ProcessStartInfo();
				oOTPStartInfo.FileName = ConfigurationManager.AppSettings["MultiOTPPathAndName"];
				oOTPStartInfo.Arguments = strOTPUsername + " " + strOTP;
				oOTPStartInfo.CreateNoWindow = true;
				oOTPStartInfo.UseShellExecute = true;
				Process oOTP = Process.Start(oOTPStartInfo);
				oOTP.WaitForExit();
				bOTPAuthenticated = (oOTP.ExitCode == 0);
			  }
			}`

I don't know how to put usernames in correct form to be properly detected in arguments with MultiOTP. Because when I test username trough MultiOTP Credential provider installation all previously mentioned shapes of usernames are properly validated,

**Comment by syscoch** [comment]
Hello,
it looks like you created your user in multiOTP with the following format name.surname@domain.com
When you copy the file, you should name it name.surname.db and not name.db in order to work with the login name.surname
In the RDWEB code posted above you can see that the RDWEB is taking into account only the part before the @ and it's sending this part to multiOTP. That is the reason why you get the user unknown error.

If you want the RDWEB to work with name.surname@domain.com, you need to chang this line 
`oOTPStartInfo.Arguments = strOTPUsername + " " + strOTP;`
to
`oOTPStartInfo.Arguments = HttpContext.Current.User.Identity.Name+ " " + strOTP;`

Hope this helps.

Have a great day

**Comment by stevegoc** [comment]
Hi,

I've been trying to use Roman's tutorial (thanks Roman) for my windows 2016 rds RD web page, but having no luck. Can someone help me by providing a copy of their login.aspx and web.confg pages just where I need to add the code.

thank you greatly

Steve.

**Comment by stevegoc** [comment]
I seem to be getting a bit further on, however when I login it just denies me access.  Can you confirm if this is the correct logation in login.aspx for the "In the method just before the end of the block:LoginPageLoadAsync()if ( Request.QueryString != null )"

    protected void Page_Load(object sender, EventArgs e)
    {
        RegisterAsyncTask(new PageAsyncTask(LoginPageLoadAsync));
        ExecuteRegisteredAsyncTasks();
    }
    
    private async Task LoginPageLoadAsync()
    {
       
if ( Request.QueryString != null )

if( Request.Form["UserOTP"] != null ) Session["UserOTP"] = (string)Request.Form["UserOTP"]; 

        {
           
NameValueCollection objQueryString = Request.QueryString;
            if ( objQueryString["ReturnUrl"] != null )




thanks

steve.

**Comment by stevegoc** [comment]
Sorry I think I've now found the correct please to put that piece of code.

Still getting username or password entered not valid, looking at multiotp log (debug/developer) and its not showing anything, which tells me perhaps its getting as far as running the multiotp.exe in the web.config file.

Any ideas?

thanks

steve.

**Comment by stevegoc** [comment]
I seem to have it working now!  basically I was using the wrong copy of multiotp locally on my server, I needed to have the server setting set in the ini file.

**Comment by multiOTP** [comment]
Thanks for the feedback.
Best regards

**Comment by sabych** [comment]
> Кажется, теперь у меня все работает! по сути, я использовал неправильную копию multiotp локально на своем сервере, мне нужно было установить настройки сервера в ini-файле.

Good afternoon. I have a similar problem to yours, tell me how you solved it? I will be grateful to you

**Comment by sabych** [comment]
> Спасибо за ответ. Сформулированы пожелания

Can someone help me by providing a copy of their login.aspx and web.confg pages just where I need to add the code.

thank you greatly

**Comment by multiOTP** [comment]
Hello Sabych,
As explained here https://roman.gallauner.at/?p=886,

After installation, RDWeb ends up in **C:\Windows\Web\RDWeb**. The file we are interested in is located in the subdirectory Pagesand there in the directory of the desired language: **login.aspx**.

At the top of the @Import lines we add
```
<% @Import Namespace="System.Diagnostics" %>
<% @Import Namespace="System.Text.RegularExpressions" %>
<% @Import Namespace="System.Configuration" %>
```

For the strings (under Comment // Localizable Text ) the following:
```
const string L_OTPLabel_Text = "OTP:";
```

In the method **LoginPageLoadAsync()** right before the end of the **if ( Request.QueryString != null )** block:
```
            }
            // INSERT
            if( Request.Form["UserOTP"] != null ) Session["UserOTP"] = (string)Request.Form["UserOTP"];
            // INSERT
        }
 
        //
        // Special case to handle 'ServerConfigChanged' error from Response's Location header.
        //
```

Further down in the same method in the second **if ( HttpContext.Current.User.Identity.IsAuthenticated == true )** block we replace **SafeRedirect(strReturnUrlPage)**; with:

```
string strOTPUsername = HttpContext.Current.User.Identity.Name;
if (strOTPUsername.Split('\\').Length > 1) strOTPUsername = strOTPUsername.Split('\\')[1];
if (strOTPUsername.Split('@').Length > 0) strOTPUsername = strOTPUsername.Split('@')[0];
			
bool bOTPAuthenticated = false;
 
if (Session["UserOTP"] != null)
{
  string strOTP = (string)Session["UserOTP"];
  if (!string.IsNullOrEmpty(strOTP) && Regex.Match(strOTP,ConfigurationManager.AppSettings["OTPRegex"]).Success && !string.IsNullOrEmpty(strOTPUsername) && Regex.Match(strOTPUsername,ConfigurationManager.AppSettings["OTPUsernameRegex"]).Success)
  {
    ProcessStartInfo oOTPStartInfo = new ProcessStartInfo();
    oOTPStartInfo.FileName = ConfigurationManager.AppSettings["MultiOTPPathAndName"];
    oOTPStartInfo.Arguments = strOTPUsername + " " + strOTP;
    oOTPStartInfo.CreateNoWindow = true;
    oOTPStartInfo.UseShellExecute = true;
    Process oOTP = Process.Start(oOTPStartInfo);
    oOTP.WaitForExit();
    bOTPAuthenticated = (oOTP.ExitCode == 0);
  }
}
 
if(bOTPAuthenticated)
{
  if (String.IsNullOrEmpty(strReturnUrlPage))
    Response.Redirect("default.aspx");
  else
    SafeRedirect(strReturnUrlPage);
}
else
{
  FormsAuthentication.SignOut(); 
  bFailedLogon = true;
  if (bFailedAuthorization) bFailedAuthorization = false; 
}
```

Finally, we add the necessary parameters in **C:\Windows\Web\Web.Config** the **appSettings** block :
```
<add key="MultiOTPPathAndName" value="C:\\Pfad\\zu\\multiotp\\multiotp.exe" />
<add key="OTPUsernameRegex" value="^[0-9a-zA-Z]*$" />
<add key="OTPRegex" value="^[0-9]{6}$" />

```

That was the code, now we have to insert the OTP input field - this happens after the password field (just search for “UserPass”) after the final one insert the following:
```
<tr>
  <td>
    <table width="300" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td width="130" align="right"><%=L_OTPLabel_Text%></td>
        <td width="7"></td>
        <td align="right">
          <label><input id="UserOTP" name="UserOTP" type="password" class="textInputField" runat="server" size="23" autocomplete="off" /></label>
        </td>
      </tr>
    </table>
  </td>
</tr>
```

Assuming a MultiOTP copied to the configured path including the appropriate .INI (be careful: if logging is switched on, the RDWeb Application Pool Account must have write permissions!), the whole thing should look something like this:
![image](https://github.com/multiOTP/multiotp/assets/9338189/9cb93f60-e754-4ba4-a1fd-49669d93208e)

**Comment by sabych** [comment]
1) good afternoon, there is no web.config file in this path C:\Windows\Web\Web.Config 
2) I'm using the web.config file in this path: C:\Windows\Web\RDWeb\Pages
2) also a question: In this path <add key="MultiOTPPathAndName" value="C:\\Pfad\\zu\\multiotp\\multiotp.exe" /> should you specify the path to the server? 
3) I indicate this path, I will give a piece of code from the web.config file: 
<?xml version="1.0" encoding="UTF-8"?>

<configuration>
  
  <appSettings>
    
    <add key="PasswordChangeEnabled" value="true" />
    **<add key="MultiOTPPathAndName" value="\\192.168.200.68\c$\MultiOTP\windows\multiotp.exe" />**
    <add key="OTPUsernameRegex" value="^[0-9a-zA-Z]*$" />
    <add key="OTPRegex" value="^[0-9]{6}$" />
      
    
    <add key="LocalHelp" value="false" />

help me please

**Comment by sabych** [comment]
<configuration>
  
  <appSettings>
    
    <add key="PasswordChangeEnabled" value="true" />
    <add key="MultiOTPPathAndName" value="\\192.168.200.68\c$\MultiOTP\windows\multiotp.exe" />
    <add key="OTPUsernameRegex" value="^[0-9a-zA-Z]*$" />
    <add key="OTPRegex" value="^[0-9]{6}$" />

**Comment by sabych** [comment]
<add key="MultiOTPPathAndName" value="\\192.168.200.68\c$\MultiOTP\windows\multiotp.exe" />
    <add key="OTPUsernameRegex" value="^[0-9a-zA-Z]*$" />
    <add key="OTPRegex" value="^[0-9]{6}$" />

**Comment by multiOTP** [comment]
Hello,
Yes, you have to give the complete local path to the multiotp.exe binary file.
Regards,

**Comment by sabych** [comment]
> Здравствуйте. Да, вам необходимо указать полный локальный путь к двоичному файлу multiotp.exe. С уважением,

thanks, where is this binary file located? show the way

**Comment by sabych** [comment]
> Здравствуйте. Да, вам необходимо указать полный локальный путь к двойному файлу multiotp.exe. С уважением,
I indicate this file:
![image](https://github.com/multiOTP/multiotp/assets/149696986/9e65810a-e695-4ad5-9bf7-a08439229a56)

**Comment by multiOTP** [comment]
Yes, it's were you put the file. In this case: **C:\MultiOTP\Windows\multiotp.exe**
Rergards

**Comment by sabych** [comment]
> Да, это место, куда вы положили файл. В данном случае: **C:\MultiOTP\Windows\multiotp.exe** С уважением

Thank you, but the thing is that the multiotp server and the server with the RD Web access role are different, so I specify the path to the multiotp server on the RD Web server, or should the multiotp server and the RD Web server be on the same server?

**Comment by sabych** [comment]
> Да, это место, куда вы положили файл. В данном случае: **C:\MultiOTP\Windows\multiotp.exe** С уважением
I specify the path to the multiotp server, but it still works. After entering the login, password and code, an error appears: Incorrect password
![image](https://github.com/multiOTP/multiotp/assets/149696986/d6993217-e0bd-4747-a0ca-255925d8d67d)

**Comment by sabych** [comment]
> Yes, it's were you put the file. In this case: **C:\MultiOTP\Windows\multiotp.exe** Regards

Colleagues, do you have any news?

**Comment by sabych** [comment]
> Привет!
> 
> Я попытался настроить Multiotp на сервере RDweb. Я успешно установил поставщик учетных данных multiotp и подключаюсь к серверу multiotp. Аутентификация (вход в систему) работает без проблем, когда я пытаюсь подключиться к серверу rdweb локально или к программе удаленного рабочего стола vi. Но если я использую портал rdweb, я получаю сообщение. Введенное вами имя пользователя или пароль недействительны. Попробуйте ввести его еще раз.
> 
> ![изображение](https://user-images.githubusercontent.com/1011302/72337136-51135c00-36c2-11ea-9db5-4eff72be865b.png)
> 
> Для настройки MultiOTP на сервере RDweb используйте это [руководство.](http://roman.gallauner.at/?p=886)
> 
> Любая помощь будет оценена по достоинству.
> 
> Спасибо!

Good afternoon, I have exactly the same problem as you. Could you tell me how you solved it? thank you in advance

**Comment by sabych** [comment]
> Кажется, теперь у меня все работает! по сути, я использовал неправильную копию multiotp локально на своем сервере, мне нужно было установить настройки сервера в ini-файле.

Good afternoon, I have exactly the same problem as you. Could you tell me how you solved it? thank you in advance

**Comment by sabych** [comment]
> Здравствуйте! Мы считаем, что в качестве первого шага лучше всего разместить сервер multiOTP и веб-службу удаленных рабочих столов на одном сервере.
> 
> С наилучшими пожеланиями

I placed the multiotp and rd web server on the same server but I still get the error: incorrect password or login

**Comment by sabych** [comment]
> Hello, we think it's best to have multiOTP server and RD Web service on the same server as a first step.
> 
> Best regards

Colleagues, good afternoon. Today I re-deployed the multiotp server again and combined it with the RD Web Access role. In the web.config file I specified the path to both the server binary file C:\MultiOTP\windows\multiotp.exe and the multiOTPCredentialProvider-5.9.6.1 file along the path C:\Program Files\multiOTP\multiotp.exe still does not work after When entering the password and token, it says the wrong password or login. Any other ideas what could be wrong?

**Comment by qzem** [comment]
@sabych have you tried using a user name in different form. I think for us it only worked if we used domain\username. Also check if you have different username for older windows (pre 2000) defined. And try that one. Good luck!

**Comment by sabych** [comment]
> @sabychПробовали ли вы использовать имя пользователя в другой форме. Я думаю, что для нас это сработало, только если мы использовали домен\имя пользователя. Также проверьте, определено ли у вас другое имя пользователя для старых окон (до 2000 года). И попробуйте это. Удачи!

colleagues, I tried names in a different format and it still doesn’t work

Still getting username or password entered not valid, looking at multiotp log (debug/developer) and its not showing anything, which tells me perhaps its getting as far as running the multiotp.exe in the web.config file.

any other ideas?

thanks

**Comment by sabych** [comment]
> any other ideas?

Colleagues, any other ideas?

**Comment by multiOTP** [comment]
Hello,

You have inserted bad syntax in the files.
Here are an example of the modified files
- **C:\Windows\Web\RDWeb\Web.config**
[Web.config.txt](https://github.com/multiOTP/multiotp/files/13453075/Web.config.txt)
Compare with original: [Web-org.config.txt](https://github.com/multiOTP/multiotp/files/13453082/Web-org.config.txt)
- **C:\Windows\Web\RDWeb\Pages\en-US\login.asp**
[login.aspx.txt](https://github.com/multiOTP/multiotp/files/13453077/login.aspx.txt)
Compare with original: [login-org.aspx.txt](https://github.com/multiOTP/multiotp/files/13453086/login-org.aspx.txt)

Be sure also that your multiOTP folder is writable by the RDWeb Application Pool Account.

In order to have some logs, you will have to enable log in the multiotp.ini which is in our example : **C:\Program Files\multiOTP\config\multiotp.ini** :
- search for the line **log=0** and change to **log=1**

Best regards,

**Comment by multiOTP** [comment]
For question and feedback, please refer to the issue #180, and not this one anymore.

**Comment by sabych** [comment]
> For further questions and feedbacks, please refer to the issue #180, and not this one anymore.

Thanks colleagues, I figured it out. My pool account did not have rights. everything works now.
