### ISSUE TITLE
Account description

### ISSUE THREAD

**Issue by arddg** [multiOTP/multiotp#79]
Hi! Is it possible to make Multiotp not to take user's description from Active Directory's Description field? I mean the description which is displayed under QR code in "3)Token provisioning."

**Comment by multiOTP** [comment]
Hello,
this is not actually possible. We will add this request to our roadmap.

Have a nice day

**Comment by arddg** [comment]
Great! Thanks!
Otherwise now user can see info from description filed when he opens some Authenticator app on his phone instead of his username. And sometimes that info looks not very good :)) If Description field is empty then username is displayed as it should.

**Comment by mchubby** [comment]
You can replace

- page display:
Replace `{MultiotpUserDescription}` in the template file
https://github.com/multiOTP/multiotp/blob/7ab20a/templates/template.html#L315
by one of the template tags at https://github.com/multiOTP/multiotp/blob/93b21f5/multiotp.class.php#L8952 e.g. `{MultiotpUserAccount}`

- for QR generation (untested):
Replace in
https://github.com/multiOTP/multiotp/blob/93b21f5/multiotp.class.php#L9015
`$url = $this->GetUserTokenUrlLink($user, $descr, $qrcode_format);`
Second parameter to GetUserTokenUrlLink is $display_name, so maybe you could pass a custom string (e.g. `"PRO: $user"` instead)

HTH
