### ISSUE TITLE
Mysql backend

### ISSUE THREAD

**Issue by sunojvijayan** [multiOTP/multiotp#8]
Hi i am trying to enable mysql backend. 

when i run this command

multiotp.php -display-log -initialize-backend

do i need apache installed. coz i have only mysql and php installed in my linux server.

**Comment by multiOTP** [comment]
No, Apache is not used for that, you have to provide an existing MySQL server, database, username and password
multiotp -config backend-type=mysql sql-server=fqdn.or.ip sql-database=dbname
multiotp -config sql-username=user sql-password=pass
multiotp -initialize-backend

**Comment by sunojvijayan** [comment]
Thanks a lot

**Comment by selvakumar89** [comment]
Hi..
Is there any possible to use MSSQL instead of MySQL server?

**Comment by multiOTP** [comment]
Hello,
No, only flat files and MySQL backends are supported. We don't have plan to develop MSSQL support. But it's open source, so perhaps somebody want to do it :-)
Regards,

**Comment by umapati** [comment]
i dont see any pull requests to allow for any changes. since this project is under LGPL, do i have to post the modifications back to this stream or create my own?
