### ISSUE TITLE
WebUI painfully slow

### ISSUE THREAD

**Issue by Theoooooo** [multiOTP/multiotp#80]
I've recently install the last official version of multiotp (5.6.1.5) under a debian 10 with the service apache2 and php7.3.

I've installed the necessary modules required for the website to work properly but every action performed under the webui is really slow (about 20 seconds between each action o the site) and the user addition does not work.

It's also really slow just for the .php script to load up the first time and for about 30 secondes, i can't do anything until the website prompt me the credentials to login in. I also got no error about permissions or functions missing for the php scripts to work properly. I've installed the dependency required when i encounter these errors.

Despite this slow website, i've watch the ressources querried by apache2 and it's like nothing is happening under the VM : no CPU or RAM usage peak or disk usage peak (nothing more than 6KB/s)

Inside the documentation, nothing is given for the installation of the webservice.

Is there other steps to do to be able to use the webUI without these huge slowdown ?

**Comment by multiOTP** [comment]
Hello,
Was it something linked with some insufficient rights ?

**Comment by ahuxtable** [comment]
I have this same issue - I was running an older version of MultiOTP which was running fine and upgraded to 5.6.1.5 and now the web gui is slow exactly as described above.  Really like to know what fixed it.

Centos 7, Apache 2.4, Php 5.4.

**Comment by multiOTP** [comment]
Hello "ahuxtable",
We will release the source code of version 5.8.0.3 the 2. October 2020.
Could you please install it and give us a feedback.
If the Gui is still slow on installation, we could arrange a remote debug with you, as we don't have a specific idea for your issue.
Regards,

**Comment by artemzheshko** [comment]
Hello,
i had a similar problem. The point was that the server could not receive data from the dns-server. The default values in file /etc/resolv.conf were 8.8.8.8 and 8.8.4.4. When i set correct dns the site and other functionality worked fine again.

**Comment by ahuxtable** [comment]
My DNS is working fine but still have the issue, at the moment I'm just dealing with it.

**Comment by multiOTP** [comment]
Hello, 
we are still working on the 5.8.0.x release.
For the slow webui, it's probably due to a call to the stat page. Yyou could try to disable this call in the multiOTP /etc/multiotp/multiotp.ini file by changing the value of anonymous_stat to 0

anonymous_stat=0

Let us know if it's better.

**Comment by ahuxtable** [comment]
Tried and that has made it much more responsive.  Thanks.
