### ISSUE TITLE
Feature request : objectClass posixAccount

### ISSUE THREAD

**Issue by xenofree** [multiOTP/multiotp#83]
Hi,

Is it possible to add an option in the config file for the ldap filter.

ldap_sync filter is (&(objectClass=posixAccount)(".$this->_cn_identifier."=".$username."))

Can you add an on option to make this configurable ?
Something like ldap_objectClass_filter=inetOrgPerson

Regards,

**Comment by syscoch** [comment]
Hello,
thanks for your comment. We will add this to our nice to have list.
Regards,

**Comment by multiOTP** [comment]
Hello,
The last version [5.9.5.5](https://github.com/multiOTP/multiotp/releases/tag/5.9.5.5) offer a LDAP filter customization.
Regards,
