### ISSUE TITLE
Few questions regarding MultiOTP

### ISSUE THREAD

**Issue by leungda** [multiOTP/multiotp#87]
Hi,

I am very happy with the MultiOTP. After I few testings, I discovered some questions listed below.

(1) I am using a domain controller with MultiOTP, Everything works fine on workstations with domain sign in. When I switch to local account sign in using ".\localaccounttest" as a username, it doesn't seem to allow me to sign in locally. Is there any way to do a local account sign in without MultiOTP involved?

(2) I tried to put a crontab using "* * * * * multiotp -ldap-users-sync". It doesn't seem to work. I want to get user accounts to sync every minute automatically.

(3) Do you know any info about to add MultiOTP on Microsoft Exchange Webmail "OWA"?

(4) Do you know how to get the provider in .msi format for domain controller deployment? Also, how can I install the .exe in silent mode with all the perimeters?

**Comment by multiOTP** [comment]
Hello,
1) You need to create the localaccounttest user in your local multiOTP
2) Our advice is to run it every 5 minutes. In your cron command please specify the full path of multiotp something like /usr/local/bin/multiotp/multiotp.php -ldap-users-sync
3) We have not yet tried OTP in OWA but the main steps are : 
   Activate ADFS for OWA
   Activate multiOTP in ADFS. Some documentation is available [here](https://roman.gallauner.at/?p=880)
4) Actually there is no .msi available. And you cannot run the .exe in silent mode for security reasons. During the setup, the process has to check if OTP authentication is working othervise you may loose access to your computer.

Best regards

**Comment by leungda** [comment]
Sorry, One more question.

When I delete a user from Active Directory, how can I sync it to multiotp?
Will this "-ldap-users-sync" do the job? or I need another switch?

**Comment by multiOTP** [comment]
Hello,
WHen a user is deleted on Active Directory, he is automatically desactivated in multiOTP when you do the sync, but he is not deleted in order to prevent the loss of the specific OTP seed if needed again.
Regards,
