### ISSUE TITLE
help to reset lincese

### ISSUE THREAD

**Issue by karkaaa** [multiOTP/multiotp#89]
Hi,

I write email to support and nothing.

Please help because i reinstalled multiotp and can not use.

**Comment by multiOTP** [comment]
Hello Karolis,

Sorry for the delay, your request from yesterday was a little bit special as the licence bought with the specified invoice was a Pro version, which has been cancelled and upgraded to an Enterprise Edition.

The best way for us to reset a licence is to send us the licence number, or the serial number of the current used device.

Best regards,
