### ISSUE TITLE
Can not activate multiotp - user does not exist... again (multiOTP Credential Provider)

### ISSUE THREAD

**Issue by soleroitsolutionsltd** [multiOTP/multiotp#91]
Well I'm having this exact same issue

https://github.com/multiOTP/multiotp/issues/41

except that I am running v 5.6.1.5 on a server 2019.

That being said the issue is exactly the same. I have also followed the procedure about creating a local user and testing against it but no go

![Screenshot 2020-07-20 at 20 24 05](https://user-images.githubusercontent.com/15646114/87972763-bc9e1200-cac7-11ea-8133-0d2689885e34.jpg)

Any help most welcome - where would I see the relevant logs ?

**Comment by soleroitsolutionsltd** [comment]
well doesn't seem to be much traffic here but FWIW I am still seeing this (blocking) issue.

I tried to run the checkmultiotp.cmd script and it reports all tests as successful
```
Check the PHP multiOTP class using the check.multiotp.class.php file.
OK! ALL 64 TESTS HAVE PASSED SUCCESSFULLY !
- OK! multiOTP class tests successful

- Stop and uninstall the multiOTP web service
Stop and remove the service multiOTPserverTest


OK! ALL 28 TESTS HAVE PASSED SUCCESSFULLY !
```
yet I have a doubt with this one

```
Authenticate test_user with next token 520489 with prefix 1234 using CHAP
- OK! Token of the user test_user successfully accepted using CHAP
Reply-Message := "ERROR: User doesn't exist"

Create user test_user@one.domain with the RFC test values HOTP token
- OK! User test_user@one.domain successfully created

Authenticate test_user@one.domain with the first token of the RFC test values
- OK! Token of the user test_user@one.domain successfully accepted
Reply-Message := "ERROR: User doesn't exist"
```

Is that the expected result ?

**Comment by multiOTP** [comment]
Have you checked if you are not missing the : Microsoft Visual C++ runtime

**Comment by soleroitsolutionsltd** [comment]
Which one specifically ? Do you have other dependencies ?

![Screenshot 2020-08-25 at 10 51 10](https://user-images.githubusercontent.com/15646114/91153805-febb0480-e6c0-11ea-9294-b287dc824028.jpg)

**Comment by K-razy** [comment]
Hello, 

Just by experencience, i made the mistake to put a different secret which causes this error.
Could you please verify that the secret configured on the client side is the same configured on the server side ? :) 

Hope it helps.

**Comment by soleroitsolutionsltd** [comment]
Thanks - I have re-checked and whatever the problem this is not it...

**Comment by multiOTP** [comment]
Last installation package is available here : https://download.multiotp.net/credential-provider/
It has been successfully tested on a "out-of-the-box" Windows 2019.
Regards,
