### ISSUE TITLE
windows 7 pro Login Error (multiOTP Credential Provider)

### ISSUE THREAD

**Issue by dhpark21** [multiOTP/multiotp#93]
I was tested Windows 7
Install pass, but at boot time, "Incorrect password or username"
What wrong?

but. windows 10 Work fine.
Thanks.

![image](https://user-images.githubusercontent.com/12795655/89134933-3b815900-d564-11ea-85a5-bc65200e7fee.png)
![image](https://user-images.githubusercontent.com/12795655/89134936-49cf7500-d564-11ea-8922-600a8f477e1a.png)

**Comment by soleroitsolutionsltd** [comment]
Did you get to OTP prompt (ie user / pass / otp) ?
From that screenshot I'd say it is not active

**Comment by multiOTP** [comment]
Hello,
have you checked if you are not missing the : Microsoft Visual C++ runtime

Please keep us posted.

Have a good day

**Comment by multiOTP** [comment]
Closed because no return about this multiOTP Credential Provider issue, which should be resolved by installing the VIsual C++ runtime.
