### ISSUE TITLE
upgrade from 5.4 to 5.6

### ISSUE THREAD

**Issue by alexmateescu** [multiOTP/multiotp#94]
i am trying to upgrade both debian from 8 to 9 and multiotp 5.4 to 5.6 on a VM image that i have.
any how tos available to do that?

how could one export all the OTP codes from 5.4 and import in 5.6?

**Comment by multiOTP** [comment]
Hello,
Whats is the backend of your data? File based or Database based ?
In both cases, data will be kept if you do the update.
With a file bases backend, you will have nothing to do, the data scheme will be enhanced automatically.
With a database backend, The database schema upgrade willbe done automatically.

Have a look at the readme file, there is a "How can I upgrade from a previous version ?" section

Regards,

Andre

**Comment by alexmateescu** [comment]
Hi 
I am using the multiOTP open source Virtual Appliance.
I will try just to copy the files as instructed and see what is happening.

**Comment by alexmateescu** [comment]
did the copy of the files and checked everything. free radius starts and now i have the below error

_Failed parsing output from: /usr/local/bin/multiotp/multiotp.php -base-dir='/usr/local/bin/multiotp/' '%{User-Name}' '%{User-Password}' -request-nt-key -src='%{Packet-Src-IP-Address}' -tag='%{Client-Shortname}' -mac='%{Called-Station-Id}' -calling-ip='%{Framed-IP-Address}' -calling-mac='%{Calling-Station-Id}' -chap-challenge='%{CHAP-Challenge}' -chap-password='%{CHAP-Password}' -ms-chap-challenge='%{MS-CHAP-Challenge}' -ms-chap-response='%{MS-CHAP-Response}' -ms-chap2-response='%{MS-CHAP2-Response}' -state='%{State}': Invalid attribute name

ERROR: (0) multiotp: ERROR: Program returned code (0) and output ',LOG 2020-08-27 16:17:20 error System Error: database file /etc/multiotp/devices/ciscoasa.db for device ciscoasa does not exist from 192.168.210.1, LOG 2020-08-27 16:17:20 notice (user alexandru.mateescu) User OK: User alexandru.mateescu successfully logged in with TOTP token from 192.168.210.1,0 *OK: Token accepted, LOG 2020-08-27 16:17:20 debug Debug Debug: *Attributes sent to the RADIUS server: Filter-Id += "SG_VPN_Access" from 192.168.210.1,Filter-Id += "SG_VPN_Access" '_

**Comment by alexmateescu** [comment]
investigating further i have found that 5.4 is on freeradius v2 and the 5.6 on freeradius v3. Could there be a miscommunication between them? could that be the problem ?
i have also restored the config on a brand new ubuntu 16.04 machine which i have setup identically. with the first OTP created it was working. the moment i restored the users from the old one the above error showed up. i guess the backup-restore breaks something

**Comment by alexmateescu** [comment]
after another round of testing my conclusion is that the restore config is breaking something.

i have tried to backup/restore the config on 5.4 the old version. I cloned the virtual machine and tested that it works before applying the restored config. 

now the auth does not work anymore. so clearly something is wrong in the backup/restore even in v5.4 

also from the debug this line is what pop out the attributes sent to the radius server are somehow doubled and i guess that is the problem

**_debug Debug Debug: *Attributes sent to the RADIUS server: Filter-Id += "SG_VPN_Access" from 192.168.210.1,Filter-Id += "SG_VPN_Access" '_**

**Comment by alexmateescu** [comment]
The solution for successful migration:

1. On the multiotp running 5.4 upgraded to 5.6 by just copying the new files in the /usr/local/bin/multiotp folder. don't touch the files in etc (multiotp 5.4 is running with radius 2 by default in the appliance)
2. log on to the new upgraded version and save the configuration
3. deploy a new 5.6 appliance (it will come with radius 3) or install it manually
4. once you have it up and running -- make sure you have the same settings as the old one LDAP and so on and import users. don't worry about new QR codes being generated --- import the saved config and all the old QR codes will be restored
