### ISSUE TITLE
HELP - Multiotp Detailed audit log

### ISSUE THREAD

**Issue by belalalali** [multiOTP/multiotp#96]
Hi There;

I was asked to deliver a one month detailed audit log with the following:

all users used the tokens
all dates the users used the tokens 
the connection detailed like where they came from, where they are requesting to access.. which meas the host received the request.

and all this data are request for the previous month. is this possible... am sure that the data stored some where but how i can get it out.

also can i integrate such data to be exported to a database or some thing ?

**Comment by multiOTP** [comment]
Hello, have a look in the /var/log/multiotp folder, you should found what you want.
If you want to consolidate your log files, you should install a SysLog server in your infrsastructure, and setup the IP address of your SysLog server into multiOTP configuration.
Best regards,
Andre
