### ISSUE TITLE
BUG Clearing comments wrong string function used

### ISSUE THREAD

**Issue by moonbaseDelta** [multiOTP/multiotp#97]
Hello! During the work with customizing the service to get full PDF with generated QR on top of partly-cyrillic template I've found that some tags just dissapear (but browser scrutinized it to proper view though) and I only got half of a document for PDF. 

Long story short, instead of mb_substr() someone mistyped or was just mistaken and used substr() that returns inproper position with non-latin characters on input. 
In current github-code (but we use 5.6.1.5) I've found that code segment here: https://github.com/multiOTP/multiotp/blob/master/multiotp.class.php but maybe it appears somewhere on code also.
```
      // Clean language comments
      $html_cleaned = "";
      $html_slice = explode("{ML} -->",$html);
      foreach($html_slice as $one_slice) {
          $comment_pos = mb_strpos($one_slice,'<!-- {ML}');
          if(FALSE !== $comment_pos) {
            $html_cleaned.=substr($one_slice,0,$comment_pos);
          }
      }
      $html_cleaned .= end($html_slice);
      $html = $html_cleaned."\n";

      // Clean comments
      $html_cleaned = "";
      $html_slice = explode("-->",$html);
      foreach($html_slice as $one_slice) {
          $comment_pos = mb_strpos($one_slice,'<!--');
          if(FALSE !== $comment_pos) {
            $html_cleaned.=substr($one_slice,0,$comment_pos);
          }
```

Please fix this, it really takes a minor time.

**Comment by multiOTP** [comment]
Hello,
Thanks for the info.
it will be corrected in the next release.

Best regards

**Comment by multiOTP** [comment]
multibytes functions are now used almost everywhere (except for specific "byte operations")
