### ISSUE TITLE
Error: database file "X" for device "X" does not exist from IP [IP] for [IP]

### ISSUE THREAD

**Issue by artsiom-github** [multiOTP/multiotp#98]
Hello,
I am using VPN-gate Cisco with Multiotp. The following error below constantly appears in my logs. At the same time everything works fine. Why is the server trying to use this .db file? 
And how can i fix it?

_multiotp IP (duplicated using native syslog library for debug) Error: database file  /etc/multiotp/devices/cisco.db for device cisco does not exist from  IP [IP] for [IP]_

_multiotp IP Error: database file  /etc/multiotp/devices/cisco.db for device cisco does not exist from IP [IP] for [IP]_

Thank you.

Best regards,
Artsiom.

**Comment by multiOTP** [comment]
Hello,
multiOTP is looking for the file cisco.db because you have defined a client-shortname in your freeRadius settings for the cisco device.
Can you please try to clear the client-shortname ?

On our side we will correct this in our next release.

Have a good day

**Comment by multiOTP** [comment]
This bug has been corrected in version 5.8.x, and the 5.8.1.9 version is now available.
Regards,
