### ISSUE TITLE
LDAP User connect with PIN + OTP

### ISSUE THREAD

**Issue by K-razy** [multiOTP/multiotp#99]
Hi everyone, hope you are fine.

I'm trying to implement multiotp and i would like ldap users to connect only with username + PIN + OTP

Is that possible ? 
Because multiotp credential provider still asking me for Windows password.

Thanks in Advance

Kind Regards

**Comment by multiOTP** [comment]
Hello,
It will never be possible to log into windows without providing a credential that is related to your Microsoft account.
multiOTP is an EXTERNAL component, and there is no way to give access to your account using an EXTERNAL component.
Regards.
Andre

**Comment by K-razy** [comment]
Hello, 
Maybe my request wasn’t so clear let me clarify.

I was talking about the following scheme 

1 : Authentification through NLA (user provides his Microsoft Credential)

2 : MultiOTP as a second factor (before giving access to the Desktop) with PIN + OTP

Hope it sounds more clear to understand.

Thanks in advance for your time.

Kind Regard

**Comment by multiOTP** [comment]
Hello,
we are trying a new design based on privacyidea implementation.

We will keep you posted.

Kind regards

**Comment by multiOTP** [comment]
Hello,
Our alpha release is working as expected (NLA step 1, PIN + OTP step 2)
This new 6.x version will be available in the next monthes. Stay tuned.
Regards,
